import { SmsProviderIdEnum } from '@novu/shared';
import { genericProviderSchemas } from '../generic';
import { SmsProvidersSchemas } from '../types';

export const smsProviderSchemas: SmsProvidersSchemas = {
  [SmsProviderIdEnum.Twilio]: genericProviderSchemas,
  [SmsProviderIdEnum.Termii]: genericProviderSchemas,
  [SmsProviderIdEnum.Telnyx]: genericProviderSchemas,
  [SmsProviderIdEnum.SNS]: genericProviderSchemas,
  [SmsProviderIdEnum.Sms77]: genericProviderSchemas,
  [SmsProviderIdEnum.SmsCentral]: genericProviderSchemas,
  [SmsProviderIdEnum.Simpletexting]: genericProviderSchemas,
  [SmsProviderIdEnum.Sendchamp]: genericProviderSchemas,
  [SmsProviderIdEnum.RingCentral]: genericProviderSchemas,
  [SmsProviderIdEnum.Plivo]: genericProviderSchemas,
  [SmsProviderIdEnum.Nexmo]: genericProviderSchemas,
  [SmsProviderIdEnum.Mobishastra]: genericProviderSchemas,
  [SmsProviderIdEnum.MessageBird]: genericProviderSchemas,
  [SmsProviderIdEnum.Maqsam]: genericProviderSchemas,
  [SmsProviderIdEnum.Kannel]: genericProviderSchemas,
  [SmsProviderIdEnum.ISendSms]: genericProviderSchemas,
  [SmsProviderIdEnum.Infobip]: genericProviderSchemas,
  [SmsProviderIdEnum.Gupshup]: genericProviderSchemas,
  [SmsProviderIdEnum.GenericSms]: genericProviderSchemas,
  [SmsProviderIdEnum.FortySixElks]: genericProviderSchemas,
  [SmsProviderIdEnum.Firetext]: genericProviderSchemas,
  [SmsProviderIdEnum.Clickatell]: genericProviderSchemas,
  [SmsProviderIdEnum.BurstSms]: genericProviderSchemas,
  [SmsProviderIdEnum.BrevoSms]: genericProviderSchemas,
  [SmsProviderIdEnum.Bandwidth]: genericProviderSchemas,
  [SmsProviderIdEnum.AzureSms]: genericProviderSchemas,
  [SmsProviderIdEnum.AfricasTalking]: genericProviderSchemas,
  [SmsProviderIdEnum.Novu]: genericProviderSchemas,
  [SmsProviderIdEnum.BulkSms]: genericProviderSchemas,
  [SmsProviderIdEnum.Clicksend]: genericProviderSchemas,
  [SmsProviderIdEnum.EazySms]: genericProviderSchemas,
};
