export enum HttpHeaderKeysEnum {
  NOVU_SIGNATURE = 'novu-signature',
  NOVU_ANONYMOUS = 'novu-anonymous',
  NOVU_SIGNATURE_DEPRECATED = 'x-novu-signature',
  NOVU_ANONYMOUS_DEPRECATED = 'x-novu-anonymous',
  NOVU_FRAMEWORK_SDK = 'novu-framework-sdk',
  NOVU_FRAMEWORK_API = 'novu-framework-api',
  NOVU_FRAMEWORK_VERSION = 'novu-framework-version',
  USER_AGENT = 'user-agent',
  CONTENT_TYPE = 'content-type',
  ACCESS_CONTROL_ALLOW_ORIGIN = 'access-control-allow-origin',
  ACCESS_CONTROL_ALLOW_METHODS = 'access-control-allow-methods',
  ACCESS_CONTROL_ALLOW_HEADERS = 'access-control-allow-headers',
  ACCESS_CONTROL_MAX_AGE = 'access-control-max-age',
}
