/**
 * Paste-ready prompt for the user's own coding agent to finish wiring Novu's
 * LangChain bridge into an existing project. Kept as plain static text — the
 * agent inspects the project itself for architecture, package manager, and
 * provider.
 */
export const LANGCHAIN_AGENT_PROMPT = [
  'You are a coding agent working directly in this repository. Wire the Novu LangChain bridge into this existing project so a Novu-hosted agent runs on the app as its brain.',
  '',
  '## First, inspect the project',
  '- Router & layout: App Router vs Pages Router, whether a src/ directory is used, and where API routes live.',
  '- Package manager: infer from the lockfile (pnpm/yarn/bun/npm) and use it for any install.',
  '- Existing Novu wiring: search for @novu/framework usage and an app/api/novu route so you do not duplicate it.',
  '- LLM provider: check package.json and model config for a LangChain chat model already in use (any @langchain/* provider package) and the env var it reads.',
  '- Conventions: match the existing formatting, lint rules, naming, and import style.',
  '',
  '## Implement',
  '1. Bridge route — create the Novu route matching the project router, e.g. app/api/novu/route.ts:',
  '',
  '```ts',
  "import { serve } from '@novu/framework/next';",
  "import { supportAgent } from '../../novu/agents';",
  '',
  'export const { GET, POST, OPTIONS } = serve({ agents: [supportAgent] });',
  '```',
  '',
  '2. Agent handler — create an agent with agent() from @novu/framework/langchain, named after the agent identifier shown in the connect output. Return a { model, system, tools } config and Novu runs the agent and owns the tool-approval loop. Novu calls onMessage when a user sends a message and onAction when they click an action:',
  '',
  '```tsx',
  "import { agent } from '@novu/framework/langchain';",
  '',
  "export const supportAgent = agent('<agent-identifier>', {",
  '  onMessage: async (message, ctx) => {',
  '    return {',
  "      model: 'openai:gpt-4o-mini', // or a LangChain chat model instance",
  "      system: 'You are a helpful support agent.',",
  '      tools: [],',
  '    };',
  '  },',
  '});',
  '```',
  '',
  '3. Provider — reuse the LangChain chat model the project already uses. Only if none exists, add a LangChain provider package (an @langchain/* package such as @langchain/openai) and install `langchain` + `@langchain/core`. Read API keys from existing env vars — never hardcode secrets. Prefer returning the declarative { model, system, tools } config; only invoke a graph yourself and return its { messages } if you need full control.',
  '',
  '## Verify',
  "- Run the project's dev:novu script and confirm Novu can reach the bridge without errors.",
  '',
  '## Authoritative docs',
  '- Fetch https://docs.novu.co/llms.txt to discover doc pages, then append .md to any doc URL for clean markdown.',
].join('\n');
