/**
 * Paste-ready prompt for the user's own coding agent to finish wiring Novu's
 * AI SDK bridge into an existing project. Kept as plain static text — the agent
 * inspects the project itself for architecture, package manager, and provider.
 */
export const AI_SDK_AGENT_PROMPT = [
  'You are a coding agent working directly in this repository. Wire the Novu AI SDK bridge into this existing project so a Novu-hosted agent runs on the app as its brain.',
  '',
  '## First, inspect the project',
  '- Router & layout: App Router vs Pages Router, whether a src/ directory is used, and where API routes live.',
  '- Package manager: infer from the lockfile (pnpm/yarn/bun/npm) and use it for any install.',
  '- Existing Novu wiring: search for @novu/framework usage and an app/api/novu route so you do not duplicate it.',
  '- AI provider: check package.json and model config for an AI SDK provider already in use (any @ai-sdk/* package, an OpenAI-compatible client, Ollama, etc.) and the env var it reads.',
  '- Conventions: match the existing formatting, lint rules, naming, and import style.',
  '',
  '## Implement',
  '1. Bridge route — create the Novu route matching the project router, e.g. app/api/novu/route.ts:',
  '',
  '```ts',
  "import { serve } from '@novu/framework/next';",
  "import { supportAgent } from '../../novu/agents';",
  '',
  'export const { GET, POST, OPTIONS } = serve({ agents: [supportAgent] });',
  '```',
  '',
  '2. Agent handler — create an agent with agent() from @novu/framework/ai-sdk, named after the agent identifier shown in the connect output. Novu calls onMessage when a user sends a message and onAction when they click an action:',
  '',
  '```tsx',
  "import { agent, toModelMessages } from '@novu/framework/ai-sdk';",
  "import { generateText } from 'ai';",
  '',
  "export const supportAgent = agent('<agent-identifier>', {",
  '  onMessage: async (message, ctx) => {',
  '    return generateText({',
  '      model: /* reuse the project\u2019s existing provider + model */,',
  "      instructions: 'You are a helpful support agent.',",
  '      messages: toModelMessages(ctx),',
  '    });',
  '  },',
  '});',
  '```',
  '',
  '3. Provider — reuse the AI provider the project already uses. Only if none exists, add an AI-SDK-compatible provider (an @ai-sdk/* package or a community provider implementing the AI SDK provider interface — see https://ai-sdk.dev/providers); the handler calls generateText from the `ai` package, so a non-AI-SDK client will not work. Read API keys from existing env vars — never hardcode secrets.',
  '',
  '## Verify',
  '- Run the project\u2019s dev:novu script and confirm Novu can reach the bridge without errors.',
  '',
  '## Authoritative docs',
  '- Fetch https://docs.novu.co/llms.txt to discover doc pages, then append .md to any doc URL for clean markdown.',
].join('\n');
