FROM node:15.11.0

WORKDIR /usr/src/app

RUN npm i yarn -g --loglevel notice --force

COPY package.json .

COPY apps/widget ./apps/widget

COPY libs/dal ./libs/dal
COPY libs/sdk ./libs/sdk
COPY libs/testing ./libs/testing
COPY libs/shared ./libs/shared

COPY lerna.json .
COPY tsconfig.json .
COPY tsconfig.base.json .

RUN yarn install
RUN yarn bootstrap

COPY apps/widget/build ./apps/widget/build

CMD [ "npm", "run", "start:widget" ]
