# version: '3.7'
services:
  mongodb:
    image: mongo:8.0.3
    container_name: novu_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - novu_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: novu_redis
    ports:
      - '6379:6379'

volumes:
  novu_mongo_data:
