packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  - 'apps/*'
  - 'libs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # all packages in enterprise modules
  - 'enterprise/packages/*'
  - 'enterprise/workers/step-resolver'
  # playground apps
  - 'playground/*'

# Pnpm configuration
# Wait 24 hours (1440 minutes) before allowing packages to be installed
minimumReleaseAge: 1440
