packages:
  # all packages in subdirs of packages/ and components/
  - 'providers/*'
  - 'packages/*'
  # Angular projects - these are nested under the Angular workspace root, and need version bumps during release.
  - 'packages/notification-center-angular/projects/*'
  - 'apps/*'
  - 'libs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # all packages in enterprise modules
  - 'enterprise/packages/*'
  - 'enterprise/packages/libs/*'
  - 'enterprise/packages/web/*'
