export function generateNextjsSection(): string[] {
  return [
    '',
    '---',
    '',
    '## **6. NEXT.JS SPECIFIC REQUIREMENTS**',
    '',
    '### **6.1 – HYDRATION ERROR PREVENTION (CRITICAL)**',
    '',
    'Next.js has specific requirements to prevent hydration errors:',
    '',
    '1. **NEVER place the <Inbox /> component directly in server components.**',
    "2. **ALWAYS create a client-side wrapper component with 'use client' directive.**",
    '3. **ALWAYS use useState and useEffect to handle subscriber ID generation.**',
    '4. **ALWAYS show loading states during initial client-side hydration.**',
    '5. **NEVER use Date.now() or Math.random() in components that render on both server and client.**',
    '6. **ALWAYS validate that subscriber ID is null during SSR and initial render.**',
    '',
    '### **6.2 – REQUIRED FILE STRUCTURE FOR HYDRATION ERROR PREVENTION**',
    '',
    '#### **6.2.1 – Client-Side Wrapper Component**',
    'Create `src/components/NovuInboxWrapper.tsx`:',
    '',
    '```tsx',
    "'use client';",
    '',
    "import { Inbox } from '@novu/nextjs';",
    "import { useEffect, useState } from 'react';",
    '',
    'function getTemporarySubscriberId(): string {',
    "  return 'user-' + Date.now();",
    '}',
    '',
    'export function NovuInboxWrapper() {',
    '  const [isLoaded, setIsLoaded] = useState(false);',
    '  const [subscriberId, setSubscriberId] = useState<string | null>(null);',
    '',
    '  useEffect(() => {',
    '    // Validate environment variable',
    '    if (!process.env.NEXT_PUBLIC_NOVU_APP_IDENTIFIER) {',
    "      console.error('NEXT_PUBLIC_NOVU_APP_IDENTIFIER is not set');",
    '      return;',
    '    }',
    '    ',
    '    // Generate subscriber ID on client side only',
    '    setSubscriberId(getTemporarySubscriberId());',
    '    setIsLoaded(true);',
    '  }, []);',
    '',
    '  if (!isLoaded) {',
    '    return <div className="w-6 h-6 border-2 border-gray-300 border-t-transparent rounded-full animate-spin"></div>;',
    '  }',
    '',
    '  if (!subscriberId) {',
    '    return <div className="w-6 h-6 border-2 border-gray-300 border-t-transparent rounded-full animate-spin"></div>;',
    '  }',
    '',
    '  return (',
    '    <Inbox ',
    '      applicationIdentifier={process.env.NEXT_PUBLIC_NOVU_APP_IDENTIFIER}',
    '      subscriberId={subscriberId}',
    '    />',
    '  );',
    '}',
    '```',
    '',
    '#### **6.2.2 – Layout Integration**',
    'In `src/app/layout.tsx`:',
    '',
    '```tsx',
    "import { NovuInboxWrapper } from '@/components/NovuInboxWrapper';",
    '',
    'export default function RootLayout({ children }: { children: React.ReactNode }) {',
    '  return (',
    '    <html lang="en">',
    '      <body>',
    '        <nav>',
    '          <NovuInboxWrapper />',
    '        </nav>',
    '        {children}',
    '      </body>',
    '    </html>',
    '  );',
    '}',
    '```',
    '',
    '### **6.3 – TROUBLESHOOTING STEPS FOR COMMON ERRORS**',
    '',
    '#### **6.3.1 – Hydration Errors**',
    '- Caused by server/client rendering mismatches',
    '- Solution: Use client-side only components with proper loading states',
    '',
    '#### **6.3.2 – Import Resolution Errors**',
    '- Caused by Next.js cache issues',
    '- Solution: Run `rm -rf .next && npm run dev`',
    '',
    '#### **6.3.3 – Configuration Errors**',
    '- Caused by missing environment variables',
    '- Solution: Validate configuration in client-side wrapper component',
    '',
    '### **6.4 – CACHE CLEARING INSTRUCTIONS**',
    '',
    'If you encounter import resolution errors:',
    '```bash',
    '# Clear Next.js cache and restart',
    'rm -rf .next',
    'npm run dev',
    '```',
  ];
}
