/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { activityTrack } from "../funcs/activityTrack.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type ActivityTrackMutationVariables = {
  request: operations.InboundWebhooksControllerHandleWebhookRequest;
  options?: RequestOptions;
};

export type ActivityTrackMutationData = Array<components.WebhookResultDto>;

/**
 * Track activity and engagement events
 *
 * @remarks
 * Track activity and engagement events for a specific delivery provider
 */
export function useActivityTrackMutation(
  options?: MutationHookOptions<
    ActivityTrackMutationData,
    Error,
    ActivityTrackMutationVariables
  >,
): UseMutationResult<
  ActivityTrackMutationData,
  Error,
  ActivityTrackMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildActivityTrackMutation(client, options),
    ...options,
  });
}

export function mutationKeyActivityTrack(): MutationKey {
  return ["@novu/api", "Activity", "track"];
}

export function buildActivityTrackMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: ActivityTrackMutationVariables,
  ) => Promise<ActivityTrackMutationData>;
} {
  return {
    mutationKey: mutationKeyActivityTrack(),
    mutationFn: function activityTrackMutationFn({
      request,
      options,
    }): Promise<ActivityTrackMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(activityTrack(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
