import { Module, Provider } from '@nestjs/common';

import {
  analyticsService,
  bullMqTokenList,
  cacheService,
  distributedLockService,
} from '../custom-providers';
import {
  ActiveJobsMetricQueueServiceHealthIndicator,
  CompletedJobsMetricQueueServiceHealthIndicator,
  InboundParseQueueServiceHealthIndicator,
  StandardQueueServiceHealthIndicator,
  WebSocketsQueueServiceHealthIndicator,
  WorkflowQueueServiceHealthIndicator,
} from '../health';
import {
  CalculateDelayService,
  DistributedLockService,
  EventsDistributedLockService,
  InvalidateCacheService,
  OldInstanceBullMqService,
  ReadinessService,
} from '../services';
import {
  ActiveJobsMetricQueueService,
  CompletedJobsMetricQueueService,
  InboundParseQueue,
  StandardQueueService,
  WebSocketsQueueService,
  WorkflowQueueService,
} from '../services/queues';
import {
  ActiveJobsMetricWorkerService,
  CompletedJobsMetricWorkerService,
  InboundParseWorker,
  StandardWorkerService,
  WebSocketsWorkerService,
  WorkflowWorkerService,
  OldInstanceWorkflowWorkerService,
} from '../services/workers';
import {
  AddDelayJob,
  AddDigestJob,
  AddJob,
  BulkCreateExecutionDetails,
  CreateExecutionDetails,
  CreateNotificationJobs,
  CreateSubscriber,
  CreateTenant,
  DigestFilterSteps,
  DigestFilterStepsBackoff,
  DigestFilterStepsRegular,
  DigestFilterStepsTimed,
  GetTenant,
  ProcessSubscriber,
  ProcessTenant,
  StoreSubscriberJobs,
  SubscriberJobBoundUsecase,
  UpdateSubscriber,
  UpdateTenant,
} from '../usecases';
import {
  JobRepository,
  ExecutionDetailsRepository,
  NotificationRepository,
  SubscriberRepository,
  IntegrationRepository,
  NotificationTemplateRepository,
  TenantRepository,
} from '@novu/dal';
import { SubscriberProcessQueueService } from '../services/queues/subscriber-process-queue.service';
import { SubscriberProcessWorkerService } from '../services/workers/subscriber-process-worker.service';

const PROVIDERS: Provider[] = [
  ActiveJobsMetricQueueService,
  ActiveJobsMetricQueueServiceHealthIndicator,
  ActiveJobsMetricWorkerService,
  bullMqTokenList,
  CompletedJobsMetricQueueService,
  CompletedJobsMetricQueueServiceHealthIndicator,
  CompletedJobsMetricWorkerService,
  InboundParseQueue,
  InboundParseWorker,
  InboundParseQueueServiceHealthIndicator,
  ReadinessService,
  StandardQueueService,
  StandardQueueServiceHealthIndicator,
  StandardWorkerService,
  WebSocketsQueueService,
  WebSocketsQueueServiceHealthIndicator,
  WebSocketsWorkerService,
  WorkflowQueueService,
  WorkflowQueueServiceHealthIndicator,
  WorkflowWorkerService,
  OldInstanceWorkflowWorkerService,
  OldInstanceBullMqService,
  CreateTenant,
  GetTenant,
  TenantRepository,
  UpdateTenant,
  ProcessTenant,
  NotificationTemplateRepository,
  IntegrationRepository,
  UpdateSubscriber,
  SubscriberRepository,
  InvalidateCacheService,
  CreateSubscriber,
  ProcessSubscriber,
  DigestFilterStepsTimed,
  DigestFilterStepsRegular,
  NotificationRepository,
  DigestFilterStepsBackoff,
  DigestFilterSteps,
  CreateNotificationJobs,
  BulkCreateExecutionDetails,
  AddDelayJob,
  CalculateDelayService,
  DistributedLockService,
  EventsDistributedLockService,
  AddDigestJob,
  ExecutionDetailsRepository,
  CreateExecutionDetails,
  JobRepository,
  AddJob,
  StoreSubscriberJobs,
  SubscriberJobBoundUsecase,
  SubscriberProcessQueueService,
  SubscriberProcessWorkerService,
  analyticsService,
  cacheService,
  distributedLockService,
];

@Module({
  providers: [...PROVIDERS],
  exports: [...PROVIDERS],
})
export class QueuesModule {}
