/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of the actor, indicating the role in the notification process.
 */
export const ActorTypeEnum = {
  None: "none",
  User: "user",
  SystemIcon: "system_icon",
  SystemCustom: "system_custom",
} as const;
/**
 * The type of the actor, indicating the role in the notification process.
 */
export type ActorTypeEnum = ClosedEnum<typeof ActorTypeEnum>;

/** @internal */
export const ActorTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof ActorTypeEnum
> = z.nativeEnum(ActorTypeEnum);
