/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChannelTypeEnum,
  ChannelTypeEnum$inboundSchema,
  ChannelTypeEnum$outboundSchema,
} from "./channeltypeenum.js";

export type ChannelPreference = {
  /**
   * Channel type through which the message is sent
   */
  type: ChannelTypeEnum;
  /**
   * If channel is enabled or not
   */
  enabled: boolean;
};

/** @internal */
export const ChannelPreference$inboundSchema: z.ZodType<
  ChannelPreference,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: ChannelTypeEnum$inboundSchema,
  enabled: z.boolean(),
});

/** @internal */
export type ChannelPreference$Outbound = {
  type: string;
  enabled: boolean;
};

/** @internal */
export const ChannelPreference$outboundSchema: z.ZodType<
  ChannelPreference$Outbound,
  z.ZodTypeDef,
  ChannelPreference
> = z.object({
  type: ChannelTypeEnum$outboundSchema,
  enabled: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChannelPreference$ {
  /** @deprecated use `ChannelPreference$inboundSchema` instead. */
  export const inboundSchema = ChannelPreference$inboundSchema;
  /** @deprecated use `ChannelPreference$outboundSchema` instead. */
  export const outboundSchema = ChannelPreference$outboundSchema;
  /** @deprecated use `ChannelPreference$Outbound` instead. */
  export type Outbound = ChannelPreference$Outbound;
}

export function channelPreferenceToJSON(
  channelPreference: ChannelPreference,
): string {
  return JSON.stringify(
    ChannelPreference$outboundSchema.parse(channelPreference),
  );
}

export function channelPreferenceFromJSON(
  jsonString: string,
): SafeParseResult<ChannelPreference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChannelPreference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChannelPreference' from JSON`,
  );
}
