/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChatControlsMetadataResponseDto,
  ChatControlsMetadataResponseDto$inboundSchema,
} from "./chatcontrolsmetadataresponsedto.js";
import {
  ResourceOriginEnum,
  ResourceOriginEnum$inboundSchema,
} from "./resourceoriginenum.js";
import { StepIssuesDto, StepIssuesDto$inboundSchema } from "./stepissuesdto.js";
import { StepTypeEnum, StepTypeEnum$inboundSchema } from "./steptypeenum.js";

/**
 * Control values for the chat step
 */
export type ChatStepResponseDtoControlValues = {
  /**
   * JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
   */
  skip?: { [k: string]: any } | undefined;
  /**
   * Content of the chat message.
   */
  body?: string | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

export type ChatStepResponseDto = {
  /**
   * Controls metadata for the chat step
   */
  controls: ChatControlsMetadataResponseDto;
  /**
   * Control values for the chat step
   */
  controlValues?: ChatStepResponseDtoControlValues | undefined;
  /**
   * JSON Schema for variables, follows the JSON Schema standard
   */
  variables: { [k: string]: any };
  /**
   * Unique identifier of the step
   */
  stepId: string;
  /**
   * Database identifier of the step
   */
  id: string;
  /**
   * Name of the step
   */
  name: string;
  /**
   * Slug of the step
   */
  slug: string;
  /**
   * Type of the step
   */
  type: StepTypeEnum;
  /**
   * Origin of the layout
   */
  origin: ResourceOriginEnum;
  /**
   * Workflow identifier
   */
  workflowId: string;
  /**
   * Workflow database identifier
   */
  workflowDatabaseId: string;
  /**
   * Issues associated with the step
   */
  issues?: StepIssuesDto | undefined;
};

/** @internal */
export const ChatStepResponseDtoControlValues$inboundSchema: z.ZodType<
  ChatStepResponseDtoControlValues,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    skip: z.record(z.any()).optional(),
    body: z.string().optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

export function chatStepResponseDtoControlValuesFromJSON(
  jsonString: string,
): SafeParseResult<ChatStepResponseDtoControlValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStepResponseDtoControlValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStepResponseDtoControlValues' from JSON`,
  );
}

/** @internal */
export const ChatStepResponseDto$inboundSchema: z.ZodType<
  ChatStepResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  controls: ChatControlsMetadataResponseDto$inboundSchema,
  controlValues: z.lazy(() => ChatStepResponseDtoControlValues$inboundSchema)
    .optional(),
  variables: z.record(z.any()),
  stepId: z.string(),
  _id: z.string(),
  name: z.string(),
  slug: z.string(),
  type: StepTypeEnum$inboundSchema,
  origin: ResourceOriginEnum$inboundSchema,
  workflowId: z.string(),
  workflowDatabaseId: z.string(),
  issues: StepIssuesDto$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});

export function chatStepResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ChatStepResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatStepResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatStepResponseDto' from JSON`,
  );
}
