/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UiSchema, UiSchema$inboundSchema } from "./uischema.js";

export type ControlsMetadataDto = {
  /**
   * JSON Schema for data
   */
  dataSchema?: { [k: string]: any } | undefined;
  /**
   * UI Schema for rendering
   */
  uiSchema?: UiSchema | undefined;
};

/** @internal */
export const ControlsMetadataDto$inboundSchema: z.ZodType<
  ControlsMetadataDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  dataSchema: z.record(z.any()).optional(),
  uiSchema: UiSchema$inboundSchema.optional(),
});

export function controlsMetadataDtoFromJSON(
  jsonString: string,
): SafeParseResult<ControlsMetadataDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ControlsMetadataDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ControlsMetadataDto' from JSON`,
  );
}
