/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CustomControlsMetadataResponseDto,
  CustomControlsMetadataResponseDto$inboundSchema,
  CustomControlsMetadataResponseDto$Outbound,
  CustomControlsMetadataResponseDto$outboundSchema,
} from "./customcontrolsmetadataresponsedto.js";
import {
  StepIssuesDto,
  StepIssuesDto$inboundSchema,
  StepIssuesDto$Outbound,
  StepIssuesDto$outboundSchema,
} from "./stepissuesdto.js";
import {
  StepTypeEnum,
  StepTypeEnum$inboundSchema,
  StepTypeEnum$outboundSchema,
} from "./steptypeenum.js";
import {
  WorkflowOriginEnum,
  WorkflowOriginEnum$inboundSchema,
  WorkflowOriginEnum$outboundSchema,
} from "./workfloworiginenum.js";

export type CustomStepResponseDto = {
  /**
   * Controls metadata for the custom step
   */
  controls: CustomControlsMetadataResponseDto;
  /**
   * JSON Schema for variables, follows the JSON Schema standard
   */
  variables: { [k: string]: any };
  /**
   * Unique identifier of the step
   */
  stepId: string;
  /**
   * Database identifier of the step
   */
  id: string;
  /**
   * Name of the step
   */
  name: string;
  /**
   * Slug of the step
   */
  slug: string;
  /**
   * Type of the step
   */
  type: StepTypeEnum;
  /**
   * Origin of the workflow
   */
  origin: WorkflowOriginEnum;
  /**
   * Workflow identifier
   */
  workflowId: string;
  /**
   * Workflow database identifier
   */
  workflowDatabaseId: string;
  /**
   * Issues associated with the step
   */
  issues?: StepIssuesDto | undefined;
};

/** @internal */
export const CustomStepResponseDto$inboundSchema: z.ZodType<
  CustomStepResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  controls: CustomControlsMetadataResponseDto$inboundSchema,
  variables: z.record(z.any()),
  stepId: z.string(),
  _id: z.string(),
  name: z.string(),
  slug: z.string(),
  type: StepTypeEnum$inboundSchema,
  origin: WorkflowOriginEnum$inboundSchema,
  workflowId: z.string(),
  workflowDatabaseId: z.string(),
  issues: StepIssuesDto$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});

/** @internal */
export type CustomStepResponseDto$Outbound = {
  controls: CustomControlsMetadataResponseDto$Outbound;
  variables: { [k: string]: any };
  stepId: string;
  _id: string;
  name: string;
  slug: string;
  type: string;
  origin: string;
  workflowId: string;
  workflowDatabaseId: string;
  issues?: StepIssuesDto$Outbound | undefined;
};

/** @internal */
export const CustomStepResponseDto$outboundSchema: z.ZodType<
  CustomStepResponseDto$Outbound,
  z.ZodTypeDef,
  CustomStepResponseDto
> = z.object({
  controls: CustomControlsMetadataResponseDto$outboundSchema,
  variables: z.record(z.any()),
  stepId: z.string(),
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  type: StepTypeEnum$outboundSchema,
  origin: WorkflowOriginEnum$outboundSchema,
  workflowId: z.string(),
  workflowDatabaseId: z.string(),
  issues: StepIssuesDto$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CustomStepResponseDto$ {
  /** @deprecated use `CustomStepResponseDto$inboundSchema` instead. */
  export const inboundSchema = CustomStepResponseDto$inboundSchema;
  /** @deprecated use `CustomStepResponseDto$outboundSchema` instead. */
  export const outboundSchema = CustomStepResponseDto$outboundSchema;
  /** @deprecated use `CustomStepResponseDto$Outbound` instead. */
  export type Outbound = CustomStepResponseDto$Outbound;
}

export function customStepResponseDtoToJSON(
  customStepResponseDto: CustomStepResponseDto,
): string {
  return JSON.stringify(
    CustomStepResponseDto$outboundSchema.parse(customStepResponseDto),
  );
}

export function customStepResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<CustomStepResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomStepResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomStepResponseDto' from JSON`,
  );
}
