/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v3';
import * as openEnums from '../../types/enums.js';
import { OpenEnum } from '../../types/enums.js';

/**
 * The Digest Type
 */
export const DigestTypeEnum = {
  Regular: 'regular',
  Backoff: 'backoff',
  Timed: 'timed',
} as const;
/**
 * The Digest Type
 */
export type DigestTypeEnum = OpenEnum<typeof DigestTypeEnum>;

/** @internal */
export const DigestTypeEnum$inboundSchema: z.ZodType<DigestTypeEnum, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(DigestTypeEnum);
