/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DuplicateWorkflowDto = {
  /**
   * Name of the workflow
   */
  name?: string | undefined;
  /**
   * Custom workflow identifier for the duplicated workflow
   */
  workflowId?: string | undefined;
  /**
   * Tags associated with the workflow
   */
  tags?: Array<string> | undefined;
  /**
   * Description of the workflow
   */
  description?: string | undefined;
  /**
   * Enable or disable translations for this workflow
   */
  isTranslationEnabled?: boolean | undefined;
};

/** @internal */
export type DuplicateWorkflowDto$Outbound = {
  name?: string | undefined;
  workflowId?: string | undefined;
  tags?: Array<string> | undefined;
  description?: string | undefined;
  isTranslationEnabled: boolean;
};

/** @internal */
export const DuplicateWorkflowDto$outboundSchema: z.ZodType<
  DuplicateWorkflowDto$Outbound,
  z.ZodTypeDef,
  DuplicateWorkflowDto
> = z.object({
  name: z.string().optional(),
  workflowId: z.string().optional(),
  tags: z.array(z.string()).optional(),
  description: z.string().optional(),
  isTranslationEnabled: z.boolean().default(false),
});

export function duplicateWorkflowDtoToJSON(
  duplicateWorkflowDto: DuplicateWorkflowDto,
): string {
  return JSON.stringify(
    DuplicateWorkflowDto$outboundSchema.parse(duplicateWorkflowDto),
  );
}
