/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EmailLayoutRenderOutput = {
  /**
   * Content of the email
   */
  body: string;
};

/** @internal */
export const EmailLayoutRenderOutput$inboundSchema: z.ZodType<
  EmailLayoutRenderOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string(),
});

export function emailLayoutRenderOutputFromJSON(
  jsonString: string,
): SafeParseResult<EmailLayoutRenderOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailLayoutRenderOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailLayoutRenderOutput' from JSON`,
  );
}
