/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EmailControlDto = {
  /**
   * JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
   */
  skip?: { [k: string]: any } | undefined;
  /**
   * Subject of the email.
   */
  subject: string;
  /**
   * Body content of the email, either a valid Maily JSON object, or html string.
   */
  body?: string | undefined;
  /**
   * Disable sanitization of the output.
   */
  disableOutputSanitization?: boolean | undefined;
};

/** @internal */
export const EmailControlDto$inboundSchema: z.ZodType<
  EmailControlDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.record(z.any()).optional(),
  subject: z.string(),
  body: z.string().default(""),
  disableOutputSanitization: z.boolean().default(false),
});

/** @internal */
export type EmailControlDto$Outbound = {
  skip?: { [k: string]: any } | undefined;
  subject: string;
  body: string;
  disableOutputSanitization: boolean;
};

/** @internal */
export const EmailControlDto$outboundSchema: z.ZodType<
  EmailControlDto$Outbound,
  z.ZodTypeDef,
  EmailControlDto
> = z.object({
  skip: z.record(z.any()).optional(),
  subject: z.string(),
  body: z.string().default(""),
  disableOutputSanitization: z.boolean().default(false),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EmailControlDto$ {
  /** @deprecated use `EmailControlDto$inboundSchema` instead. */
  export const inboundSchema = EmailControlDto$inboundSchema;
  /** @deprecated use `EmailControlDto$outboundSchema` instead. */
  export const outboundSchema = EmailControlDto$outboundSchema;
  /** @deprecated use `EmailControlDto$Outbound` instead. */
  export type Outbound = EmailControlDto$Outbound;
}

export function emailControlDtoToJSON(
  emailControlDto: EmailControlDto,
): string {
  return JSON.stringify(EmailControlDto$outboundSchema.parse(emailControlDto));
}

export function emailControlDtoFromJSON(
  jsonString: string,
): SafeParseResult<EmailControlDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailControlDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailControlDto' from JSON`,
  );
}
