/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvironmentVariableValueResponseDto = {
  environmentId: string;
  /**
   * Value is masked (••••••••) for secret variables
   */
  value: string;
};

/** @internal */
export const EnvironmentVariableValueResponseDto$inboundSchema: z.ZodType<
  EnvironmentVariableValueResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  _environmentId: z.string(),
  value: z.string(),
}).transform((v) => {
  return remap$(v, {
    "_environmentId": "environmentId",
  });
});

export function environmentVariableValueResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentVariableValueResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentVariableValueResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentVariableValueResponseDto' from JSON`,
  );
}
