/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SubscriberGlobalPreferenceDto,
  SubscriberGlobalPreferenceDto$inboundSchema,
} from "./subscriberglobalpreferencedto.js";
import {
  SubscriberWorkflowPreferenceDto,
  SubscriberWorkflowPreferenceDto$inboundSchema,
} from "./subscriberworkflowpreferencedto.js";

export type GetSubscriberPreferencesDto = {
  /**
   * Global preference settings
   */
  global: SubscriberGlobalPreferenceDto;
  /**
   * Workflow-specific preference settings
   */
  workflows: Array<SubscriberWorkflowPreferenceDto>;
};

/** @internal */
export const GetSubscriberPreferencesDto$inboundSchema: z.ZodType<
  GetSubscriberPreferencesDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  global: SubscriberGlobalPreferenceDto$inboundSchema,
  workflows: z.array(SubscriberWorkflowPreferenceDto$inboundSchema),
});

export function getSubscriberPreferencesDtoFromJSON(
  jsonString: string,
): SafeParseResult<GetSubscriberPreferencesDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSubscriberPreferencesDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSubscriberPreferencesDto' from JSON`,
  );
}
