/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InBoundParseDomainDto = {
  inboundParseDomain?: string | undefined;
};

/** @internal */
export const InBoundParseDomainDto$inboundSchema: z.ZodType<
  InBoundParseDomainDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  inboundParseDomain: z.string().optional(),
});

/** @internal */
export type InBoundParseDomainDto$Outbound = {
  inboundParseDomain?: string | undefined;
};

/** @internal */
export const InBoundParseDomainDto$outboundSchema: z.ZodType<
  InBoundParseDomainDto$Outbound,
  z.ZodTypeDef,
  InBoundParseDomainDto
> = z.object({
  inboundParseDomain: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InBoundParseDomainDto$ {
  /** @deprecated use `InBoundParseDomainDto$inboundSchema` instead. */
  export const inboundSchema = InBoundParseDomainDto$inboundSchema;
  /** @deprecated use `InBoundParseDomainDto$outboundSchema` instead. */
  export const outboundSchema = InBoundParseDomainDto$outboundSchema;
  /** @deprecated use `InBoundParseDomainDto$Outbound` instead. */
  export type Outbound = InBoundParseDomainDto$Outbound;
}

export function inBoundParseDomainDtoToJSON(
  inBoundParseDomainDto: InBoundParseDomainDto,
): string {
  return JSON.stringify(
    InBoundParseDomainDto$outboundSchema.parse(inBoundParseDomainDto),
  );
}

export function inBoundParseDomainDtoFromJSON(
  jsonString: string,
): SafeParseResult<InBoundParseDomainDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InBoundParseDomainDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InBoundParseDomainDto' from JSON`,
  );
}
