/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LineUserEndpointDto = {
  /**
   * LINE user ID
   */
  userId: string;
};

/** @internal */
export const LineUserEndpointDto$inboundSchema: z.ZodType<
  LineUserEndpointDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string(),
});
/** @internal */
export type LineUserEndpointDto$Outbound = {
  userId: string;
};

/** @internal */
export const LineUserEndpointDto$outboundSchema: z.ZodType<
  LineUserEndpointDto$Outbound,
  z.ZodTypeDef,
  LineUserEndpointDto
> = z.object({
  userId: z.string(),
});

export function lineUserEndpointDtoToJSON(
  lineUserEndpointDto: LineUserEndpointDto,
): string {
  return JSON.stringify(
    LineUserEndpointDto$outboundSchema.parse(lineUserEndpointDto),
  );
}
export function lineUserEndpointDtoFromJSON(
  jsonString: string,
): SafeParseResult<LineUserEndpointDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineUserEndpointDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineUserEndpointDto' from JSON`,
  );
}
