/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LayoutResponseDto,
  LayoutResponseDto$inboundSchema,
} from "./layoutresponsedto.js";

export type ListLayoutResponseDto = {
  /**
   * List of layouts
   */
  layouts: Array<LayoutResponseDto>;
  /**
   * Total number of layouts
   */
  totalCount: number;
};

/** @internal */
export const ListLayoutResponseDto$inboundSchema: z.ZodType<
  ListLayoutResponseDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  layouts: z.array(LayoutResponseDto$inboundSchema),
  totalCount: z.number(),
});

export function listLayoutResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ListLayoutResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListLayoutResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListLayoutResponseDto' from JSON`,
  );
}
