/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MessageActionResult,
  MessageActionResult$inboundSchema,
} from "./messageactionresult.js";
import {
  MessageActionStatusEnum,
  MessageActionStatusEnum$inboundSchema,
} from "./messageactionstatusenum.js";
import { MessageButton, MessageButton$inboundSchema } from "./messagebutton.js";

export type MessageAction = {
  /**
   * Status of the message action
   */
  status?: MessageActionStatusEnum | undefined;
  /**
   * List of buttons associated with the message action
   */
  buttons?: Array<MessageButton> | undefined;
  /**
   * Result of the message action
   */
  result?: MessageActionResult | undefined;
};

/** @internal */
export const MessageAction$inboundSchema: z.ZodType<
  MessageAction,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: MessageActionStatusEnum$inboundSchema.optional(),
  buttons: z.array(MessageButton$inboundSchema).optional(),
  result: MessageActionResult$inboundSchema.optional(),
});

export function messageActionFromJSON(
  jsonString: string,
): SafeParseResult<MessageAction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageAction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageAction' from JSON`,
  );
}
