/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const MetadataSetSignalDtoType = {
  Metadata: "metadata",
} as const;
export type MetadataSetSignalDtoType = ClosedEnum<
  typeof MetadataSetSignalDtoType
>;

/**
 * Defaults to `set` when omitted.
 */
export const Action = {
  Set: "set",
} as const;
/**
 * Defaults to `set` when omitted.
 */
export type Action = ClosedEnum<typeof Action>;

/**
 * JSON-serializable value to store.
 */
export type MetadataSetSignalDtoValue = {};

export type MetadataSetSignalDto = {
  type: MetadataSetSignalDtoType;
  /**
   * Defaults to `set` when omitted.
   */
  action?: Action | undefined;
  /**
   * Metadata key (1–128 chars; letters, digits, and `-` `_` `:` separators).
   */
  key: string;
  /**
   * JSON-serializable value to store.
   */
  value: MetadataSetSignalDtoValue;
};

/** @internal */
export const MetadataSetSignalDtoType$outboundSchema: z.ZodNativeEnum<
  typeof MetadataSetSignalDtoType
> = z.nativeEnum(MetadataSetSignalDtoType);

/** @internal */
export const Action$outboundSchema: z.ZodNativeEnum<typeof Action> = z
  .nativeEnum(Action);

/** @internal */
export type MetadataSetSignalDtoValue$Outbound = {};

/** @internal */
export const MetadataSetSignalDtoValue$outboundSchema: z.ZodType<
  MetadataSetSignalDtoValue$Outbound,
  z.ZodTypeDef,
  MetadataSetSignalDtoValue
> = z.object({});

export function metadataSetSignalDtoValueToJSON(
  metadataSetSignalDtoValue: MetadataSetSignalDtoValue,
): string {
  return JSON.stringify(
    MetadataSetSignalDtoValue$outboundSchema.parse(metadataSetSignalDtoValue),
  );
}

/** @internal */
export type MetadataSetSignalDto$Outbound = {
  type: string;
  action: string;
  key: string;
  value: MetadataSetSignalDtoValue$Outbound;
};

/** @internal */
export const MetadataSetSignalDto$outboundSchema: z.ZodType<
  MetadataSetSignalDto$Outbound,
  z.ZodTypeDef,
  MetadataSetSignalDto
> = z.object({
  type: MetadataSetSignalDtoType$outboundSchema,
  action: Action$outboundSchema.default("set"),
  key: z.string(),
  value: z.lazy(() => MetadataSetSignalDtoValue$outboundSchema),
});

export function metadataSetSignalDtoToJSON(
  metadataSetSignalDto: MetadataSetSignalDto,
): string {
  return JSON.stringify(
    MetadataSetSignalDto$outboundSchema.parse(metadataSetSignalDto),
  );
}
