/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const MetadataClearSignalDtoType = {
  Metadata: "metadata",
} as const;
export type MetadataClearSignalDtoType = ClosedEnum<
  typeof MetadataClearSignalDtoType
>;

export const MetadataClearSignalDtoAction = {
  Clear: "clear",
} as const;
export type MetadataClearSignalDtoAction = ClosedEnum<
  typeof MetadataClearSignalDtoAction
>;

export type MetadataClearSignalDto = {
  type: MetadataClearSignalDtoType;
  action: MetadataClearSignalDtoAction;
};

/** @internal */
export const MetadataClearSignalDtoType$outboundSchema: z.ZodNativeEnum<
  typeof MetadataClearSignalDtoType
> = z.nativeEnum(MetadataClearSignalDtoType);

/** @internal */
export const MetadataClearSignalDtoAction$outboundSchema: z.ZodNativeEnum<
  typeof MetadataClearSignalDtoAction
> = z.nativeEnum(MetadataClearSignalDtoAction);

/** @internal */
export type MetadataClearSignalDto$Outbound = {
  type: string;
  action: string;
};

/** @internal */
export const MetadataClearSignalDto$outboundSchema: z.ZodType<
  MetadataClearSignalDto$Outbound,
  z.ZodTypeDef,
  MetadataClearSignalDto
> = z.object({
  type: MetadataClearSignalDtoType$outboundSchema,
  action: MetadataClearSignalDtoAction$outboundSchema,
});

export function metadataClearSignalDtoToJSON(
  metadataClearSignalDto: MetadataClearSignalDto,
): string {
  return JSON.stringify(
    MetadataClearSignalDto$outboundSchema.parse(metadataClearSignalDto),
  );
}
