/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of monthly schedule
 */
export const MonthlyTypeEnum = {
  Each: "each",
  On: "on",
} as const;
/**
 * Type of monthly schedule
 */
export type MonthlyTypeEnum = ClosedEnum<typeof MonthlyTypeEnum>;

/** @internal */
export const MonthlyTypeEnum$inboundSchema: z.ZodNativeEnum<
  typeof MonthlyTypeEnum
> = z.nativeEnum(MonthlyTypeEnum);

/** @internal */
export const MonthlyTypeEnum$outboundSchema: z.ZodNativeEnum<
  typeof MonthlyTypeEnum
> = MonthlyTypeEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MonthlyTypeEnum$ {
  /** @deprecated use `MonthlyTypeEnum$inboundSchema` instead. */
  export const inboundSchema = MonthlyTypeEnum$inboundSchema;
  /** @deprecated use `MonthlyTypeEnum$outboundSchema` instead. */
  export const outboundSchema = MonthlyTypeEnum$outboundSchema;
}
