/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SubscriberResponseDtoOptional,
  SubscriberResponseDtoOptional$inboundSchema,
  SubscriberResponseDtoOptional$Outbound,
  SubscriberResponseDtoOptional$outboundSchema,
} from "./subscriberresponsedtooptional.js";

/**
 * Rich context object with id and optional data
 */
export type PreviewPayloadDtoContext2 = {
  id: string;
  /**
   * Optional additional context data
   */
  data?: { [k: string]: any } | undefined;
};

export type PreviewPayloadDtoContext = PreviewPayloadDtoContext2 | string;

export type PreviewPayloadDto = {
  /**
   * Partial subscriber information
   */
  subscriber?: SubscriberResponseDtoOptional | undefined;
  /**
   * Payload data
   */
  payload?: { [k: string]: any } | undefined;
  /**
   * Steps data
   */
  steps?: { [k: string]: any } | undefined;
  context?: { [k: string]: PreviewPayloadDtoContext2 | string } | undefined;
  /**
   * Environment variables data
   */
  env?: { [k: string]: any } | undefined;
};

/** @internal */
export const PreviewPayloadDtoContext2$inboundSchema: z.ZodType<
  PreviewPayloadDtoContext2,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  data: z.record(z.any()).optional(),
});
/** @internal */
export type PreviewPayloadDtoContext2$Outbound = {
  id: string;
  data?: { [k: string]: any } | undefined;
};

/** @internal */
export const PreviewPayloadDtoContext2$outboundSchema: z.ZodType<
  PreviewPayloadDtoContext2$Outbound,
  z.ZodTypeDef,
  PreviewPayloadDtoContext2
> = z.object({
  id: z.string(),
  data: z.record(z.any()).optional(),
});

export function previewPayloadDtoContext2ToJSON(
  previewPayloadDtoContext2: PreviewPayloadDtoContext2,
): string {
  return JSON.stringify(
    PreviewPayloadDtoContext2$outboundSchema.parse(previewPayloadDtoContext2),
  );
}
export function previewPayloadDtoContext2FromJSON(
  jsonString: string,
): SafeParseResult<PreviewPayloadDtoContext2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewPayloadDtoContext2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewPayloadDtoContext2' from JSON`,
  );
}

/** @internal */
export const PreviewPayloadDtoContext$inboundSchema: z.ZodType<
  PreviewPayloadDtoContext,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => PreviewPayloadDtoContext2$inboundSchema),
  z.string(),
]);
/** @internal */
export type PreviewPayloadDtoContext$Outbound =
  | PreviewPayloadDtoContext2$Outbound
  | string;

/** @internal */
export const PreviewPayloadDtoContext$outboundSchema: z.ZodType<
  PreviewPayloadDtoContext$Outbound,
  z.ZodTypeDef,
  PreviewPayloadDtoContext
> = z.union([
  z.lazy(() => PreviewPayloadDtoContext2$outboundSchema),
  z.string(),
]);

export function previewPayloadDtoContextToJSON(
  previewPayloadDtoContext: PreviewPayloadDtoContext,
): string {
  return JSON.stringify(
    PreviewPayloadDtoContext$outboundSchema.parse(previewPayloadDtoContext),
  );
}
export function previewPayloadDtoContextFromJSON(
  jsonString: string,
): SafeParseResult<PreviewPayloadDtoContext, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewPayloadDtoContext$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewPayloadDtoContext' from JSON`,
  );
}

/** @internal */
export const PreviewPayloadDto$inboundSchema: z.ZodType<
  PreviewPayloadDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  subscriber: SubscriberResponseDtoOptional$inboundSchema.optional(),
  payload: z.record(z.any()).optional(),
  steps: z.record(z.any()).optional(),
  context: z.record(
    z.union([
      z.lazy(() => PreviewPayloadDtoContext2$inboundSchema),
      z.string(),
    ]),
  ).optional(),
  env: z.record(z.any()).optional(),
});
/** @internal */
export type PreviewPayloadDto$Outbound = {
  subscriber?: SubscriberResponseDtoOptional$Outbound | undefined;
  payload?: { [k: string]: any } | undefined;
  steps?: { [k: string]: any } | undefined;
  context?:
    | { [k: string]: PreviewPayloadDtoContext2$Outbound | string }
    | undefined;
  env?: { [k: string]: any } | undefined;
};

/** @internal */
export const PreviewPayloadDto$outboundSchema: z.ZodType<
  PreviewPayloadDto$Outbound,
  z.ZodTypeDef,
  PreviewPayloadDto
> = z.object({
  subscriber: SubscriberResponseDtoOptional$outboundSchema.optional(),
  payload: z.record(z.any()).optional(),
  steps: z.record(z.any()).optional(),
  context: z.record(
    z.union([
      z.lazy(() => PreviewPayloadDtoContext2$outboundSchema),
      z.string(),
    ]),
  ).optional(),
  env: z.record(z.any()).optional(),
});

export function previewPayloadDtoToJSON(
  previewPayloadDto: PreviewPayloadDto,
): string {
  return JSON.stringify(
    PreviewPayloadDto$outboundSchema.parse(previewPayloadDto),
  );
}
export function previewPayloadDtoFromJSON(
  jsonString: string,
): SafeParseResult<PreviewPayloadDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PreviewPayloadDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PreviewPayloadDto' from JSON`,
  );
}
