/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type of the step
 */
export const PushStepUpsertDtoType = {
  Push: "push",
} as const;
/**
 * Type of the step
 */
export type PushStepUpsertDtoType = ClosedEnum<typeof PushStepUpsertDtoType>;

/**
 * Filter conditions for skipping the step.
 */
export type PushStepUpsertDtoSkip = {};

/**
 * Control values for the Push step
 */
export type PushStepUpsertDtoControlValues = {
  /**
   * Filter conditions for skipping the step.
   */
  skip?: PushStepUpsertDtoSkip | undefined;
  /**
   * Subject/title of the push notification.
   */
  subject: string;
  /**
   * Body content of the push notification.
   */
  body: string;
};

export type PushStepUpsertDto = {
  /**
   * Unique identifier of the step
   */
  id?: string | undefined;
  /**
   * Name of the step
   */
  name: string;
  /**
   * Type of the step
   */
  type?: PushStepUpsertDtoType | undefined;
  /**
   * Control values for the Push step
   */
  controlValues?: PushStepUpsertDtoControlValues | null | undefined;
};

/** @internal */
export const PushStepUpsertDtoType$inboundSchema: z.ZodNativeEnum<
  typeof PushStepUpsertDtoType
> = z.nativeEnum(PushStepUpsertDtoType);

/** @internal */
export const PushStepUpsertDtoType$outboundSchema: z.ZodNativeEnum<
  typeof PushStepUpsertDtoType
> = PushStepUpsertDtoType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PushStepUpsertDtoType$ {
  /** @deprecated use `PushStepUpsertDtoType$inboundSchema` instead. */
  export const inboundSchema = PushStepUpsertDtoType$inboundSchema;
  /** @deprecated use `PushStepUpsertDtoType$outboundSchema` instead. */
  export const outboundSchema = PushStepUpsertDtoType$outboundSchema;
}

/** @internal */
export const PushStepUpsertDtoSkip$inboundSchema: z.ZodType<
  PushStepUpsertDtoSkip,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PushStepUpsertDtoSkip$Outbound = {};

/** @internal */
export const PushStepUpsertDtoSkip$outboundSchema: z.ZodType<
  PushStepUpsertDtoSkip$Outbound,
  z.ZodTypeDef,
  PushStepUpsertDtoSkip
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PushStepUpsertDtoSkip$ {
  /** @deprecated use `PushStepUpsertDtoSkip$inboundSchema` instead. */
  export const inboundSchema = PushStepUpsertDtoSkip$inboundSchema;
  /** @deprecated use `PushStepUpsertDtoSkip$outboundSchema` instead. */
  export const outboundSchema = PushStepUpsertDtoSkip$outboundSchema;
  /** @deprecated use `PushStepUpsertDtoSkip$Outbound` instead. */
  export type Outbound = PushStepUpsertDtoSkip$Outbound;
}

export function pushStepUpsertDtoSkipToJSON(
  pushStepUpsertDtoSkip: PushStepUpsertDtoSkip,
): string {
  return JSON.stringify(
    PushStepUpsertDtoSkip$outboundSchema.parse(pushStepUpsertDtoSkip),
  );
}

export function pushStepUpsertDtoSkipFromJSON(
  jsonString: string,
): SafeParseResult<PushStepUpsertDtoSkip, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PushStepUpsertDtoSkip$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PushStepUpsertDtoSkip' from JSON`,
  );
}

/** @internal */
export const PushStepUpsertDtoControlValues$inboundSchema: z.ZodType<
  PushStepUpsertDtoControlValues,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.lazy(() => PushStepUpsertDtoSkip$inboundSchema).optional(),
  subject: z.string(),
  body: z.string(),
});

/** @internal */
export type PushStepUpsertDtoControlValues$Outbound = {
  skip?: PushStepUpsertDtoSkip$Outbound | undefined;
  subject: string;
  body: string;
};

/** @internal */
export const PushStepUpsertDtoControlValues$outboundSchema: z.ZodType<
  PushStepUpsertDtoControlValues$Outbound,
  z.ZodTypeDef,
  PushStepUpsertDtoControlValues
> = z.object({
  skip: z.lazy(() => PushStepUpsertDtoSkip$outboundSchema).optional(),
  subject: z.string(),
  body: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PushStepUpsertDtoControlValues$ {
  /** @deprecated use `PushStepUpsertDtoControlValues$inboundSchema` instead. */
  export const inboundSchema = PushStepUpsertDtoControlValues$inboundSchema;
  /** @deprecated use `PushStepUpsertDtoControlValues$outboundSchema` instead. */
  export const outboundSchema = PushStepUpsertDtoControlValues$outboundSchema;
  /** @deprecated use `PushStepUpsertDtoControlValues$Outbound` instead. */
  export type Outbound = PushStepUpsertDtoControlValues$Outbound;
}

export function pushStepUpsertDtoControlValuesToJSON(
  pushStepUpsertDtoControlValues: PushStepUpsertDtoControlValues,
): string {
  return JSON.stringify(
    PushStepUpsertDtoControlValues$outboundSchema.parse(
      pushStepUpsertDtoControlValues,
    ),
  );
}

export function pushStepUpsertDtoControlValuesFromJSON(
  jsonString: string,
): SafeParseResult<PushStepUpsertDtoControlValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PushStepUpsertDtoControlValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PushStepUpsertDtoControlValues' from JSON`,
  );
}

/** @internal */
export const PushStepUpsertDto$inboundSchema: z.ZodType<
  PushStepUpsertDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string().optional(),
  name: z.string(),
  type: PushStepUpsertDtoType$inboundSchema.default("push"),
  controlValues: z.nullable(
    z.lazy(() => PushStepUpsertDtoControlValues$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});

/** @internal */
export type PushStepUpsertDto$Outbound = {
  _id?: string | undefined;
  name: string;
  type: string;
  controlValues?: PushStepUpsertDtoControlValues$Outbound | null | undefined;
};

/** @internal */
export const PushStepUpsertDto$outboundSchema: z.ZodType<
  PushStepUpsertDto$Outbound,
  z.ZodTypeDef,
  PushStepUpsertDto
> = z.object({
  id: z.string().optional(),
  name: z.string(),
  type: PushStepUpsertDtoType$outboundSchema.default("push"),
  controlValues: z.nullable(
    z.lazy(() => PushStepUpsertDtoControlValues$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PushStepUpsertDto$ {
  /** @deprecated use `PushStepUpsertDto$inboundSchema` instead. */
  export const inboundSchema = PushStepUpsertDto$inboundSchema;
  /** @deprecated use `PushStepUpsertDto$outboundSchema` instead. */
  export const outboundSchema = PushStepUpsertDto$outboundSchema;
  /** @deprecated use `PushStepUpsertDto$Outbound` instead. */
  export type Outbound = PushStepUpsertDto$Outbound;
}

export function pushStepUpsertDtoToJSON(
  pushStepUpsertDto: PushStepUpsertDto,
): string {
  return JSON.stringify(
    PushStepUpsertDto$outboundSchema.parse(pushStepUpsertDto),
  );
}

export function pushStepUpsertDtoFromJSON(
  jsonString: string,
): SafeParseResult<PushStepUpsertDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PushStepUpsertDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PushStepUpsertDto' from JSON`,
  );
}
