/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RuntimeIssueDto = {};

/** @internal */
export const RuntimeIssueDto$inboundSchema: z.ZodType<
  RuntimeIssueDto,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function runtimeIssueDtoFromJSON(
  jsonString: string,
): SafeParseResult<RuntimeIssueDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RuntimeIssueDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuntimeIssueDto' from JSON`,
  );
}
