/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SignalDtoType = {
  Metadata: "metadata",
  Trigger: "trigger",
} as const;
export type SignalDtoType = ClosedEnum<typeof SignalDtoType>;

export const Action = {
  Set: "set",
  Delete: "delete",
  Clear: "clear",
} as const;
export type Action = ClosedEnum<typeof Action>;

export type SignalDtoValue = {};

export type To = {};

export type SignalDtoPayload = {};

export type SignalDto = {
  type: SignalDtoType;
  action?: Action | undefined;
  key?: string | undefined;
  value?: SignalDtoValue | undefined;
  workflowId?: string | undefined;
  to?: To | undefined;
  payload?: SignalDtoPayload | undefined;
};

/** @internal */
export const SignalDtoType$outboundSchema: z.ZodNativeEnum<
  typeof SignalDtoType
> = z.nativeEnum(SignalDtoType);

/** @internal */
export const Action$outboundSchema: z.ZodNativeEnum<typeof Action> = z
  .nativeEnum(Action);

/** @internal */
export type SignalDtoValue$Outbound = {};

/** @internal */
export const SignalDtoValue$outboundSchema: z.ZodType<
  SignalDtoValue$Outbound,
  z.ZodTypeDef,
  SignalDtoValue
> = z.object({});

export function signalDtoValueToJSON(signalDtoValue: SignalDtoValue): string {
  return JSON.stringify(SignalDtoValue$outboundSchema.parse(signalDtoValue));
}

/** @internal */
export type To$Outbound = {};

/** @internal */
export const To$outboundSchema: z.ZodType<To$Outbound, z.ZodTypeDef, To> = z
  .object({});

export function toToJSON(to: To): string {
  return JSON.stringify(To$outboundSchema.parse(to));
}

/** @internal */
export type SignalDtoPayload$Outbound = {};

/** @internal */
export const SignalDtoPayload$outboundSchema: z.ZodType<
  SignalDtoPayload$Outbound,
  z.ZodTypeDef,
  SignalDtoPayload
> = z.object({});

export function signalDtoPayloadToJSON(
  signalDtoPayload: SignalDtoPayload,
): string {
  return JSON.stringify(
    SignalDtoPayload$outboundSchema.parse(signalDtoPayload),
  );
}

/** @internal */
export type SignalDto$Outbound = {
  type: string;
  action?: string | undefined;
  key?: string | undefined;
  value?: SignalDtoValue$Outbound | undefined;
  workflowId?: string | undefined;
  to?: To$Outbound | undefined;
  payload?: SignalDtoPayload$Outbound | undefined;
};

/** @internal */
export const SignalDto$outboundSchema: z.ZodType<
  SignalDto$Outbound,
  z.ZodTypeDef,
  SignalDto
> = z.object({
  type: SignalDtoType$outboundSchema,
  action: Action$outboundSchema.optional(),
  key: z.string().optional(),
  value: z.lazy(() => SignalDtoValue$outboundSchema).optional(),
  workflowId: z.string().optional(),
  to: z.lazy(() => To$outboundSchema).optional(),
  payload: z.lazy(() => SignalDtoPayload$outboundSchema).optional(),
});

export function signalDtoToJSON(signalDto: SignalDto): string {
  return JSON.stringify(SignalDto$outboundSchema.parse(signalDto));
}
