/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ResourceTypeEnum,
  ResourceTypeEnum$inboundSchema,
} from "./resourcetypeenum.js";

export type SkippedWorkflowDto = {
  /**
   * Type of the layout
   */
  resourceType: ResourceTypeEnum;
  /**
   * Resource ID
   */
  resourceId: string;
  /**
   * Resource name
   */
  resourceName: string;
  /**
   * Reason for skipping
   */
  reason: string;
};

/** @internal */
export const SkippedWorkflowDto$inboundSchema: z.ZodType<
  SkippedWorkflowDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  resourceType: ResourceTypeEnum$inboundSchema,
  resourceId: z.string(),
  resourceName: z.string(),
  reason: z.string(),
});

export function skippedWorkflowDtoFromJSON(
  jsonString: string,
): SafeParseResult<SkippedWorkflowDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SkippedWorkflowDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SkippedWorkflowDto' from JSON`,
  );
}
