/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SlackUserEndpointDto = {
  /**
   * Slack user ID
   */
  userId: string;
};

/** @internal */
export const SlackUserEndpointDto$inboundSchema: z.ZodType<
  SlackUserEndpointDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  userId: z.string(),
});
/** @internal */
export type SlackUserEndpointDto$Outbound = {
  userId: string;
};

/** @internal */
export const SlackUserEndpointDto$outboundSchema: z.ZodType<
  SlackUserEndpointDto$Outbound,
  z.ZodTypeDef,
  SlackUserEndpointDto
> = z.object({
  userId: z.string(),
});

export function slackUserEndpointDtoToJSON(
  slackUserEndpointDto: SlackUserEndpointDto,
): string {
  return JSON.stringify(
    SlackUserEndpointDto$outboundSchema.parse(slackUserEndpointDto),
  );
}
export function slackUserEndpointDtoFromJSON(
  jsonString: string,
): SafeParseResult<SlackUserEndpointDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlackUserEndpointDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlackUserEndpointDto' from JSON`,
  );
}
