/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type of the step
 */
export const SmsStepUpsertDtoType = {
  Sms: "sms",
} as const;
/**
 * Type of the step
 */
export type SmsStepUpsertDtoType = ClosedEnum<typeof SmsStepUpsertDtoType>;

/**
 * Filter conditions for skipping the step.
 */
export type SmsStepUpsertDtoSkip = {};

/**
 * Control values for the SMS step
 */
export type SmsStepUpsertDtoControlValues = {
  /**
   * Filter conditions for skipping the step.
   */
  skip?: SmsStepUpsertDtoSkip | undefined;
  /**
   * Content of the SMS message.
   */
  body: string;
};

export type SmsStepUpsertDto = {
  /**
   * Unique identifier of the step
   */
  id?: string | undefined;
  /**
   * Name of the step
   */
  name: string;
  /**
   * Type of the step
   */
  type?: SmsStepUpsertDtoType | undefined;
  /**
   * Control values for the SMS step
   */
  controlValues?: SmsStepUpsertDtoControlValues | null | undefined;
};

/** @internal */
export const SmsStepUpsertDtoType$inboundSchema: z.ZodNativeEnum<
  typeof SmsStepUpsertDtoType
> = z.nativeEnum(SmsStepUpsertDtoType);

/** @internal */
export const SmsStepUpsertDtoType$outboundSchema: z.ZodNativeEnum<
  typeof SmsStepUpsertDtoType
> = SmsStepUpsertDtoType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SmsStepUpsertDtoType$ {
  /** @deprecated use `SmsStepUpsertDtoType$inboundSchema` instead. */
  export const inboundSchema = SmsStepUpsertDtoType$inboundSchema;
  /** @deprecated use `SmsStepUpsertDtoType$outboundSchema` instead. */
  export const outboundSchema = SmsStepUpsertDtoType$outboundSchema;
}

/** @internal */
export const SmsStepUpsertDtoSkip$inboundSchema: z.ZodType<
  SmsStepUpsertDtoSkip,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type SmsStepUpsertDtoSkip$Outbound = {};

/** @internal */
export const SmsStepUpsertDtoSkip$outboundSchema: z.ZodType<
  SmsStepUpsertDtoSkip$Outbound,
  z.ZodTypeDef,
  SmsStepUpsertDtoSkip
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SmsStepUpsertDtoSkip$ {
  /** @deprecated use `SmsStepUpsertDtoSkip$inboundSchema` instead. */
  export const inboundSchema = SmsStepUpsertDtoSkip$inboundSchema;
  /** @deprecated use `SmsStepUpsertDtoSkip$outboundSchema` instead. */
  export const outboundSchema = SmsStepUpsertDtoSkip$outboundSchema;
  /** @deprecated use `SmsStepUpsertDtoSkip$Outbound` instead. */
  export type Outbound = SmsStepUpsertDtoSkip$Outbound;
}

export function smsStepUpsertDtoSkipToJSON(
  smsStepUpsertDtoSkip: SmsStepUpsertDtoSkip,
): string {
  return JSON.stringify(
    SmsStepUpsertDtoSkip$outboundSchema.parse(smsStepUpsertDtoSkip),
  );
}

export function smsStepUpsertDtoSkipFromJSON(
  jsonString: string,
): SafeParseResult<SmsStepUpsertDtoSkip, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmsStepUpsertDtoSkip$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmsStepUpsertDtoSkip' from JSON`,
  );
}

/** @internal */
export const SmsStepUpsertDtoControlValues$inboundSchema: z.ZodType<
  SmsStepUpsertDtoControlValues,
  z.ZodTypeDef,
  unknown
> = z.object({
  skip: z.lazy(() => SmsStepUpsertDtoSkip$inboundSchema).optional(),
  body: z.string(),
});

/** @internal */
export type SmsStepUpsertDtoControlValues$Outbound = {
  skip?: SmsStepUpsertDtoSkip$Outbound | undefined;
  body: string;
};

/** @internal */
export const SmsStepUpsertDtoControlValues$outboundSchema: z.ZodType<
  SmsStepUpsertDtoControlValues$Outbound,
  z.ZodTypeDef,
  SmsStepUpsertDtoControlValues
> = z.object({
  skip: z.lazy(() => SmsStepUpsertDtoSkip$outboundSchema).optional(),
  body: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SmsStepUpsertDtoControlValues$ {
  /** @deprecated use `SmsStepUpsertDtoControlValues$inboundSchema` instead. */
  export const inboundSchema = SmsStepUpsertDtoControlValues$inboundSchema;
  /** @deprecated use `SmsStepUpsertDtoControlValues$outboundSchema` instead. */
  export const outboundSchema = SmsStepUpsertDtoControlValues$outboundSchema;
  /** @deprecated use `SmsStepUpsertDtoControlValues$Outbound` instead. */
  export type Outbound = SmsStepUpsertDtoControlValues$Outbound;
}

export function smsStepUpsertDtoControlValuesToJSON(
  smsStepUpsertDtoControlValues: SmsStepUpsertDtoControlValues,
): string {
  return JSON.stringify(
    SmsStepUpsertDtoControlValues$outboundSchema.parse(
      smsStepUpsertDtoControlValues,
    ),
  );
}

export function smsStepUpsertDtoControlValuesFromJSON(
  jsonString: string,
): SafeParseResult<SmsStepUpsertDtoControlValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmsStepUpsertDtoControlValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmsStepUpsertDtoControlValues' from JSON`,
  );
}

/** @internal */
export const SmsStepUpsertDto$inboundSchema: z.ZodType<
  SmsStepUpsertDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string().optional(),
  name: z.string(),
  type: SmsStepUpsertDtoType$inboundSchema.default("sms"),
  controlValues: z.nullable(
    z.lazy(() => SmsStepUpsertDtoControlValues$inboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});

/** @internal */
export type SmsStepUpsertDto$Outbound = {
  _id?: string | undefined;
  name: string;
  type: string;
  controlValues?: SmsStepUpsertDtoControlValues$Outbound | null | undefined;
};

/** @internal */
export const SmsStepUpsertDto$outboundSchema: z.ZodType<
  SmsStepUpsertDto$Outbound,
  z.ZodTypeDef,
  SmsStepUpsertDto
> = z.object({
  id: z.string().optional(),
  name: z.string(),
  type: SmsStepUpsertDtoType$outboundSchema.default("sms"),
  controlValues: z.nullable(
    z.lazy(() => SmsStepUpsertDtoControlValues$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SmsStepUpsertDto$ {
  /** @deprecated use `SmsStepUpsertDto$inboundSchema` instead. */
  export const inboundSchema = SmsStepUpsertDto$inboundSchema;
  /** @deprecated use `SmsStepUpsertDto$outboundSchema` instead. */
  export const outboundSchema = SmsStepUpsertDto$outboundSchema;
  /** @deprecated use `SmsStepUpsertDto$Outbound` instead. */
  export type Outbound = SmsStepUpsertDto$Outbound;
}

export function smsStepUpsertDtoToJSON(
  smsStepUpsertDto: SmsStepUpsertDto,
): string {
  return JSON.stringify(
    SmsStepUpsertDto$outboundSchema.parse(smsStepUpsertDto),
  );
}

export function smsStepUpsertDtoFromJSON(
  jsonString: string,
): SafeParseResult<SmsStepUpsertDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SmsStepUpsertDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SmsStepUpsertDto' from JSON`,
  );
}
