/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type StepsOverrides = {
  /**
   * Passing the provider id and the provider specific configurations
   */
  providers?: { [k: string]: { [k: string]: any } } | undefined;
  /**
   * Override the or remove the layout for this specific step
   */
  layoutId?: string | null | undefined;
};

/** @internal */
export type StepsOverrides$Outbound = {
  providers?: { [k: string]: { [k: string]: any } } | undefined;
  layoutId?: string | null | undefined;
};

/** @internal */
export const StepsOverrides$outboundSchema: z.ZodType<
  StepsOverrides$Outbound,
  z.ZodTypeDef,
  StepsOverrides
> = z.object({
  providers: z.record(z.record(z.any())).optional(),
  layoutId: z.nullable(z.string()).optional(),
});

export function stepsOverridesToJSON(stepsOverrides: StepsOverrides): string {
  return JSON.stringify(StepsOverrides$outboundSchema.parse(stepsOverrides));
}
