/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of integration issue
 */
export const StepIntegrationIssueEnum = {
  MissingIntegration: "MISSING_INTEGRATION",
} as const;
/**
 * Type of integration issue
 */
export type StepIntegrationIssueEnum = ClosedEnum<
  typeof StepIntegrationIssueEnum
>;

/** @internal */
export const StepIntegrationIssueEnum$inboundSchema: z.ZodNativeEnum<
  typeof StepIntegrationIssueEnum
> = z.nativeEnum(StepIntegrationIssueEnum);

/** @internal */
export const StepIntegrationIssueEnum$outboundSchema: z.ZodNativeEnum<
  typeof StepIntegrationIssueEnum
> = StepIntegrationIssueEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StepIntegrationIssueEnum$ {
  /** @deprecated use `StepIntegrationIssueEnum$inboundSchema` instead. */
  export const inboundSchema = StepIntegrationIssueEnum$inboundSchema;
  /** @deprecated use `StepIntegrationIssueEnum$outboundSchema` instead. */
  export const outboundSchema = StepIntegrationIssueEnum$outboundSchema;
}
