/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ChannelCredentialsDto,
  ChannelCredentialsDto$inboundSchema,
  ChannelCredentialsDto$Outbound,
  ChannelCredentialsDto$outboundSchema,
} from "./channelcredentialsdto.js";

/**
 * The ID of the chat or push provider.
 */
export const ProviderId = {
  Slack: "slack",
  Discord: "discord",
  Msteams: "msteams",
  Mattermost: "mattermost",
  Ryver: "ryver",
  Zulip: "zulip",
  GrafanaOnCall: "grafana-on-call",
  Getstream: "getstream",
  RocketChat: "rocket-chat",
  WhatsappBusiness: "whatsapp-business",
  ChatWebhook: "chat-webhook",
  NovuSlack: "novu-slack",
  Fcm: "fcm",
  Apns: "apns",
  Expo: "expo",
  OneSignal: "one-signal",
  Pushpad: "pushpad",
  PushWebhook: "push-webhook",
  PusherBeams: "pusher-beams",
} as const;
/**
 * The ID of the chat or push provider.
 */
export type ProviderId = ClosedEnum<typeof ProviderId>;

export type SubscriberChannelDto = {
  /**
   * The ID of the chat or push provider.
   */
  providerId: ProviderId;
  /**
   * An optional identifier for the integration.
   */
  integrationIdentifier?: string | undefined;
  /**
   * Credentials for the channel.
   */
  credentials: ChannelCredentialsDto;
};

/** @internal */
export const ProviderId$inboundSchema: z.ZodNativeEnum<typeof ProviderId> = z
  .nativeEnum(ProviderId);

/** @internal */
export const ProviderId$outboundSchema: z.ZodNativeEnum<typeof ProviderId> =
  ProviderId$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProviderId$ {
  /** @deprecated use `ProviderId$inboundSchema` instead. */
  export const inboundSchema = ProviderId$inboundSchema;
  /** @deprecated use `ProviderId$outboundSchema` instead. */
  export const outboundSchema = ProviderId$outboundSchema;
}

/** @internal */
export const SubscriberChannelDto$inboundSchema: z.ZodType<
  SubscriberChannelDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  providerId: ProviderId$inboundSchema,
  integrationIdentifier: z.string().optional(),
  credentials: ChannelCredentialsDto$inboundSchema,
});

/** @internal */
export type SubscriberChannelDto$Outbound = {
  providerId: string;
  integrationIdentifier?: string | undefined;
  credentials: ChannelCredentialsDto$Outbound;
};

/** @internal */
export const SubscriberChannelDto$outboundSchema: z.ZodType<
  SubscriberChannelDto$Outbound,
  z.ZodTypeDef,
  SubscriberChannelDto
> = z.object({
  providerId: ProviderId$outboundSchema,
  integrationIdentifier: z.string().optional(),
  credentials: ChannelCredentialsDto$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscriberChannelDto$ {
  /** @deprecated use `SubscriberChannelDto$inboundSchema` instead. */
  export const inboundSchema = SubscriberChannelDto$inboundSchema;
  /** @deprecated use `SubscriberChannelDto$outboundSchema` instead. */
  export const outboundSchema = SubscriberChannelDto$outboundSchema;
  /** @deprecated use `SubscriberChannelDto$Outbound` instead. */
  export type Outbound = SubscriberChannelDto$Outbound;
}

export function subscriberChannelDtoToJSON(
  subscriberChannelDto: SubscriberChannelDto,
): string {
  return JSON.stringify(
    SubscriberChannelDto$outboundSchema.parse(subscriberChannelDto),
  );
}

export function subscriberChannelDtoFromJSON(
  jsonString: string,
): SafeParseResult<SubscriberChannelDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubscriberChannelDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubscriberChannelDto' from JSON`,
  );
}
