/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TestDomainRouteFromDto,
  TestDomainRouteFromDto$Outbound,
  TestDomainRouteFromDto$outboundSchema,
} from "./testdomainroutefromdto.js";

export type TestDomainRouteDto = {
  from: TestDomainRouteFromDto;
  subject: string;
  text?: string | undefined;
  html?: string | undefined;
  /**
   * When true, returns the payload that would be delivered without invoking outbound webhooks or the agent HTTP endpoint.
   */
  dryRun?: boolean | undefined;
};

/** @internal */
export type TestDomainRouteDto$Outbound = {
  from: TestDomainRouteFromDto$Outbound;
  subject: string;
  text?: string | undefined;
  html?: string | undefined;
  dryRun?: boolean | undefined;
};

/** @internal */
export const TestDomainRouteDto$outboundSchema: z.ZodType<
  TestDomainRouteDto$Outbound,
  z.ZodTypeDef,
  TestDomainRouteDto
> = z.object({
  from: TestDomainRouteFromDto$outboundSchema,
  subject: z.string(),
  text: z.string().optional(),
  html: z.string().optional(),
  dryRun: z.boolean().optional(),
});

export function testDomainRouteDtoToJSON(
  testDomainRouteDto: TestDomainRouteDto,
): string {
  return JSON.stringify(
    TestDomainRouteDto$outboundSchema.parse(testDomainRouteDto),
  );
}
