/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TriggerRecipientsTypeEnum,
  TriggerRecipientsTypeEnum$outboundSchema,
} from "./triggerrecipientstypeenum.js";

export type TopicPayloadDto = {
  topicKey: string;
  type: TriggerRecipientsTypeEnum;
  /**
   * Optional array of subscriber IDs to exclude from the topic trigger
   */
  exclude?: Array<string> | undefined;
};

/** @internal */
export type TopicPayloadDto$Outbound = {
  topicKey: string;
  type: string;
  exclude?: Array<string> | undefined;
};

/** @internal */
export const TopicPayloadDto$outboundSchema: z.ZodType<
  TopicPayloadDto$Outbound,
  z.ZodTypeDef,
  TopicPayloadDto
> = z.object({
  topicKey: z.string(),
  type: TriggerRecipientsTypeEnum$outboundSchema,
  exclude: z.array(z.string()).optional(),
});

export function topicPayloadDtoToJSON(
  topicPayloadDto: TopicPayloadDto,
): string {
  return JSON.stringify(TopicPayloadDto$outboundSchema.parse(topicPayloadDto));
}
