/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod';
import { ClosedEnum } from '../../types/enums.js';

/**
 * Component type for the UI Schema Property
 */
export const UiComponentEnum = {
  EmailEditorSelect: 'EMAIL_EDITOR_SELECT',
  LayoutSelect: 'LAYOUT_SELECT',
  BlockEditor: 'BLOCK_EDITOR',
  EmailBody: 'EMAIL_BODY',
  TextFullLine: 'TEXT_FULL_LINE',
  TextInlineLabel: 'TEXT_INLINE_LABEL',
  InAppBody: 'IN_APP_BODY',
  InAppAvatar: 'IN_APP_AVATAR',
  InAppPrimarySubject: 'IN_APP_PRIMARY_SUBJECT',
  InAppButtonDropdown: 'IN_APP_BUTTON_DROPDOWN',
  InAppDisableSanitizationSwitch: 'IN_APP_DISABLE_SANITIZATION_SWITCH',
  DisableSanitizationSwitch: 'DISABLE_SANITIZATION_SWITCH',
  UrlTextBox: 'URL_TEXT_BOX',
  DigestAmount: 'DIGEST_AMOUNT',
  DigestUnit: 'DIGEST_UNIT',
  DigestKey: 'DIGEST_KEY',
  DigestCron: 'DIGEST_CRON',
  DelayType: 'DELAY_TYPE',
  DelayAmount: 'DELAY_AMOUNT',
  DelayUnit: 'DELAY_UNIT',
  ExtendToSchedule: 'EXTEND_TO_SCHEDULE',
  SmsBody: 'SMS_BODY',
  ChatBody: 'CHAT_BODY',
  PushBody: 'PUSH_BODY',
  PushSubject: 'PUSH_SUBJECT',
  QueryEditor: 'QUERY_EDITOR',
  Data: 'DATA',
  LayoutEmail: 'LAYOUT_EMAIL',
} as const;
/**
 * Component type for the UI Schema Property
 */
export type UiComponentEnum = ClosedEnum<typeof UiComponentEnum>;

/** @internal */
export const UiComponentEnum$inboundSchema: z.ZodNativeEnum<typeof UiComponentEnum> = z.nativeEnum(UiComponentEnum);

/** @internal */
export const UiComponentEnum$outboundSchema: z.ZodNativeEnum<typeof UiComponentEnum> = UiComponentEnum$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UiComponentEnum$ {
  /** @deprecated use `UiComponentEnum$inboundSchema` instead. */
  export const inboundSchema = UiComponentEnum$inboundSchema;
  /** @deprecated use `UiComponentEnum$outboundSchema` instead. */
  export const outboundSchema = UiComponentEnum$outboundSchema;
}
