/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const WorkflowResponseDtoSortField = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Name: "name",
  LastTriggeredAt: "lastTriggeredAt",
} as const;
export type WorkflowResponseDtoSortField = ClosedEnum<
  typeof WorkflowResponseDtoSortField
>;

/** @internal */
export const WorkflowResponseDtoSortField$outboundSchema: z.ZodNativeEnum<
  typeof WorkflowResponseDtoSortField
> = z.nativeEnum(WorkflowResponseDtoSortField);
