/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from 'zod/v3';
import * as openEnums from '../../types/enums.js';
import { OpenEnum } from '../../types/enums.js';

/**
 * Status of the workflow
 */
export const WorkflowStatusEnum = {
  Active: 'ACTIVE',
  Inactive: 'INACTIVE',
  Error: 'ERROR',
} as const;
/**
 * Status of the workflow
 */
export type WorkflowStatusEnum = OpenEnum<typeof WorkflowStatusEnum>;

/** @internal */
export const WorkflowStatusEnum$inboundSchema: z.ZodType<WorkflowStatusEnum, z.ZodTypeDef, unknown> =
  openEnums.inboundSchema(WorkflowStatusEnum);
/** @internal */
export const WorkflowStatusEnum$outboundSchema: z.ZodType<string, z.ZodTypeDef, WorkflowStatusEnum> =
  openEnums.outboundSchema(WorkflowStatusEnum);
