import { HttpLog } from '../../types/logs';

export const mockLogsData: HttpLog[] = [
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_1234567890abcdef',
    ip: '192.168.1.100',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    queryParams: '{}',
    requestBody: '{"name":"welcome-email","to":{"subscriberId":"user_123"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_1234567890abcdef"}',
    userId: 'user_123',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 245,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_2345678901bcdefg',
    ip: '192.168.1.101',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36',
    queryParams: '{}',
    requestBody: '{"name":"order-confirmation","to":{"subscriberId":"user_456"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_2345678901bcdefg"}',
    userId: 'user_456',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 189,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_3456789012cdefgh',
    ip: '10.0.0.50',
    userAgent: 'curl/7.68.0',
    queryParams: '{}',
    requestBody: '{"name":"password-reset","to":{"subscriberId":"user_789"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_3456789012cdefgh"}',
    userId: 'user_789',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 156,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_4567890123defghi',
    ip: '172.16.0.25',
    userAgent: 'PostmanRuntime/7.29.2',
    queryParams: '{}',
    requestBody: '{"name":"newsletter","to":{"subscriberId":"user_101112"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_4567890123defghi"}',
    userId: 'user_101112',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 203,
  },
  {
    timestamp: '2024-11-05T08:25:09Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 408,
    method: 'POST',
    transactionId: null,
    ip: '192.168.1.200',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
    queryParams: '{}',
    requestBody: '{"name":"timeout-test","to":{"subscriberId":"user_timeout"}}',
    responseBody: '{"error":"Request Timeout","message":"The request took too long to process"}',
    userId: 'user_timeout',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 30000,
  },
  {
    timestamp: '2024-11-05T08:21:30Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 429,
    method: 'POST',
    transactionId: null,
    ip: '203.0.113.42',
    userAgent: 'axios/0.27.2',
    queryParams: '{}',
    requestBody: '{"name":"rate-limit-test","to":{"subscriberId":"user_rate_limit"}}',
    responseBody:
      '{"error":"Too Many Requests","message":"Rate limit exceeded. Please try again later.","retryAfter":60}',
    userId: 'user_rate_limit',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 45,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_5678901234efghij',
    ip: '198.51.100.15',
    userAgent: 'node-fetch/2.6.7',
    queryParams: '{}',
    requestBody: '{"name":"promotion-email","to":{"subscriberId":"user_promo"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_5678901234efghij"}',
    userId: 'user_promo',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 167,
  },
  {
    timestamp: '2024-11-05T08:18:15Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 401,
    method: 'POST',
    transactionId: null,
    ip: '192.168.1.50',
    userAgent: 'insomnia/2023.5.8',
    queryParams: '{}',
    requestBody: '{"name":"unauthorized-test","to":{"subscriberId":"user_unauth"}}',
    responseBody: '{"error":"Unauthorized","message":"Invalid API key provided"}',
    userId: 'user_unauth',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 12,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_6789012345fghijk',
    ip: '10.1.1.100',
    userAgent: 'fetch/1.0',
    queryParams: '{}',
    requestBody: '{"name":"welcome-sms","to":{"subscriberId":"user_sms"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_6789012345fghijk"}',
    userId: 'user_sms',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 234,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_7890123456ghijkl',
    ip: '172.31.0.10',
    userAgent: 'Python/3.9 requests/2.28.1',
    queryParams: '{}',
    requestBody: '{"name":"security-alert","to":{"subscriberId":"user_security"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_7890123456ghijkl"}',
    userId: 'user_security',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 198,
  },
  {
    timestamp: '2024-11-05T08:18:08Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 400,
    method: 'POST',
    transactionId: null,
    ip: '192.168.2.100',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36',
    queryParams: '{}',
    requestBody: '{"name":"","to":{"subscriberId":"user_bad_request"}}',
    responseBody:
      '{"error":"Bad Request","message":"Workflow name is required","details":{"field":"name","code":"REQUIRED"}}',
    userId: 'user_bad_request',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 23,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/subscriber/create',
    url: 'https://api.novu.co/v1/api/subscriber/create',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'GET',
    transactionId: 'tx_8901234567hijklm',
    ip: '203.0.113.100',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15',
    queryParams: '{"subscriberId":"new_user_123"}',
    requestBody: '{}',
    responseBody: '{"subscriberId":"new_user_123","email":"user@example.com","firstName":"John","lastName":"Doe"}',
    userId: 'new_user_123',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'subscriber_fetch',
    durationMs: 87,
  },
  {
    timestamp: '2024-11-05T08:19:30Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 500,
    method: 'POST',
    transactionId: null,
    ip: '192.168.3.50',
    userAgent: 'Ruby/3.0.0',
    queryParams: '{}',
    requestBody: '{"name":"server-error-test","to":{"subscriberId":"user_server_error"}}',
    responseBody:
      '{"error":"Internal Server Error","message":"An unexpected error occurred while processing your request"}',
    userId: 'user_server_error',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 1205,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_9012345678ijklmn',
    ip: '10.0.1.25',
    userAgent: 'Go-http-client/1.1',
    queryParams: '{}',
    requestBody: '{"name":"invoice-reminder","to":{"subscriberId":"user_invoice"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_9012345678ijklmn"}',
    userId: 'user_invoice',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 312,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_0123456789jklmno',
    ip: '172.20.0.5',
    userAgent: 'Java/11.0.16',
    queryParams: '{}',
    requestBody: '{"name":"birthday-wishes","to":{"subscriberId":"user_birthday"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_0123456789jklmno"}',
    userId: 'user_birthday',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 278,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_1234567890klmnop',
    ip: '198.51.100.200',
    userAgent: 'Dart/2.18 (dart:io)',
    queryParams: '{}',
    requestBody: '{"name":"app-update","to":{"subscriberId":"user_app_update"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_1234567890klmnop"}',
    userId: 'user_app_update',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 145,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_2345678901lmnopq',
    ip: '10.10.10.10',
    userAgent: 'okhttp/4.10.0',
    queryParams: '{}',
    requestBody: '{"name":"maintenance-notice","to":{"subscriberId":"user_maintenance"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_2345678901lmnopq"}',
    userId: 'user_maintenance',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 167,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_3456789012mnopqr',
    ip: '192.168.100.1',
    userAgent: 'HTTPie/3.2.0',
    queryParams: '{}',
    requestBody: '{"name":"weekly-digest","to":{"subscriberId":"user_digest"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_3456789012mnopqr"}',
    userId: 'user_digest',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 289,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_4567890123nopqrs',
    ip: '172.16.255.1',
    userAgent: 'Wget/1.21.2',
    queryParams: '{}',
    requestBody: '{"name":"system-alert","to":{"subscriberId":"user_system"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_4567890123nopqrs"}',
    userId: 'user_system',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 198,
  },
  {
    timestamp: '2024-11-05T08:16:49Z',
    path: '/v1/api/trigger',
    url: 'https://api.novu.co/v1/api/trigger',
    hostname: 'api.novu.co',
    statusCode: 200,
    method: 'POST',
    transactionId: 'tx_5678901234opqrst',
    ip: '203.0.113.50',
    userAgent: 'libcurl/7.84.0',
    queryParams: '{}',
    requestBody: '{"name":"flash-sale","to":{"subscriberId":"user_flash_sale"}}',
    responseBody: '{"acknowledged":true,"status":"processed","transactionId":"tx_5678901234opqrst"}',
    userId: 'user_flash_sale',
    organizationId: 'org_456',
    environmentId: 'env_789',
    schemaType: 'trigger_event',
    durationMs: 134,
  },
];

// Helper function to get total count for pagination
export const getTotalLogsCount = () => 2413;
