export enum ProductFeatureKeyEnum {
  TRANSLATIONS = 'TRANSLATIONS',
  MANAGE_ENVIRONMENTS = 'MANAGE_ENVIRONMENTS',
  WEBHOOKS = 'WEBHOOKS',
  AGENT_EMAIL_INTEGRATION = 'AGENT_EMAIL_INTEGRATION',
  CUSTOM_DOMAINS = 'CUSTOM_DOMAINS',
}
