/**
 * The required format for a boolean flag key.
 */

export type BooleanFlagKey = `IS_${Uppercase<string>}_ENABLED` | `IS_${Uppercase<string>}_DISABLED`;
export type NumericFlagKey = `${Uppercase<string>}_NUMBER`;

export type FlagKey = BooleanFlagKey | NumericFlagKey;

export type FlagType<T> = T extends BooleanFlagKey ? boolean : T extends NumericFlagKey ? number : never;

/**
 * Helper function to test that enum keys and values match correct format.
 *
 * It is not possible as of Typescript 5.2 to declare a type for an enum key or value in-line.
 * Therefore, we must test the enum via a helper function that abstracts the enum to an object.
 *
 * If the test fails, you should review your `enum` to verify that both the
 * keys and values match the format specified by the `FlagKey` template literal type.
 * ref: https://stackoverflow.com/a/58181315
 *
 * @param testEnum - the Enum to type check
 */
export function testFlagEnumValidity<TEnum extends IFlags, IFlags = Record<FlagKey, FlagKey>>(
  _: TEnum & Record<Exclude<keyof TEnum, keyof IFlags>, ['Key must follow `FlagKey` format']>
) {}

export enum FeatureFlagsKeysEnum {
  // Boolean flags
  IS_API_IDEMPOTENCY_ENABLED = 'IS_API_IDEMPOTENCY_ENABLED',
  IS_API_RATE_LIMITING_DRY_RUN_ENABLED = 'IS_API_RATE_LIMITING_DRY_RUN_ENABLED',
  IS_API_RATE_LIMITING_KEYLESS_DRY_RUN_ENABLED = 'IS_API_RATE_LIMITING_KEYLESS_DRY_RUN_ENABLED',
  IS_API_RATE_LIMITING_ENABLED = 'IS_API_RATE_LIMITING_ENABLED',
  IS_CLOUDFLARE_SOCKETS_ENABLED = 'IS_CLOUDFLARE_SOCKETS_ENABLED',
  IS_LEGACY_WS_SERVICE_DISABLED = 'IS_LEGACY_WS_SERVICE_DISABLED',
  IS_EMAIL_INLINE_CSS_DISABLED = 'IS_EMAIL_INLINE_CSS_DISABLED',
  IS_EVENT_QUOTA_THROTTLER_ENABLED = 'IS_EVENT_QUOTA_THROTTLER_ENABLED',
  IS_NEW_MESSAGES_API_RESPONSE_ENABLED = 'IS_NEW_MESSAGES_API_RESPONSE_ENABLED',
  IS_TEMPLATE_STORE_ENABLED = 'IS_TEMPLATE_STORE_ENABLED',
  IS_USAGE_ALERTS_ENABLED = 'IS_USAGE_ALERTS_ENABLED',
  IS_USE_MERGED_DIGEST_ID_ENABLED = 'IS_USE_MERGED_DIGEST_ID_ENABLED',
  IS_V2_ENABLED = 'IS_V2_ENABLED',
  IS_SLACK_TEAMS_ENABLED = 'IS_SLACK_TEAMS_ENABLED',

  IS_WORKFLOW_NODE_PREVIEW_ENABLED = 'IS_WORKFLOW_NODE_PREVIEW_ENABLED',
  IS_WEBHOOKS_MANAGEMENT_ENABLED = 'IS_WEBHOOKS_MANAGEMENT_ENABLED',
  IS_INCR_IF_EXIST_USAGE_ENABLED = 'IS_INCR_IF_EXIST_USAGE_ENABLED',
  IS_KEYLESS_ENVIRONMENT_CREATION_ENABLED = 'IS_KEYLESS_ENVIRONMENT_CREATION_ENABLED',
  IS_TEST_PROVIDER_LIMITS_ENABLED = 'IS_TEST_PROVIDER_LIMITS_ENABLED',
  IS_2025_Q1_LEGACY_TIERING_MIGRATION = 'IS_2025_Q1_LEGACY_TIERING_MIGRATION',
  IS_SUBSCRIBER_ID_VALIDATION_DRY_RUN_ENABLED = 'IS_SUBSCRIBER_ID_VALIDATION_DRY_RUN_ENABLED',
  IS_TOPIC_KEYS_VALIDATION_DRY_RUN_ENABLED = 'IS_TOPIC_KEYS_VALIDATION_DRY_RUN_ENABLED',
  IS_RBAC_ENABLED = 'IS_RBAC_ENABLED',
  IS_HTTP_LOGS_PAGE_ENABLED = 'IS_HTTP_LOGS_PAGE_ENABLED',
  IS_TRACE_LOGS_ENABLED = 'IS_TRACE_LOGS_ENABLED',
  IS_TRACE_LOGS_READ_ENABLED = 'IS_TRACE_LOGS_READ_ENABLED',
  IS_OUTBOUND_WEBHOOKS_ENABLED = 'IS_OUTBOUND_WEBHOOKS_ENABLED',
  IS_INBOUND_WEBHOOKS_ENABLED = 'IS_INBOUND_WEBHOOKS_ENABLED',
  IS_INBOUND_WEBHOOKS_CONFIGURATION_ENABLED = 'IS_INBOUND_WEBHOOKS_CONFIGURATION_ENABLED',
  IS_STEP_RUN_LOGS_READ_ENABLED = 'IS_STEP_RUN_LOGS_READ_ENABLED',
  IS_STEP_RUN_LOGS_WRITE_ENABLED = 'IS_STEP_RUN_LOGS_WRITE_ENABLED',
  IS_WORKFLOW_RUN_LOGS_WRITE_ENABLED = 'IS_WORKFLOW_RUN_LOGS_WRITE_ENABLED',
  IS_WORKFLOW_RUN_LOGS_READ_ENABLED = 'IS_WORKFLOW_RUN_LOGS_READ_ENABLED',
  IS_WORKFLOW_RUN_TRACES_WRITE_ENABLED = 'IS_WORKFLOW_RUN_TRACES_WRITE_ENABLED',
  IS_WORKFLOW_RUN_PAGE_MIGRATION_ENABLED = 'IS_WORKFLOW_RUN_PAGE_MIGRATION_ENABLED',
  IS_WORKFLOW_RUN_TREND_FROM_TRACES_ENABLED = 'IS_WORKFLOW_RUN_TREND_FROM_TRACES_ENABLED',
  IS_DELIVERY_LIFECYCLE_TRANSITION_ENABLED = 'IS_DELIVERY_LIFECYCLE_TRANSITION_ENABLED',
  IS_EXECUTION_DETAILS_CLICKHOUSE_ONLY_ENABLED = 'IS_EXECUTION_DETAILS_CLICKHOUSE_ONLY_ENABLED',
  IS_SUBSCRIBERS_SCHEDULE_ENABLED = 'IS_SUBSCRIBERS_SCHEDULE_ENABLED',
  IS_GET_PREFERENCES_DISABLED = 'IS_GET_PREFERENCES_DISABLED',
  IS_THROTTLE_STEP_ENABLED = 'IS_THROTTLE_STEP_ENABLED',
  IS_REGION_SELECTOR_ENABLED = 'IS_REGION_SELECTOR_ENABLED',
  IS_PUSH_UNREAD_COUNT_ENABLED = 'IS_PUSH_UNREAD_COUNT_ENABLED',
  IS_EXPIRED_TOKENS_REMOVAL_ENABLED = 'IS_EXPIRED_TOKENS_REMOVAL_ENABLED',
  IS_ANALYTICS_WORKFLOW_FILTER_ENABLED = 'IS_ANALYTICS_WORKFLOW_FILTER_ENABLED',
  IS_CONTEXTUAL_HELP_DRAWER_ENABLED = 'IS_CONTEXTUAL_HELP_DRAWER_ENABLED',
  IS_SUBSCRIPTION_PREFERENCES_ENABLED = 'IS_SUBSCRIPTION_PREFERENCES_ENABLED',
  IS_LRU_CACHE_ENABLED = 'IS_LRU_CACHE_ENABLED',
  IS_CONTEXT_PREFERENCES_ENABLED = 'IS_CONTEXT_PREFERENCES_ENABLED',
  IS_PREFERENCE_FETCH_OPTIMIZATION_ENABLED = 'IS_PREFERENCE_FETCH_OPTIMIZATION_ENABLED',
  IS_ANALYTIC_V2_LOGS_READ_GLOBAL_ENABLED = 'IS_ANALYTIC_V2_LOGS_READ_GLOBAL_ENABLED',
  IS_ANALYTIC_V2_MESSAGE_DELIVERY_READ_ENABLED = 'IS_ANALYTIC_V2_MESSAGE_DELIVERY_READ_ENABLED',
  IS_ANALYTIC_V2_ACTIVE_SUBSCRIBER_TREND_READ_ENABLED = 'IS_ANALYTIC_V2_ACTIVE_SUBSCRIBER_TREND_READ_ENABLED',
  IS_ANALYTIC_V2_AVG_MESSAGES_PER_SUBSCRIBER_READ_ENABLED = 'IS_ANALYTIC_V2_AVG_MESSAGES_PER_SUBSCRIBER_READ_ENABLED',
  IS_ANALYTIC_V2_PROVIDER_VOLUME_READ_ENABLED = 'IS_ANALYTIC_V2_PROVIDER_VOLUME_READ_ENABLED',
  IS_ANALYTIC_V2_INTERACTION_TREND_READ_ENABLED = 'IS_ANALYTIC_V2_INTERACTION_TREND_READ_ENABLED',
  IS_ANALYTIC_V2_DELIVERY_TREND_READ_ENABLED = 'IS_ANALYTIC_V2_DELIVERY_TREND_READ_ENABLED',
  IS_ANALYTIC_V2_ACTIVE_SUBSCRIBERS_READ_ENABLED = 'IS_ANALYTIC_V2_ACTIVE_SUBSCRIBERS_READ_ENABLED',
  IS_ANALYTIC_V2_TOTAL_INTERACTIONS_READ_ENABLED = 'IS_ANALYTIC_V2_TOTAL_INTERACTIONS_READ_ENABLED',
  IS_BILLING_USAGE_CLICKHOUSE_ENABLED = 'IS_BILLING_USAGE_CLICKHOUSE_ENABLED',
  IS_BILLING_USAGE_CLICKHOUSE_SHADOW_ENABLED = 'IS_BILLING_USAGE_CLICKHOUSE_SHADOW_ENABLED',
  IS_BILLING_USAGE_DETAILED_DIAGNOSTICS_ENABLED = 'IS_BILLING_USAGE_DETAILED_DIAGNOSTICS_ENABLED',
  IS_AI_WORKFLOW_GENERATION_ENABLED = 'IS_AI_WORKFLOW_GENERATION_ENABLED',
  IS_CLICKHOUSE_BATCHING_ENABLED = 'IS_CLICKHOUSE_BATCHING_ENABLED',
  IS_ORG_KILLSWITCH_FLAG_ENABLED = 'IS_ORG_KILLSWITCH_FLAG_ENABLED',
  IS_USAGE_REPORT_ENABLED = 'IS_USAGE_REPORT_ENABLED',
  IS_USAGE_REPORT_DELAY_ENABLED = 'IS_USAGE_REPORT_DELAY_ENABLED',
  IS_STEP_RESOLVER_ENABLED = 'IS_STEP_RESOLVER_ENABLED',

  // String flags
  CF_SCHEDULER_MODE = 'CF_SCHEDULER_MODE', // Values: "off" | "shadow" | "live" | "complete"
  QUEUE_BACKEND_MODE = 'QUEUE_BACKEND_MODE', // Values: "bullmq" | "shadow" | "live" | "complete"
  USAGE_REPORT_TRIGGER_SECRET = 'USAGE_REPORT_TRIGGER_SECRET',
  USAGE_REPORT_OVERRIDE_EMAIL = 'USAGE_REPORT_OVERRIDE_EMAIL',

  // Numeric flags
  MAX_WORKFLOW_LIMIT_NUMBER = 'MAX_WORKFLOW_LIMIT_NUMBER',
  MAX_LAYOUT_LIMIT_NUMBER = 'MAX_LAYOUT_LIMIT_NUMBER',
  MAX_STEPS_PER_WORKFLOW_LIMIT_NUMBER = 'MAX_STEPS_PER_WORKFLOW_LIMIT_NUMBER',
  MAX_DEFER_DURATION_IN_MS_NUMBER = 'MAX_DEFER_DURATION_IN_MS_NUMBER',
  MAX_THROTTLE_WINDOW_DURATION_IN_MS_NUMBER = 'MAX_THROTTLE_WINDOW_DURATION_IN_MS_NUMBER',
  LOG_EXPIRATION_DAYS_NUMBER = 'LOG_EXPIRATION_DAYS_NUMBER',
  MAX_DATE_ANALYTICS_ENABLED_NUMBER = 'MAX_DATE_ANALYTICS_ENABLED_NUMBER',
  MAX_ENVIRONMENT_COUNT = 'MAX_ENVIRONMENT_COUNT',
  IS_ANALYTICS_PAGE_ENABLED = 'IS_ANALYTICS_PAGE_ENABLED',
  IS_LEGACY_SELECTOR_BUTTON_VISIBLE = 'IS_LEGACY_SELECTOR_BUTTON_VISIBLE',
}

export enum CloudflareSchedulerMode {
  OFF = 'off',
  SHADOW = 'shadow',
  LIVE = 'live',
  COMPLETE = 'complete',
}

export enum QueueBackendMode {
  BULLMQ = 'bullmq',
  SHADOW = 'shadow',
  LIVE = 'live',
  COMPLETE = 'complete',
}

export type FeatureFlags = {
  [key in FeatureFlagsKeysEnum]: boolean | number | string | undefined;
};
