export enum StepContentIssueEnum {
  ILLEGAL_VARIABLE_IN_CONTROL_VALUE = 'ILLEGAL_VARIABLE_IN_CONTROL_VALUE',
  MISSING_VALUE = 'MISSING_VALUE',
  TIER_LIMIT_EXCEEDED = 'TIER_LIMIT_EXCEEDED',
}

export enum StepIntegrationIssueEnum {
  MISSING_INTEGRATION = 'MISSING_INTEGRATION',
}

export enum StepIssueEnum {
  ILLEGAL_VARIABLE_IN_CONTROL_VALUE = 'ILLEGAL_VARIABLE_IN_CONTROL_VALUE',
  MISSING_VALUE = 'MISSING_VALUE',
  TIER_LIMIT_EXCEEDED = 'TIER_LIMIT_EXCEEDED',
  MISSING_INTEGRATION = 'MISSING_INTEGRATION',
}
