/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  UseQueryResult,
  UseSuspenseQueryResult,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import * as operations from '../models/operations/index.js';
import { useNovuContext } from './_context.js';
import { QueryHookOptions, SuspenseQueryHookOptions, TupleToPrefixes } from './_types.js';
import {
  ActivityWorkflowRunsListQueryData,
  buildActivityWorkflowRunsListQuery,
  prefetchActivityWorkflowRunsList,
  queryKeyActivityWorkflowRunsList,
} from './activityWorkflowRunsList.core.js';
export {
  type ActivityWorkflowRunsListQueryData,
  buildActivityWorkflowRunsListQuery,
  prefetchActivityWorkflowRunsList,
  queryKeyActivityWorkflowRunsList,
};

/**
 * List workflow runs
 *
 * @remarks
 * Retrieve a list of workflow runs with optional filtering and pagination.
 */
export function useActivityWorkflowRunsList(
  request: operations.ActivityControllerGetWorkflowRunsRequest,
  options?: QueryHookOptions<ActivityWorkflowRunsListQueryData>
): UseQueryResult<ActivityWorkflowRunsListQueryData, Error> {
  const client = useNovuContext();
  return useQuery({
    ...buildActivityWorkflowRunsListQuery(client, request, options),
    ...options,
  });
}

/**
 * List workflow runs
 *
 * @remarks
 * Retrieve a list of workflow runs with optional filtering and pagination.
 */
export function useActivityWorkflowRunsListSuspense(
  request: operations.ActivityControllerGetWorkflowRunsRequest,
  options?: SuspenseQueryHookOptions<ActivityWorkflowRunsListQueryData>
): UseSuspenseQueryResult<ActivityWorkflowRunsListQueryData, Error> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildActivityWorkflowRunsListQuery(client, request, options),
    ...options,
  });
}

export function setActivityWorkflowRunsListData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      limit: number | undefined;
      cursor?: string | undefined;
      workflowIds?: Array<string> | undefined;
      subscriberIds?: Array<string> | undefined;
      transactionIds?: Array<string> | undefined;
      statuses?: Array<operations.QueryParamStatuses> | undefined;
      channels?: Array<string> | undefined;
      topicKey?: string | undefined;
      subscriptionId?: string | undefined;
      createdGte?: string | undefined;
      createdLte?: string | undefined;
      severity?: Array<operations.Severity> | undefined;
      contextKeys?: Array<string> | undefined;
      idempotencyKey?: string | undefined;
    },
  ],
  data: ActivityWorkflowRunsListQueryData
): ActivityWorkflowRunsListQueryData | undefined {
  const key = queryKeyActivityWorkflowRunsList(...queryKeyBase);

  return client.setQueryData<ActivityWorkflowRunsListQueryData>(key, data);
}

export function invalidateActivityWorkflowRunsList(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      parameters: {
        limit: number | undefined;
        cursor?: string | undefined;
        workflowIds?: Array<string> | undefined;
        subscriberIds?: Array<string> | undefined;
        transactionIds?: Array<string> | undefined;
        statuses?: Array<operations.QueryParamStatuses> | undefined;
        channels?: Array<string> | undefined;
        topicKey?: string | undefined;
        subscriptionId?: string | undefined;
        createdGte?: string | undefined;
        createdLte?: string | undefined;
        severity?: Array<operations.Severity> | undefined;
        contextKeys?: Array<string> | undefined;
        idempotencyKey?: string | undefined;
      },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, 'queryKey' | 'predicate' | 'exact'>
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ['@novu/api', 'WorkflowRuns', 'list', ...queryKeyBase],
  });
}

export function invalidateAllActivityWorkflowRunsList(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, 'queryKey' | 'predicate' | 'exact'>
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ['@novu/api', 'WorkflowRuns', 'list'],
  });
}
