/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { channelConnectionsRetrieve } from "../funcs/channelConnectionsRetrieve.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type ChannelConnectionsRetrieveQueryData =
  operations.ChannelConnectionsControllerGetChannelConnectionByIdentifierResponse;

export function prefetchChannelConnectionsRetrieve(
  queryClient: QueryClient,
  client$: NovuCore,
  identifier: string,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildChannelConnectionsRetrieveQuery(
      client$,
      identifier,
      idempotencyKey,
      options,
    ),
  });
}

export function buildChannelConnectionsRetrieveQuery(
  client$: NovuCore,
  identifier: string,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<ChannelConnectionsRetrieveQueryData>;
} {
  return {
    queryKey: queryKeyChannelConnectionsRetrieve(identifier, {
      idempotencyKey,
    }),
    queryFn: async function channelConnectionsRetrieveQueryFn(
      ctx,
    ): Promise<ChannelConnectionsRetrieveQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(channelConnectionsRetrieve(
        client$,
        identifier,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyChannelConnectionsRetrieve(
  identifier: string,
  parameters: { idempotencyKey?: string | undefined },
): QueryKey {
  return [
    "@novu/api",
    "Channel Connections",
    "retrieve",
    identifier,
    parameters,
  ];
}
