/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { domainsAutoConfigureRetrieve } from "../funcs/domainsAutoConfigureRetrieve.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type DomainsAutoConfigureRetrieveQueryData =
  operations.DomainsControllerGetDomainAutoConfigureResponse;

export function prefetchDomainsAutoConfigureRetrieve(
  queryClient: QueryClient,
  client$: NovuCore,
  domain: string,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildDomainsAutoConfigureRetrieveQuery(
      client$,
      domain,
      idempotencyKey,
      options,
    ),
  });
}

export function buildDomainsAutoConfigureRetrieveQuery(
  client$: NovuCore,
  domain: string,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<DomainsAutoConfigureRetrieveQueryData>;
} {
  return {
    queryKey: queryKeyDomainsAutoConfigureRetrieve(domain, { idempotencyKey }),
    queryFn: async function domainsAutoConfigureRetrieveQueryFn(
      ctx,
    ): Promise<DomainsAutoConfigureRetrieveQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(domainsAutoConfigureRetrieve(
        client$,
        domain,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyDomainsAutoConfigureRetrieve(
  domain: string,
  parameters: { idempotencyKey?: string | undefined },
): QueryKey {
  return ["@novu/api", "AutoConfigure", "retrieve", domain, parameters];
}
