/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { NovuError } from "../models/errors/novuerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildDomainsDomainConnectStatusQuery,
  DomainsDomainConnectStatusQueryData,
  prefetchDomainsDomainConnectStatus,
  queryKeyDomainsDomainConnectStatus,
} from "./domainsDomainConnectStatus.core.js";
export {
  buildDomainsDomainConnectStatusQuery,
  type DomainsDomainConnectStatusQueryData,
  prefetchDomainsDomainConnectStatus,
  queryKeyDomainsDomainConnectStatus,
};

export type DomainsDomainConnectStatusQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Get Domain Connect auto-configuration availability for a domain
 */
export function useDomainsDomainConnectStatus(
  domain: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<
    DomainsDomainConnectStatusQueryData,
    DomainsDomainConnectStatusQueryError
  >,
): UseQueryResult<
  DomainsDomainConnectStatusQueryData,
  DomainsDomainConnectStatusQueryError
> {
  const client = useNovuContext();
  return useQuery({
    ...buildDomainsDomainConnectStatusQuery(
      client,
      domain,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

/**
 * Get Domain Connect auto-configuration availability for a domain
 */
export function useDomainsDomainConnectStatusSuspense(
  domain: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<
    DomainsDomainConnectStatusQueryData,
    DomainsDomainConnectStatusQueryError
  >,
): UseSuspenseQueryResult<
  DomainsDomainConnectStatusQueryData,
  DomainsDomainConnectStatusQueryError
> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildDomainsDomainConnectStatusQuery(
      client,
      domain,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function setDomainsDomainConnectStatusData(
  client: QueryClient,
  queryKeyBase: [
    domain: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: DomainsDomainConnectStatusQueryData,
): DomainsDomainConnectStatusQueryData | undefined {
  const key = queryKeyDomainsDomainConnectStatus(...queryKeyBase);

  return client.setQueryData<DomainsDomainConnectStatusQueryData>(key, data);
}

export function invalidateDomainsDomainConnectStatus(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [domain: string, parameters: { idempotencyKey?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "DomainConnect", "status", ...queryKeyBase],
  });
}

export function invalidateAllDomainsDomainConnectStatus(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "DomainConnect", "status"],
  });
}
