/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { NovuError } from "../models/errors/novuerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildEnvironmentVariablesUsageQuery,
  EnvironmentVariablesUsageQueryData,
  prefetchEnvironmentVariablesUsage,
  queryKeyEnvironmentVariablesUsage,
} from "./environmentVariablesUsage.core.js";
export {
  buildEnvironmentVariablesUsageQuery,
  type EnvironmentVariablesUsageQueryData,
  prefetchEnvironmentVariablesUsage,
  queryKeyEnvironmentVariablesUsage,
};

export type EnvironmentVariablesUsageQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Retrieve a variable usage
 *
 * @remarks
 * Returns the workflows that reference this environment variable via `{{env.KEY}}` in their step controls. **variableId** is required.
 */
export function useEnvironmentVariablesUsage(
  variableKey: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<
    EnvironmentVariablesUsageQueryData,
    EnvironmentVariablesUsageQueryError
  >,
): UseQueryResult<
  EnvironmentVariablesUsageQueryData,
  EnvironmentVariablesUsageQueryError
> {
  const client = useNovuContext();
  return useQuery({
    ...buildEnvironmentVariablesUsageQuery(
      client,
      variableKey,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

/**
 * Retrieve a variable usage
 *
 * @remarks
 * Returns the workflows that reference this environment variable via `{{env.KEY}}` in their step controls. **variableId** is required.
 */
export function useEnvironmentVariablesUsageSuspense(
  variableKey: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<
    EnvironmentVariablesUsageQueryData,
    EnvironmentVariablesUsageQueryError
  >,
): UseSuspenseQueryResult<
  EnvironmentVariablesUsageQueryData,
  EnvironmentVariablesUsageQueryError
> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildEnvironmentVariablesUsageQuery(
      client,
      variableKey,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function setEnvironmentVariablesUsageData(
  client: QueryClient,
  queryKeyBase: [
    variableKey: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: EnvironmentVariablesUsageQueryData,
): EnvironmentVariablesUsageQueryData | undefined {
  const key = queryKeyEnvironmentVariablesUsage(...queryKeyBase);

  return client.setQueryData<EnvironmentVariablesUsageQueryData>(key, data);
}

export function invalidateEnvironmentVariablesUsage(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [variableKey: string, parameters: { idempotencyKey?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Environment Variables", "usage", ...queryKeyBase],
  });
}

export function invalidateAllEnvironmentVariablesUsage(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Environment Variables", "usage"],
  });
}
