/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { environmentsList } from "../funcs/environmentsList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type EnvironmentsListQueryData =
  operations.EnvironmentsControllerV1ListMyEnvironmentsResponse;

export function prefetchEnvironmentsList(
  queryClient: QueryClient,
  client$: NovuCore,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildEnvironmentsListQuery(
      client$,
      idempotencyKey,
      options,
    ),
  });
}

export function buildEnvironmentsListQuery(
  client$: NovuCore,
  idempotencyKey?: string | undefined,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<EnvironmentsListQueryData>;
} {
  return {
    queryKey: queryKeyEnvironmentsList({ idempotencyKey }),
    queryFn: async function environmentsListQueryFn(
      ctx,
    ): Promise<EnvironmentsListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(environmentsList(
        client$,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyEnvironmentsList(
  parameters: { idempotencyKey?: string | undefined },
): QueryKey {
  return ["@novu/api", "Environments", "list", parameters];
}
