/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { inboundWebhooksControllerHandleWebhook } from "../funcs/inboundWebhooksControllerHandleWebhook.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type InboundWebhooksControllerHandleWebhookMutationVariables = {
  environmentId: string;
  integrationId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type InboundWebhooksControllerHandleWebhookMutationData = void;

export function useInboundWebhooksControllerHandleWebhookMutation(
  options?: MutationHookOptions<
    InboundWebhooksControllerHandleWebhookMutationData,
    Error,
    InboundWebhooksControllerHandleWebhookMutationVariables
  >,
): UseMutationResult<
  InboundWebhooksControllerHandleWebhookMutationData,
  Error,
  InboundWebhooksControllerHandleWebhookMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildInboundWebhooksControllerHandleWebhookMutation(client, options),
    ...options,
  });
}

export function mutationKeyInboundWebhooksControllerHandleWebhook(): MutationKey {
  return ["@novu/api", "inboundWebhooksControllerHandleWebhook"];
}

export function buildInboundWebhooksControllerHandleWebhookMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: InboundWebhooksControllerHandleWebhookMutationVariables,
  ) => Promise<InboundWebhooksControllerHandleWebhookMutationData>;
} {
  return {
    mutationKey: mutationKeyInboundWebhooksControllerHandleWebhook(),
    mutationFn: function inboundWebhooksControllerHandleWebhookMutationFn({
      environmentId,
      integrationId,
      idempotencyKey,
      options,
    }): Promise<InboundWebhooksControllerHandleWebhookMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(inboundWebhooksControllerHandleWebhook(
        client$,
        environmentId,
        integrationId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
