/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildLayoutsUsageQuery,
  LayoutsUsageQueryData,
  prefetchLayoutsUsage,
  queryKeyLayoutsUsage,
} from "./layoutsUsage.core.js";
export {
  buildLayoutsUsageQuery,
  type LayoutsUsageQueryData,
  prefetchLayoutsUsage,
  queryKeyLayoutsUsage,
};

/**
 * Get layout usage
 *
 * @remarks
 * Retrieves information about workflows that use the specified layout by its unique identifier **layoutId**
 */
export function useLayoutsUsage(
  layoutId: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<LayoutsUsageQueryData>,
): UseQueryResult<LayoutsUsageQueryData, Error> {
  const client = useNovuContext();
  return useQuery({
    ...buildLayoutsUsageQuery(
      client,
      layoutId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

/**
 * Get layout usage
 *
 * @remarks
 * Retrieves information about workflows that use the specified layout by its unique identifier **layoutId**
 */
export function useLayoutsUsageSuspense(
  layoutId: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<LayoutsUsageQueryData>,
): UseSuspenseQueryResult<LayoutsUsageQueryData, Error> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildLayoutsUsageQuery(
      client,
      layoutId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function setLayoutsUsageData(
  client: QueryClient,
  queryKeyBase: [
    layoutId: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: LayoutsUsageQueryData,
): LayoutsUsageQueryData | undefined {
  const key = queryKeyLayoutsUsage(...queryKeyBase);

  return client.setQueryData<LayoutsUsageQueryData>(key, data);
}

export function invalidateLayoutsUsage(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [layoutId: string, parameters: { idempotencyKey?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Layouts", "usage", ...queryKeyBase],
  });
}

export function invalidateAllLayoutsUsage(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Layouts", "usage"],
  });
}
