/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { messagesDeleteByTransactionId } from "../funcs/messagesDeleteByTransactionId.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type MessagesDeleteByTransactionIdMutationVariables = {
  transactionId: string;
  channel?: operations.Channel | undefined;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type MessagesDeleteByTransactionIdMutationData =
  | operations.MessagesControllerDeleteMessagesByTransactionIdResponse
  | undefined;

/**
 * Delete messages by transactionId
 *
 * @remarks
 * Deletes messages entity from the Novu platform using TransactionId of message
 */
export function useMessagesDeleteByTransactionIdMutation(
  options?: MutationHookOptions<
    MessagesDeleteByTransactionIdMutationData,
    Error,
    MessagesDeleteByTransactionIdMutationVariables
  >,
): UseMutationResult<
  MessagesDeleteByTransactionIdMutationData,
  Error,
  MessagesDeleteByTransactionIdMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildMessagesDeleteByTransactionIdMutation(client, options),
    ...options,
  });
}

export function mutationKeyMessagesDeleteByTransactionId(): MutationKey {
  return ["@novu/api", "Messages", "deleteByTransactionId"];
}

export function buildMessagesDeleteByTransactionIdMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: MessagesDeleteByTransactionIdMutationVariables,
  ) => Promise<MessagesDeleteByTransactionIdMutationData>;
} {
  return {
    mutationKey: mutationKeyMessagesDeleteByTransactionId(),
    mutationFn: function messagesDeleteByTransactionIdMutationFn({
      transactionId,
      channel,
      idempotencyKey,
      options,
    }): Promise<MessagesDeleteByTransactionIdMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(messagesDeleteByTransactionId(
        client$,
        transactionId,
        channel,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
