/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import * as components from "../models/components/index.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { NovuError } from "../models/errors/novuerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildMessagesRetrieveQuery,
  MessagesRetrieveQueryData,
  prefetchMessagesRetrieve,
  queryKeyMessagesRetrieve,
} from "./messagesRetrieve.core.js";
export {
  buildMessagesRetrieveQuery,
  type MessagesRetrieveQueryData,
  prefetchMessagesRetrieve,
  queryKeyMessagesRetrieve,
};

export type MessagesRetrieveQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * List all messages
 *
 * @remarks
 * List all messages for the current environment.
 *     This API supports filtering by **channel**, **subscriberId**, and **transactionId**.
 *     This API returns a paginated list of messages.
 */
export function useMessagesRetrieve(
  request: operations.MessagesControllerGetMessagesRequest,
  options?: QueryHookOptions<
    MessagesRetrieveQueryData,
    MessagesRetrieveQueryError
  >,
): UseQueryResult<MessagesRetrieveQueryData, MessagesRetrieveQueryError> {
  const client = useNovuContext();
  return useQuery({
    ...buildMessagesRetrieveQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List all messages
 *
 * @remarks
 * List all messages for the current environment.
 *     This API supports filtering by **channel**, **subscriberId**, and **transactionId**.
 *     This API returns a paginated list of messages.
 */
export function useMessagesRetrieveSuspense(
  request: operations.MessagesControllerGetMessagesRequest,
  options?: SuspenseQueryHookOptions<
    MessagesRetrieveQueryData,
    MessagesRetrieveQueryError
  >,
): UseSuspenseQueryResult<
  MessagesRetrieveQueryData,
  MessagesRetrieveQueryError
> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildMessagesRetrieveQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setMessagesRetrieveData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      channel?: components.ChannelTypeEnum | undefined;
      subscriberId?: string | undefined;
      transactionId?: Array<string> | undefined;
      contextKeys?: Array<string> | undefined;
      page?: number | undefined;
      limit?: number | undefined;
      idempotencyKey?: string | undefined;
    },
  ],
  data: MessagesRetrieveQueryData,
): MessagesRetrieveQueryData | undefined {
  const key = queryKeyMessagesRetrieve(...queryKeyBase);

  return client.setQueryData<MessagesRetrieveQueryData>(key, data);
}

export function invalidateMessagesRetrieve(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      channel?: components.ChannelTypeEnum | undefined;
      subscriberId?: string | undefined;
      transactionId?: Array<string> | undefined;
      contextKeys?: Array<string> | undefined;
      page?: number | undefined;
      limit?: number | undefined;
      idempotencyKey?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Messages", "retrieve", ...queryKeyBase],
  });
}

export function invalidateAllMessagesRetrieve(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Messages", "retrieve"],
  });
}
