/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { NovuError } from "../models/errors/novuerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildSubscribersRetrieveQuery,
  prefetchSubscribersRetrieve,
  queryKeySubscribersRetrieve,
  SubscribersRetrieveQueryData,
} from "./subscribersRetrieve.core.js";
export {
  buildSubscribersRetrieveQuery,
  prefetchSubscribersRetrieve,
  queryKeySubscribersRetrieve,
  type SubscribersRetrieveQueryData,
};

export type SubscribersRetrieveQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Retrieve a subscriber
 *
 * @remarks
 * Retrieve a subscriber by its unique key identifier **subscriberId**.
 *     **subscriberId** field is required.
 */
export function useSubscribersRetrieve(
  subscriberId: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<
    SubscribersRetrieveQueryData,
    SubscribersRetrieveQueryError
  >,
): UseQueryResult<SubscribersRetrieveQueryData, SubscribersRetrieveQueryError> {
  const client = useNovuContext();
  return useQuery({
    ...buildSubscribersRetrieveQuery(
      client,
      subscriberId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

/**
 * Retrieve a subscriber
 *
 * @remarks
 * Retrieve a subscriber by its unique key identifier **subscriberId**.
 *     **subscriberId** field is required.
 */
export function useSubscribersRetrieveSuspense(
  subscriberId: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<
    SubscribersRetrieveQueryData,
    SubscribersRetrieveQueryError
  >,
): UseSuspenseQueryResult<
  SubscribersRetrieveQueryData,
  SubscribersRetrieveQueryError
> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildSubscribersRetrieveQuery(
      client,
      subscriberId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function setSubscribersRetrieveData(
  client: QueryClient,
  queryKeyBase: [
    subscriberId: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: SubscribersRetrieveQueryData,
): SubscribersRetrieveQueryData | undefined {
  const key = queryKeySubscribersRetrieve(...queryKeyBase);

  return client.setQueryData<SubscribersRetrieveQueryData>(key, data);
}

export function invalidateSubscribersRetrieve(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [subscriberId: string, parameters: { idempotencyKey?: string | undefined }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Subscribers", "retrieve", ...queryKeyBase],
  });
}

export function invalidateAllSubscribersRetrieve(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Subscribers", "retrieve"],
  });
}
