/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { subscribersPreferencesList } from "../funcs/subscribersPreferencesList.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type SubscribersPreferencesListQueryData =
  operations.SubscribersControllerGetSubscriberPreferencesResponse;

export function prefetchSubscribersPreferencesList(
  queryClient: QueryClient,
  client$: NovuCore,
  request: operations.SubscribersControllerGetSubscriberPreferencesRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildSubscribersPreferencesListQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildSubscribersPreferencesListQuery(
  client$: NovuCore,
  request: operations.SubscribersControllerGetSubscriberPreferencesRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<SubscribersPreferencesListQueryData>;
} {
  return {
    queryKey: queryKeySubscribersPreferencesList(request.subscriberId, {
      criticality: request.criticality,
      contextKeys: request.contextKeys,
      idempotencyKey: request.idempotencyKey,
    }),
    queryFn: async function subscribersPreferencesListQueryFn(
      ctx,
    ): Promise<SubscribersPreferencesListQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(subscribersPreferencesList(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeySubscribersPreferencesList(
  subscriberId: string,
  parameters: {
    criticality?: operations.Criticality | undefined;
    contextKeys?: Array<string> | undefined;
    idempotencyKey?: string | undefined;
  },
): QueryKey {
  return ["@novu/api", "Preferences", "list", subscriberId, parameters];
}
