/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { subscribersNotificationsUnseenCount } from "../funcs/subscribersNotificationsUnseenCount.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type SubscribersNotificationsUnseenCountQueryData =
  operations.SubscribersV1ControllerGetUnseenCountResponse;

export function prefetchSubscribersNotificationsUnseenCount(
  queryClient: QueryClient,
  client$: NovuCore,
  request: operations.SubscribersV1ControllerGetUnseenCountRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildSubscribersNotificationsUnseenCountQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildSubscribersNotificationsUnseenCountQuery(
  client$: NovuCore,
  request: operations.SubscribersV1ControllerGetUnseenCountRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<SubscribersNotificationsUnseenCountQueryData>;
} {
  return {
    queryKey: queryKeySubscribersNotificationsUnseenCount(
      request.subscriberId,
      {
        seen: request.seen,
        limit: request.limit,
        idempotencyKey: request.idempotencyKey,
      },
    ),
    queryFn: async function subscribersNotificationsUnseenCountQueryFn(
      ctx,
    ): Promise<SubscribersNotificationsUnseenCountQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(subscribersNotificationsUnseenCount(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeySubscribersNotificationsUnseenCount(
  subscriberId: string,
  parameters: {
    seen?: boolean | undefined;
    limit?: number | undefined;
    idempotencyKey?: string | undefined;
  },
): QueryKey {
  return [
    "@novu/api",
    "Notifications",
    "unseenCount",
    subscriberId,
    parameters,
  ];
}
