/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsSearch } from "../funcs/workflowsSearch.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type WorkflowsSearchQueryData =
  operations.WorkflowControllerSearchWorkflowsResponse;

/**
 * Search workflows
 *
 * @remarks
 * Retrieves a list of workflows with optional filtering and pagination
 */
export function useWorkflowsSearch(
  request: operations.WorkflowControllerSearchWorkflowsRequest,
  options?: QueryHookOptions<WorkflowsSearchQueryData>,
): UseQueryResult<WorkflowsSearchQueryData, Error> {
  const client = useNovuContext();
  return useQuery({
    ...buildWorkflowsSearchQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Search workflows
 *
 * @remarks
 * Retrieves a list of workflows with optional filtering and pagination
 */
export function useWorkflowsSearchSuspense(
  request: operations.WorkflowControllerSearchWorkflowsRequest,
  options?: SuspenseQueryHookOptions<WorkflowsSearchQueryData>,
): UseSuspenseQueryResult<WorkflowsSearchQueryData, Error> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildWorkflowsSearchQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchWorkflowsSearch(
  queryClient: QueryClient,
  client$: NovuCore,
  request: operations.WorkflowControllerSearchWorkflowsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildWorkflowsSearchQuery(
      client$,
      request,
    ),
  });
}

export function setWorkflowsSearchData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      limit?: number | undefined;
      offset?: number | undefined;
      orderDirection?: components.DirectionEnum | undefined;
      orderBy?: components.WorkflowResponseDtoSortField | undefined;
      query?: string | undefined;
      idempotencyKey?: string | undefined;
    },
  ],
  data: WorkflowsSearchQueryData,
): WorkflowsSearchQueryData | undefined {
  const key = queryKeyWorkflowsSearch(...queryKeyBase);

  return client.setQueryData<WorkflowsSearchQueryData>(key, data);
}

export function invalidateWorkflowsSearch(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      limit?: number | undefined;
      offset?: number | undefined;
      orderDirection?: components.DirectionEnum | undefined;
      orderBy?: components.WorkflowResponseDtoSortField | undefined;
      query?: string | undefined;
      idempotencyKey?: string | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Workflows", "search", ...queryKeyBase],
  });
}

export function invalidateAllWorkflowsSearch(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Workflows", "search"],
  });
}

export function buildWorkflowsSearchQuery(
  client$: NovuCore,
  request: operations.WorkflowControllerSearchWorkflowsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<WorkflowsSearchQueryData>;
} {
  return {
    queryKey: queryKeyWorkflowsSearch({
      limit: request.limit,
      offset: request.offset,
      orderDirection: request.orderDirection,
      orderBy: request.orderBy,
      query: request.query,
      idempotencyKey: request.idempotencyKey,
    }),
    queryFn: async function workflowsSearchQueryFn(
      ctx,
    ): Promise<WorkflowsSearchQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(workflowsSearch(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyWorkflowsSearch(
  parameters: {
    limit?: number | undefined;
    offset?: number | undefined;
    orderDirection?: components.DirectionEnum | undefined;
    orderBy?: components.WorkflowResponseDtoSortField | undefined;
    query?: string | undefined;
    idempotencyKey?: string | undefined;
  },
): QueryKey {
  return ["@novu/api", "Workflows", "search", parameters];
}
