/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsDuplicate } from "../funcs/workflowsDuplicate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkflowsDuplicateMutationVariables = {
  duplicateWorkflowDto: components.DuplicateWorkflowDto;
  workflowId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type WorkflowsDuplicateMutationData =
  operations.WorkflowControllerDuplicateWorkflowResponse;

/**
 * Duplicate a workflow
 *
 * @remarks
 * Duplicates a workflow by its unique identifier **workflowId**. This will create a new workflow with the same steps and settings.
 */
export function useWorkflowsDuplicateMutation(
  options?: MutationHookOptions<
    WorkflowsDuplicateMutationData,
    Error,
    WorkflowsDuplicateMutationVariables
  >,
): UseMutationResult<
  WorkflowsDuplicateMutationData,
  Error,
  WorkflowsDuplicateMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildWorkflowsDuplicateMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkflowsDuplicate(): MutationKey {
  return ["@novu/api", "Workflows", "duplicate"];
}

export function buildWorkflowsDuplicateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkflowsDuplicateMutationVariables,
  ) => Promise<WorkflowsDuplicateMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkflowsDuplicate(),
    mutationFn: function workflowsDuplicateMutationFn({
      duplicateWorkflowDto,
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsDuplicateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workflowsDuplicate(
        client$,
        duplicateWorkflowDto,
        workflowId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
