/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsSync } from "../funcs/workflowsSync.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkflowsSyncMutationVariables = {
  syncWorkflowDto: components.SyncWorkflowDto;
  workflowId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type WorkflowsSyncMutationData =
  operations.WorkflowControllerSyncResponse;

/**
 * Sync a workflow
 *
 * @remarks
 * Synchronizes a workflow to the target environment
 */
export function useWorkflowsSyncMutation(
  options?: MutationHookOptions<
    WorkflowsSyncMutationData,
    Error,
    WorkflowsSyncMutationVariables
  >,
): UseMutationResult<
  WorkflowsSyncMutationData,
  Error,
  WorkflowsSyncMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildWorkflowsSyncMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkflowsSync(): MutationKey {
  return ["@novu/api", "Workflows", "sync"];
}

export function buildWorkflowsSyncMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkflowsSyncMutationVariables,
  ) => Promise<WorkflowsSyncMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkflowsSync(),
    mutationFn: function workflowsSyncMutationFn({
      syncWorkflowDto,
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsSyncMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workflowsSync(
        client$,
        syncWorkflowDto,
        workflowId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
