/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsUpdate } from "../funcs/workflowsUpdate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkflowsUpdateMutationVariables = {
  workflowId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type WorkflowsUpdateMutationData =
  operations.WorkflowControllerUpdateResponse;

export function useWorkflowsUpdateMutation(
  options?: MutationHookOptions<
    WorkflowsUpdateMutationData,
    Error,
    WorkflowsUpdateMutationVariables
  >,
): UseMutationResult<
  WorkflowsUpdateMutationData,
  Error,
  WorkflowsUpdateMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildWorkflowsUpdateMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkflowsUpdate(): MutationKey {
  return ["@novu/api", "Workflows", "update"];
}

export function buildWorkflowsUpdateMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkflowsUpdateMutationVariables,
  ) => Promise<WorkflowsUpdateMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkflowsUpdate(),
    mutationFn: function workflowsUpdateMutationFn({
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsUpdateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workflowsUpdate(
        client$,
        workflowId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
