/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { NovuCore } from "../core.js";
import { workflowsWorkflowControllerPatchWorkflow } from "../funcs/workflowsWorkflowControllerPatchWorkflow.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useNovuContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type WorkflowsWorkflowControllerPatchWorkflowMutationVariables = {
  workflowId: string;
  idempotencyKey?: string | undefined;
  options?: RequestOptions;
};

export type WorkflowsWorkflowControllerPatchWorkflowMutationData =
  operations.WorkflowControllerPatchWorkflowResponse;

export function useWorkflowsWorkflowControllerPatchWorkflowMutation(
  options?: MutationHookOptions<
    WorkflowsWorkflowControllerPatchWorkflowMutationData,
    Error,
    WorkflowsWorkflowControllerPatchWorkflowMutationVariables
  >,
): UseMutationResult<
  WorkflowsWorkflowControllerPatchWorkflowMutationData,
  Error,
  WorkflowsWorkflowControllerPatchWorkflowMutationVariables
> {
  const client = useNovuContext();
  return useMutation({
    ...buildWorkflowsWorkflowControllerPatchWorkflowMutation(client, options),
    ...options,
  });
}

export function mutationKeyWorkflowsWorkflowControllerPatchWorkflow(): MutationKey {
  return ["@novu/api", "Workflows", "workflowControllerPatchWorkflow"];
}

export function buildWorkflowsWorkflowControllerPatchWorkflowMutation(
  client$: NovuCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: WorkflowsWorkflowControllerPatchWorkflowMutationVariables,
  ) => Promise<WorkflowsWorkflowControllerPatchWorkflowMutationData>;
} {
  return {
    mutationKey: mutationKeyWorkflowsWorkflowControllerPatchWorkflow(),
    mutationFn: function workflowsWorkflowControllerPatchWorkflowMutationFn({
      workflowId,
      idempotencyKey,
      options,
    }): Promise<WorkflowsWorkflowControllerPatchWorkflowMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(workflowsWorkflowControllerPatchWorkflow(
        client$,
        workflowId,
        idempotencyKey,
        mergedOptions,
      ));
    },
  };
}
