/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { NovuError } from "../models/errors/novuerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { useNovuContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildWorkflowsStepsRetrieveQuery,
  prefetchWorkflowsStepsRetrieve,
  queryKeyWorkflowsStepsRetrieve,
  WorkflowsStepsRetrieveQueryData,
} from "./workflowsStepsRetrieve.core.js";
export {
  buildWorkflowsStepsRetrieveQuery,
  prefetchWorkflowsStepsRetrieve,
  queryKeyWorkflowsStepsRetrieve,
  type WorkflowsStepsRetrieveQueryData,
};

export type WorkflowsStepsRetrieveQueryError =
  | errors.ErrorDto
  | errors.ValidationErrorDto
  | NovuError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Retrieve workflow step
 *
 * @remarks
 * Retrieves data for a specific step in a workflow
 */
export function useWorkflowsStepsRetrieve(
  workflowId: string,
  stepId: string,
  idempotencyKey?: string | undefined,
  options?: QueryHookOptions<
    WorkflowsStepsRetrieveQueryData,
    WorkflowsStepsRetrieveQueryError
  >,
): UseQueryResult<
  WorkflowsStepsRetrieveQueryData,
  WorkflowsStepsRetrieveQueryError
> {
  const client = useNovuContext();
  return useQuery({
    ...buildWorkflowsStepsRetrieveQuery(
      client,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

/**
 * Retrieve workflow step
 *
 * @remarks
 * Retrieves data for a specific step in a workflow
 */
export function useWorkflowsStepsRetrieveSuspense(
  workflowId: string,
  stepId: string,
  idempotencyKey?: string | undefined,
  options?: SuspenseQueryHookOptions<
    WorkflowsStepsRetrieveQueryData,
    WorkflowsStepsRetrieveQueryError
  >,
): UseSuspenseQueryResult<
  WorkflowsStepsRetrieveQueryData,
  WorkflowsStepsRetrieveQueryError
> {
  const client = useNovuContext();
  return useSuspenseQuery({
    ...buildWorkflowsStepsRetrieveQuery(
      client,
      workflowId,
      stepId,
      idempotencyKey,
      options,
    ),
    ...options,
  });
}

export function setWorkflowsStepsRetrieveData(
  client: QueryClient,
  queryKeyBase: [
    workflowId: string,
    stepId: string,
    parameters: { idempotencyKey?: string | undefined },
  ],
  data: WorkflowsStepsRetrieveQueryData,
): WorkflowsStepsRetrieveQueryData | undefined {
  const key = queryKeyWorkflowsStepsRetrieve(...queryKeyBase);

  return client.setQueryData<WorkflowsStepsRetrieveQueryData>(key, data);
}

export function invalidateWorkflowsStepsRetrieve(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      workflowId: string,
      stepId: string,
      parameters: { idempotencyKey?: string | undefined },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Steps", "retrieve", ...queryKeyBase],
  });
}

export function invalidateAllWorkflowsStepsRetrieve(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@novu/api", "Steps", "retrieve"],
  });
}
