export enum HttpHeaderKeysEnum {
  SIGNATURE = 'x-novu-signature',
  ANONYMOUS = 'x-novu-anonymous',
  EXECUTION_DURATION = 'x-novu-execution-duration',
  SDK_VERSION = 'x-novu-sdk',
  FRAMEWORK = 'x-novu-framework',
  USER_AGENT = 'user-agent',
  CONTENT_TYPE = 'content-type',
  AUTHORIZATION = 'authorization',
  ACCESS_CONTROL_ALLOW_ORIGIN = 'access-control-allow-origin',
  ACCESS_CONTROL_ALLOW_METHODS = 'access-control-allow-methods',
  ACCESS_CONTROL_ALLOW_HEADERS = 'access-control-allow-headers',
  ACCESS_CONTROL_ALLOW_CREDENTIALS = 'access-control-allow-credentials',
  ACCESS_CONTROL_MAX_AGE = 'access-control-max-age',
}
