/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ChannelConnectionsControllerUpdateChannelConnectionRequest = {
  /**
   * The unique identifier of the channel connection
   */
  identifier: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateChannelConnectionRequestDto:
    components.UpdateChannelConnectionRequestDto;
};

export type ChannelConnectionsControllerUpdateChannelConnectionResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetChannelConnectionResponseDto;
};

/** @internal */
export type ChannelConnectionsControllerUpdateChannelConnectionRequest$Outbound =
  {
    identifier: string;
    "idempotency-key"?: string | undefined;
    UpdateChannelConnectionRequestDto:
      components.UpdateChannelConnectionRequestDto$Outbound;
  };

/** @internal */
export const ChannelConnectionsControllerUpdateChannelConnectionRequest$outboundSchema:
  z.ZodType<
    ChannelConnectionsControllerUpdateChannelConnectionRequest$Outbound,
    z.ZodTypeDef,
    ChannelConnectionsControllerUpdateChannelConnectionRequest
  > = z.object({
    identifier: z.string(),
    idempotencyKey: z.string().optional(),
    updateChannelConnectionRequestDto:
      components.UpdateChannelConnectionRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      updateChannelConnectionRequestDto: "UpdateChannelConnectionRequestDto",
    });
  });

export function channelConnectionsControllerUpdateChannelConnectionRequestToJSON(
  channelConnectionsControllerUpdateChannelConnectionRequest:
    ChannelConnectionsControllerUpdateChannelConnectionRequest,
): string {
  return JSON.stringify(
    ChannelConnectionsControllerUpdateChannelConnectionRequest$outboundSchema
      .parse(channelConnectionsControllerUpdateChannelConnectionRequest),
  );
}

/** @internal */
export const ChannelConnectionsControllerUpdateChannelConnectionResponse$inboundSchema:
  z.ZodType<
    ChannelConnectionsControllerUpdateChannelConnectionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.GetChannelConnectionResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function channelConnectionsControllerUpdateChannelConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ChannelConnectionsControllerUpdateChannelConnectionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChannelConnectionsControllerUpdateChannelConnectionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'ChannelConnectionsControllerUpdateChannelConnectionResponse' from JSON`,
  );
}
