/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvironmentsControllerV1DeleteEnvironmentRequest = {
  /**
   * The unique identifier of the environment
   */
  environmentId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type EnvironmentsControllerV1DeleteEnvironmentResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export type EnvironmentsControllerV1DeleteEnvironmentRequest$Outbound = {
  environmentId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const EnvironmentsControllerV1DeleteEnvironmentRequest$outboundSchema:
  z.ZodType<
    EnvironmentsControllerV1DeleteEnvironmentRequest$Outbound,
    z.ZodTypeDef,
    EnvironmentsControllerV1DeleteEnvironmentRequest
  > = z.object({
    environmentId: z.string(),
    idempotencyKey: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  });

export function environmentsControllerV1DeleteEnvironmentRequestToJSON(
  environmentsControllerV1DeleteEnvironmentRequest:
    EnvironmentsControllerV1DeleteEnvironmentRequest,
): string {
  return JSON.stringify(
    EnvironmentsControllerV1DeleteEnvironmentRequest$outboundSchema.parse(
      environmentsControllerV1DeleteEnvironmentRequest,
    ),
  );
}

/** @internal */
export const EnvironmentsControllerV1DeleteEnvironmentResponse$inboundSchema:
  z.ZodType<
    EnvironmentsControllerV1DeleteEnvironmentResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  });

export function environmentsControllerV1DeleteEnvironmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvironmentsControllerV1DeleteEnvironmentResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentsControllerV1DeleteEnvironmentResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvironmentsControllerV1DeleteEnvironmentResponse' from JSON`,
  );
}
