import type {
  ChannelPreference,
  ListNotificationsResponse,
  Notification,
  NotificationFilter,
  NovuOptions,
  PreferencesResponse,
  Subscriber,
  Schedule,
  SubscriptionPreference,
  ListSubscriptionsArgs,
  GetSubscriptionArgs,
  CreateSubscriptionArgs,
  UpdateSubscriptionArgs,
  DeleteSubscriptionArgs,
  TopicSubscription,
} from '@novu/js';

export type {
  ChannelPreference,
  Notification,
  NotificationFilter,
  ListNotificationsResponse as NotificationsResponse,
  NovuOptions,
  PreferencesResponse as PreferenceResponse,
  Subscriber,
  Schedule,
  SubscriptionPreference,
  ListSubscriptionsArgs,
  GetSubscriptionArgs,
  CreateSubscriptionArgs,
  UpdateSubscriptionArgs,
  DeleteSubscriptionArgs,
  TopicSubscription,
};
