import { FrameworkConfig } from '../types/framework';

export const FRAMEWORK_CONFIGS: Record<string, FrameworkConfig> = {
  'Next.js': {
    name: 'Next.js',
    packageName: '@novu/nextjs',
    docsUrl: 'https://docs.novu.co/inbox/nextjs',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'NEXT_PUBLIC_NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  React: {
    name: 'React (Vite)',
    packageName: '@novu/react',
    docsUrl: 'https://docs.novu.co/inbox/react',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'VITE_NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  JavaScript: {
    name: 'JavaScript (Headless)',
    packageName: '@novu/js',
    docsUrl: 'https://docs.novu.co/platform/sdks/javascript',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  Angular: {
    name: 'Angular',
    packageName: '@novu/js',
    docsUrl: 'https://docs.novu.co/inbox/angular',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  Vue: {
    name: 'Vue',
    packageName: '@novu/js',
    docsUrl: 'https://docs.novu.co/inbox/vue',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'VITE_NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  Remix: {
    name: 'Remix',
    packageName: '@novu/react',
    docsUrl: 'https://docs.novu.co/inbox/remix',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
  Native: {
    name: 'React Native',
    packageName: '@novu/react-native',
    docsUrl: 'https://docs.novu.co/inbox/react-native',
    hasNativeSupport: true,
    requiresEnvVars: true,
    envVarName: 'NOVU_APP_IDENTIFIER',
    regionSupport: true,
    hmacSupport: true,
  },
};
