FROM node:22.22-alpine3.23 AS builder
RUN apk add --no-cache g++ make py3-pip bash
ENV NX_DAEMON=false

WORKDIR /usr/src/app

RUN npm --no-update-notifier --no-fund --global install pnpm@10.33.0

COPY .npmrc .
COPY package.json .

COPY apps/dashboard ./apps/dashboard
COPY libs ./libs
COPY packages ./packages
COPY enterprise ./enterprise
COPY tsconfig.json .

COPY nx.json .
COPY pnpm-workspace.yaml .
COPY pnpm-lock.yaml .

RUN --mount=type=cache,id=pnpm-store-dashboard,target=/root/.pnpm-store\
  pnpm install --frozen-lockfile --unsafe-perm

ARG VITE_EE_AUTH_PROVIDER
ARG VITE_SELF_HOSTED=true
ARG VITE_NOVU_ENTERPRISE=false

ENV VITE_EE_AUTH_PROVIDER=${VITE_EE_AUTH_PROVIDER}
ENV VITE_SELF_HOSTED=${VITE_SELF_HOSTED}
ENV VITE_NOVU_ENTERPRISE=${VITE_NOVU_ENTERPRISE}

RUN CI='' pnpm build:dashboard --skip-nx-cache

FROM node:22.22-alpine3.23 AS prod

ENV CI=true

RUN apk upgrade --no-cache && \
    # Manually upgrade packages from edge/main to patch CVEs
    # until fixes are backported to the alpine3.23 stable repo
    apk add --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/edge/main --upgrade libcrypto3 libssl3 musl musl-utils && \
    npm --no-update-notifier --no-fund --global install http-server && \
    rm -rf /usr/local/lib/node_modules/npm /usr/local/bin/npm /usr/local/bin/npx

USER 1000
WORKDIR /app

COPY --chown=1000:1000 --from=builder /usr/src/app/apps/dashboard/dist /app/dist
COPY --chown=1000:1000 --from=builder /usr/src/app/apps/dashboard/package.json /app/package.json
COPY --chown=1000:1000 --from=builder /usr/src/app/apps/dashboard/docker-entrypoint.sh /app/docker-entrypoint.sh

RUN chmod +x /app/docker-entrypoint.sh
ENTRYPOINT [ "/app/docker-entrypoint.sh" ]
EXPOSE 4000
CMD [ "http-server", "dist", "-p", "4000", "-d", "false", "--proxy", "http://localhost:4000?" ]