import { ROUTES } from './routes.enum';

export const UNPROTECTED_ROUTES: ROUTES[] = [
  ROUTES.AUTH_SIGNUP,
  ROUTES.AUTH_LOGIN,
  ROUTES.AUTH_RESET_REQUEST,
  ROUTES.AUTH_RESET_TOKEN,
  ROUTES.AUTH_INVITATION_TOKEN,
  ROUTES.AUTH_APPLICATION,
];

export const UNPROTECTED_ROUTES_SET: Set<string> = new Set(UNPROTECTED_ROUTES);
