name: Setup Novu Monorepo

description: Sets up the whole monorepo and install dependencies

inputs:
  slim:
    description: 'Should only install dependencies and checkout code'
    required: false
    default: 'false'
  submodules:
    description: 'Should link submodules'
    required: false
    default: 'false'
outputs:
  cypress_cache_hit:
    description: 'Did cypress use binary cache'
    value: ${{ inputs.cypress_version != '' && steps.cache-cypress-binary-version.outputs.cache-hit || steps.cache-cypress-binary.outputs.cache-hit}}

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      with:
        version: 11.0.9

    - uses: useblacksmith/setup-node@65c6ca86fdeb0ab3d85e78f57e4f6a7e4780b391 # v5
      name: ⚙️ Setup Node Version
      with:
        node-version: '22.22.1'
        cache: 'pnpm'

    - name: 💵 Start Redis
      if: ${{ inputs.slim == 'false' }}
      uses: supercharge/redis-github-action@f63fe516254d0af5df91755a4488274c2e71e38c # 1.5.0

    - name: 📚 Start MongoDB
      if: ${{ inputs.slim == 'false' }}
      uses: supercharge/mongodb-github-action@5a87bd81f88e2a8b195f8b7b656f5cda1350815a # 1.11.0
      with:
        mongodb-version: 8.0

    - name: 🔍 Start ClickHouse
      if: ${{ inputs.slim == 'false' }}
      uses: praneeth527/clickhouse-server-action@f09502165f8075d2a11c4fbc9e93ccea9b2a821b # v1.0.0
      env:
        CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      with:
        tag: '24.3-alpine'

    - name: 🛟 Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Install wait-on plugin
      shell: bash
      run: pnpm i -g wait-on
