/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const QueryParamStatuses = {
  Processing: "processing",
  Completed: "completed",
  Error: "error",
} as const;
export type QueryParamStatuses = ClosedEnum<typeof QueryParamStatuses>;

export const QueryParamSeverity = {
  High: "high",
  Medium: "medium",
  Low: "low",
  None: "none",
} as const;
export type QueryParamSeverity = ClosedEnum<typeof QueryParamSeverity>;

export type ActivityControllerGetWorkflowRunsRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  workflowIds?: Array<string> | undefined;
  subscriberIds?: Array<string> | undefined;
  transactionIds?: Array<string> | undefined;
  statuses?: Array<QueryParamStatuses> | undefined;
  channels?: Array<string> | undefined;
  topicKey?: string | undefined;
  subscriptionId?: string | undefined;
  createdGte?: string | undefined;
  createdLte?: string | undefined;
  severity?: Array<QueryParamSeverity> | undefined;
  contextKeys?: Array<string> | undefined;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export const QueryParamStatuses$outboundSchema: z.ZodNativeEnum<
  typeof QueryParamStatuses
> = z.nativeEnum(QueryParamStatuses);

/** @internal */
export const QueryParamSeverity$outboundSchema: z.ZodNativeEnum<
  typeof QueryParamSeverity
> = z.nativeEnum(QueryParamSeverity);

/** @internal */
export type ActivityControllerGetWorkflowRunsRequest$Outbound = {
  limit: number;
  cursor?: string | undefined;
  workflowIds?: Array<string> | undefined;
  subscriberIds?: Array<string> | undefined;
  transactionIds?: Array<string> | undefined;
  statuses?: Array<string> | undefined;
  channels?: Array<string> | undefined;
  topicKey?: string | undefined;
  subscriptionId?: string | undefined;
  createdGte?: string | undefined;
  createdLte?: string | undefined;
  severity?: Array<string> | undefined;
  contextKeys?: Array<string> | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const ActivityControllerGetWorkflowRunsRequest$outboundSchema: z.ZodType<
  ActivityControllerGetWorkflowRunsRequest$Outbound,
  z.ZodTypeDef,
  ActivityControllerGetWorkflowRunsRequest
> = z.object({
  limit: z.number().default(10),
  cursor: z.string().optional(),
  workflowIds: z.array(z.string()).optional(),
  subscriberIds: z.array(z.string()).optional(),
  transactionIds: z.array(z.string()).optional(),
  statuses: z.array(QueryParamStatuses$outboundSchema).optional(),
  channels: z.array(z.string()).optional(),
  topicKey: z.string().optional(),
  subscriptionId: z.string().optional(),
  createdGte: z.string().optional(),
  createdLte: z.string().optional(),
  severity: z.array(QueryParamSeverity$outboundSchema).optional(),
  contextKeys: z.array(z.string()).optional(),
  idempotencyKey: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
  });
});

export function activityControllerGetWorkflowRunsRequestToJSON(
  activityControllerGetWorkflowRunsRequest:
    ActivityControllerGetWorkflowRunsRequest,
): string {
  return JSON.stringify(
    ActivityControllerGetWorkflowRunsRequest$outboundSchema.parse(
      activityControllerGetWorkflowRunsRequest,
    ),
  );
}
