/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AgentsControllerCreateAgentRequest = {
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  createAgentRequestDto: components.CreateAgentRequestDto;
};

export type AgentsControllerCreateAgentResponse = {
  headers: { [k: string]: Array<string> };
  result: components.AgentResponseDto;
};

/** @internal */
export type AgentsControllerCreateAgentRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  CreateAgentRequestDto: components.CreateAgentRequestDto$Outbound;
};

/** @internal */
export const AgentsControllerCreateAgentRequest$outboundSchema: z.ZodType<
  AgentsControllerCreateAgentRequest$Outbound,
  z.ZodTypeDef,
  AgentsControllerCreateAgentRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  createAgentRequestDto: components.CreateAgentRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    createAgentRequestDto: "CreateAgentRequestDto",
  });
});

export function agentsControllerCreateAgentRequestToJSON(
  agentsControllerCreateAgentRequest: AgentsControllerCreateAgentRequest,
): string {
  return JSON.stringify(
    AgentsControllerCreateAgentRequest$outboundSchema.parse(
      agentsControllerCreateAgentRequest,
    ),
  );
}

/** @internal */
export const AgentsControllerCreateAgentResponse$inboundSchema: z.ZodType<
  AgentsControllerCreateAgentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.AgentResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function agentsControllerCreateAgentResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentsControllerCreateAgentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentsControllerCreateAgentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentsControllerCreateAgentResponse' from JSON`,
  );
}
