/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AgentReplyControllerHandleAgentReplyHandlerRequest = {
  agentId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  agentReplyPayloadDto: components.AgentReplyPayloadDto;
};

export type AgentReplyControllerHandleAgentReplyHandlerResponseBody = {};

export type AgentReplyControllerHandleAgentReplyHandlerResponse = {
  headers: { [k: string]: Array<string> };
  result: AgentReplyControllerHandleAgentReplyHandlerResponseBody;
};

/** @internal */
export type AgentReplyControllerHandleAgentReplyHandlerRequest$Outbound = {
  agentId: string;
  "idempotency-key"?: string | undefined;
  AgentReplyPayloadDto: components.AgentReplyPayloadDto$Outbound;
};

/** @internal */
export const AgentReplyControllerHandleAgentReplyHandlerRequest$outboundSchema:
  z.ZodType<
    AgentReplyControllerHandleAgentReplyHandlerRequest$Outbound,
    z.ZodTypeDef,
    AgentReplyControllerHandleAgentReplyHandlerRequest
  > = z.object({
    agentId: z.string(),
    idempotencyKey: z.string().optional(),
    agentReplyPayloadDto: components.AgentReplyPayloadDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      agentReplyPayloadDto: "AgentReplyPayloadDto",
    });
  });

export function agentReplyControllerHandleAgentReplyHandlerRequestToJSON(
  agentReplyControllerHandleAgentReplyHandlerRequest:
    AgentReplyControllerHandleAgentReplyHandlerRequest,
): string {
  return JSON.stringify(
    AgentReplyControllerHandleAgentReplyHandlerRequest$outboundSchema.parse(
      agentReplyControllerHandleAgentReplyHandlerRequest,
    ),
  );
}

/** @internal */
export const AgentReplyControllerHandleAgentReplyHandlerResponseBody$inboundSchema:
  z.ZodType<
    AgentReplyControllerHandleAgentReplyHandlerResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({});

export function agentReplyControllerHandleAgentReplyHandlerResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  AgentReplyControllerHandleAgentReplyHandlerResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AgentReplyControllerHandleAgentReplyHandlerResponseBody$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'AgentReplyControllerHandleAgentReplyHandlerResponseBody' from JSON`,
  );
}

/** @internal */
export const AgentReplyControllerHandleAgentReplyHandlerResponse$inboundSchema:
  z.ZodType<
    AgentReplyControllerHandleAgentReplyHandlerResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: z.lazy(() =>
      AgentReplyControllerHandleAgentReplyHandlerResponseBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function agentReplyControllerHandleAgentReplyHandlerResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AgentReplyControllerHandleAgentReplyHandlerResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AgentReplyControllerHandleAgentReplyHandlerResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AgentReplyControllerHandleAgentReplyHandlerResponse' from JSON`,
  );
}
