/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AgentsControllerUpdateAgentBridgeRequest = {
  identifier: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateAgentBridgeRequestDto: components.UpdateAgentBridgeRequestDto;
};

export type AgentsControllerUpdateAgentBridgeResponse = {
  headers: { [k: string]: Array<string> };
  result: components.AgentResponseDto;
};

/** @internal */
export type AgentsControllerUpdateAgentBridgeRequest$Outbound = {
  identifier: string;
  "idempotency-key"?: string | undefined;
  UpdateAgentBridgeRequestDto: components.UpdateAgentBridgeRequestDto$Outbound;
};

/** @internal */
export const AgentsControllerUpdateAgentBridgeRequest$outboundSchema: z.ZodType<
  AgentsControllerUpdateAgentBridgeRequest$Outbound,
  z.ZodTypeDef,
  AgentsControllerUpdateAgentBridgeRequest
> = z.object({
  identifier: z.string(),
  idempotencyKey: z.string().optional(),
  updateAgentBridgeRequestDto:
    components.UpdateAgentBridgeRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    updateAgentBridgeRequestDto: "UpdateAgentBridgeRequestDto",
  });
});

export function agentsControllerUpdateAgentBridgeRequestToJSON(
  agentsControllerUpdateAgentBridgeRequest:
    AgentsControllerUpdateAgentBridgeRequest,
): string {
  return JSON.stringify(
    AgentsControllerUpdateAgentBridgeRequest$outboundSchema.parse(
      agentsControllerUpdateAgentBridgeRequest,
    ),
  );
}

/** @internal */
export const AgentsControllerUpdateAgentBridgeResponse$inboundSchema: z.ZodType<
  AgentsControllerUpdateAgentBridgeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.AgentResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function agentsControllerUpdateAgentBridgeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AgentsControllerUpdateAgentBridgeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AgentsControllerUpdateAgentBridgeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AgentsControllerUpdateAgentBridgeResponse' from JSON`,
  );
}
