/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ContextsControllerCreateContextRequest = {
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  createContextRequestDto: components.CreateContextRequestDto;
};

export type ContextsControllerCreateContextResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GetContextResponseDto;
};

/** @internal */
export type ContextsControllerCreateContextRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  CreateContextRequestDto: components.CreateContextRequestDto$Outbound;
};

/** @internal */
export const ContextsControllerCreateContextRequest$outboundSchema: z.ZodType<
  ContextsControllerCreateContextRequest$Outbound,
  z.ZodTypeDef,
  ContextsControllerCreateContextRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  createContextRequestDto: components.CreateContextRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    createContextRequestDto: "CreateContextRequestDto",
  });
});

export function contextsControllerCreateContextRequestToJSON(
  contextsControllerCreateContextRequest:
    ContextsControllerCreateContextRequest,
): string {
  return JSON.stringify(
    ContextsControllerCreateContextRequest$outboundSchema.parse(
      contextsControllerCreateContextRequest,
    ),
  );
}

/** @internal */
export const ContextsControllerCreateContextResponse$inboundSchema: z.ZodType<
  ContextsControllerCreateContextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.GetContextResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function contextsControllerCreateContextResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  ContextsControllerCreateContextResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ContextsControllerCreateContextResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ContextsControllerCreateContextResponse' from JSON`,
  );
}
