/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvironmentsControllerV1UpdateMyEnvironmentRequest = {
  /**
   * The unique identifier of the environment
   */
  environmentId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateEnvironmentRequestDto: components.UpdateEnvironmentRequestDto;
};

export type EnvironmentsControllerV1UpdateMyEnvironmentResponse = {
  headers: { [k: string]: Array<string> };
  result: components.EnvironmentResponseDto;
};

/** @internal */
export type EnvironmentsControllerV1UpdateMyEnvironmentRequest$Outbound = {
  environmentId: string;
  "idempotency-key"?: string | undefined;
  UpdateEnvironmentRequestDto: components.UpdateEnvironmentRequestDto$Outbound;
};

/** @internal */
export const EnvironmentsControllerV1UpdateMyEnvironmentRequest$outboundSchema:
  z.ZodType<
    EnvironmentsControllerV1UpdateMyEnvironmentRequest$Outbound,
    z.ZodTypeDef,
    EnvironmentsControllerV1UpdateMyEnvironmentRequest
  > = z.object({
    environmentId: z.string(),
    idempotencyKey: z.string().optional(),
    updateEnvironmentRequestDto:
      components.UpdateEnvironmentRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      updateEnvironmentRequestDto: "UpdateEnvironmentRequestDto",
    });
  });

export function environmentsControllerV1UpdateMyEnvironmentRequestToJSON(
  environmentsControllerV1UpdateMyEnvironmentRequest:
    EnvironmentsControllerV1UpdateMyEnvironmentRequest,
): string {
  return JSON.stringify(
    EnvironmentsControllerV1UpdateMyEnvironmentRequest$outboundSchema.parse(
      environmentsControllerV1UpdateMyEnvironmentRequest,
    ),
  );
}

/** @internal */
export const EnvironmentsControllerV1UpdateMyEnvironmentResponse$inboundSchema:
  z.ZodType<
    EnvironmentsControllerV1UpdateMyEnvironmentResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.EnvironmentResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function environmentsControllerV1UpdateMyEnvironmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvironmentsControllerV1UpdateMyEnvironmentResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentsControllerV1UpdateMyEnvironmentResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvironmentsControllerV1UpdateMyEnvironmentResponse' from JSON`,
  );
}
