/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvironmentVariablesControllerUpdateEnvironmentVariableRequest = {
  /**
   * The unique key of the environment variable (e.g. BASE_URL)
   */
  variableKey: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateEnvironmentVariableRequestDto:
    components.UpdateEnvironmentVariableRequestDto;
};

export type EnvironmentVariablesControllerUpdateEnvironmentVariableResponse = {
  headers: { [k: string]: Array<string> };
  result: components.EnvironmentVariableResponseDto;
};

/** @internal */
export type EnvironmentVariablesControllerUpdateEnvironmentVariableRequest$Outbound =
  {
    variableKey: string;
    "idempotency-key"?: string | undefined;
    UpdateEnvironmentVariableRequestDto:
      components.UpdateEnvironmentVariableRequestDto$Outbound;
  };

/** @internal */
export const EnvironmentVariablesControllerUpdateEnvironmentVariableRequest$outboundSchema:
  z.ZodType<
    EnvironmentVariablesControllerUpdateEnvironmentVariableRequest$Outbound,
    z.ZodTypeDef,
    EnvironmentVariablesControllerUpdateEnvironmentVariableRequest
  > = z.object({
    variableKey: z.string(),
    idempotencyKey: z.string().optional(),
    updateEnvironmentVariableRequestDto:
      components.UpdateEnvironmentVariableRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      updateEnvironmentVariableRequestDto:
        "UpdateEnvironmentVariableRequestDto",
    });
  });

export function environmentVariablesControllerUpdateEnvironmentVariableRequestToJSON(
  environmentVariablesControllerUpdateEnvironmentVariableRequest:
    EnvironmentVariablesControllerUpdateEnvironmentVariableRequest,
): string {
  return JSON.stringify(
    EnvironmentVariablesControllerUpdateEnvironmentVariableRequest$outboundSchema
      .parse(environmentVariablesControllerUpdateEnvironmentVariableRequest),
  );
}

/** @internal */
export const EnvironmentVariablesControllerUpdateEnvironmentVariableResponse$inboundSchema:
  z.ZodType<
    EnvironmentVariablesControllerUpdateEnvironmentVariableResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.EnvironmentVariableResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function environmentVariablesControllerUpdateEnvironmentVariableResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvironmentVariablesControllerUpdateEnvironmentVariableResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvironmentVariablesControllerUpdateEnvironmentVariableResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentVariablesControllerUpdateEnvironmentVariableResponse' from JSON`,
  );
}
