/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventsControllerTriggerBulkRequest = {
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  bulkTriggerEventDto: components.BulkTriggerEventDto;
};

export type EventsControllerTriggerBulkResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<components.TriggerEventResponseDto>;
};

/** @internal */
export type EventsControllerTriggerBulkRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  BulkTriggerEventDto: components.BulkTriggerEventDto$Outbound;
};

/** @internal */
export const EventsControllerTriggerBulkRequest$outboundSchema: z.ZodType<
  EventsControllerTriggerBulkRequest$Outbound,
  z.ZodTypeDef,
  EventsControllerTriggerBulkRequest
> = z.object({
  idempotencyKey: z.string().optional(),
  bulkTriggerEventDto: components.BulkTriggerEventDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    bulkTriggerEventDto: "BulkTriggerEventDto",
  });
});

export function eventsControllerTriggerBulkRequestToJSON(
  eventsControllerTriggerBulkRequest: EventsControllerTriggerBulkRequest,
): string {
  return JSON.stringify(
    EventsControllerTriggerBulkRequest$outboundSchema.parse(
      eventsControllerTriggerBulkRequest,
    ),
  );
}

/** @internal */
export const EventsControllerTriggerBulkResponse$inboundSchema: z.ZodType<
  EventsControllerTriggerBulkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.array(components.TriggerEventResponseDto$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function eventsControllerTriggerBulkResponseFromJSON(
  jsonString: string,
): SafeParseResult<EventsControllerTriggerBulkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EventsControllerTriggerBulkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventsControllerTriggerBulkResponse' from JSON`,
  );
}
