/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The channel of the message to be deleted
 */
export const Channel = {
  InApp: "in_app",
  Email: "email",
  Sms: "sms",
  Chat: "chat",
  Push: "push",
} as const;
/**
 * The channel of the message to be deleted
 */
export type Channel = ClosedEnum<typeof Channel>;

export type MessagesControllerDeleteMessagesByTransactionIdRequest = {
  /**
   * The channel of the message to be deleted
   */
  channel?: Channel | undefined;
  transactionId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type MessagesControllerDeleteMessagesByTransactionIdResponse = {
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const Channel$outboundSchema: z.ZodNativeEnum<typeof Channel> = z
  .nativeEnum(Channel);

/** @internal */
export type MessagesControllerDeleteMessagesByTransactionIdRequest$Outbound = {
  channel?: string | undefined;
  transactionId: string;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const MessagesControllerDeleteMessagesByTransactionIdRequest$outboundSchema:
  z.ZodType<
    MessagesControllerDeleteMessagesByTransactionIdRequest$Outbound,
    z.ZodTypeDef,
    MessagesControllerDeleteMessagesByTransactionIdRequest
  > = z.object({
    channel: Channel$outboundSchema.optional(),
    transactionId: z.string(),
    idempotencyKey: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  });

export function messagesControllerDeleteMessagesByTransactionIdRequestToJSON(
  messagesControllerDeleteMessagesByTransactionIdRequest:
    MessagesControllerDeleteMessagesByTransactionIdRequest,
): string {
  return JSON.stringify(
    MessagesControllerDeleteMessagesByTransactionIdRequest$outboundSchema.parse(
      messagesControllerDeleteMessagesByTransactionIdRequest,
    ),
  );
}

/** @internal */
export const MessagesControllerDeleteMessagesByTransactionIdResponse$inboundSchema:
  z.ZodType<
    MessagesControllerDeleteMessagesByTransactionIdResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
    });
  });

export function messagesControllerDeleteMessagesByTransactionIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  MessagesControllerDeleteMessagesByTransactionIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      MessagesControllerDeleteMessagesByTransactionIdResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'MessagesControllerDeleteMessagesByTransactionIdResponse' from JSON`,
  );
}
