/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribersV1ControllerUpdateSubscriberRequest = {
  subscriberId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  updateSubscriberRequestDto: components.UpdateSubscriberRequestDto;
};

export type SubscribersV1ControllerUpdateSubscriberResponse = {
  headers: { [k: string]: Array<string> };
  result: components.SubscriberResponseDto;
};

/** @internal */
export const SubscribersV1ControllerUpdateSubscriberRequest$inboundSchema:
  z.ZodType<
    SubscribersV1ControllerUpdateSubscriberRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    subscriberId: z.string(),
    "idempotency-key": z.string().optional(),
    UpdateSubscriberRequestDto:
      components.UpdateSubscriberRequestDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "idempotency-key": "idempotencyKey",
      "UpdateSubscriberRequestDto": "updateSubscriberRequestDto",
    });
  });

/** @internal */
export type SubscribersV1ControllerUpdateSubscriberRequest$Outbound = {
  subscriberId: string;
  "idempotency-key"?: string | undefined;
  UpdateSubscriberRequestDto: components.UpdateSubscriberRequestDto$Outbound;
};

/** @internal */
export const SubscribersV1ControllerUpdateSubscriberRequest$outboundSchema:
  z.ZodType<
    SubscribersV1ControllerUpdateSubscriberRequest$Outbound,
    z.ZodTypeDef,
    SubscribersV1ControllerUpdateSubscriberRequest
  > = z.object({
    subscriberId: z.string(),
    idempotencyKey: z.string().optional(),
    updateSubscriberRequestDto:
      components.UpdateSubscriberRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      updateSubscriberRequestDto: "UpdateSubscriberRequestDto",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribersV1ControllerUpdateSubscriberRequest$ {
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberRequest$inboundSchema` instead. */
  export const inboundSchema =
    SubscribersV1ControllerUpdateSubscriberRequest$inboundSchema;
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberRequest$outboundSchema` instead. */
  export const outboundSchema =
    SubscribersV1ControllerUpdateSubscriberRequest$outboundSchema;
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberRequest$Outbound` instead. */
  export type Outbound =
    SubscribersV1ControllerUpdateSubscriberRequest$Outbound;
}

export function subscribersV1ControllerUpdateSubscriberRequestToJSON(
  subscribersV1ControllerUpdateSubscriberRequest:
    SubscribersV1ControllerUpdateSubscriberRequest,
): string {
  return JSON.stringify(
    SubscribersV1ControllerUpdateSubscriberRequest$outboundSchema.parse(
      subscribersV1ControllerUpdateSubscriberRequest,
    ),
  );
}

export function subscribersV1ControllerUpdateSubscriberRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersV1ControllerUpdateSubscriberRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersV1ControllerUpdateSubscriberRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersV1ControllerUpdateSubscriberRequest' from JSON`,
  );
}

/** @internal */
export const SubscribersV1ControllerUpdateSubscriberResponse$inboundSchema:
  z.ZodType<
    SubscribersV1ControllerUpdateSubscriberResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result: components.SubscriberResponseDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type SubscribersV1ControllerUpdateSubscriberResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: components.SubscriberResponseDto$Outbound;
};

/** @internal */
export const SubscribersV1ControllerUpdateSubscriberResponse$outboundSchema:
  z.ZodType<
    SubscribersV1ControllerUpdateSubscriberResponse$Outbound,
    z.ZodTypeDef,
    SubscribersV1ControllerUpdateSubscriberResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result: components.SubscriberResponseDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubscribersV1ControllerUpdateSubscriberResponse$ {
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberResponse$inboundSchema` instead. */
  export const inboundSchema =
    SubscribersV1ControllerUpdateSubscriberResponse$inboundSchema;
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberResponse$outboundSchema` instead. */
  export const outboundSchema =
    SubscribersV1ControllerUpdateSubscriberResponse$outboundSchema;
  /** @deprecated use `SubscribersV1ControllerUpdateSubscriberResponse$Outbound` instead. */
  export type Outbound =
    SubscribersV1ControllerUpdateSubscriberResponse$Outbound;
}

export function subscribersV1ControllerUpdateSubscriberResponseToJSON(
  subscribersV1ControllerUpdateSubscriberResponse:
    SubscribersV1ControllerUpdateSubscriberResponse,
): string {
  return JSON.stringify(
    SubscribersV1ControllerUpdateSubscriberResponse$outboundSchema.parse(
      subscribersV1ControllerUpdateSubscriberResponse,
    ),
  );
}

export function subscribersV1ControllerUpdateSubscriberResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersV1ControllerUpdateSubscriberResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersV1ControllerUpdateSubscriberResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersV1ControllerUpdateSubscriberResponse' from JSON`,
  );
}
