/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubscribersControllerUnsnoozeNotificationRequest = {
  /**
   * The identifier of the subscriber
   */
  subscriberId: string;
  /**
   * The identifier of the notification
   */
  notificationId: string;
  /**
   * Context keys for filtering
   */
  contextKeys?: Array<string> | undefined;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
};

export type SubscribersControllerUnsnoozeNotificationResponse = {
  headers: { [k: string]: Array<string> };
  result: components.InboxNotificationDto;
};

/** @internal */
export type SubscribersControllerUnsnoozeNotificationRequest$Outbound = {
  subscriberId: string;
  notificationId: string;
  contextKeys?: Array<string> | undefined;
  "idempotency-key"?: string | undefined;
};

/** @internal */
export const SubscribersControllerUnsnoozeNotificationRequest$outboundSchema:
  z.ZodType<
    SubscribersControllerUnsnoozeNotificationRequest$Outbound,
    z.ZodTypeDef,
    SubscribersControllerUnsnoozeNotificationRequest
  > = z.object({
    subscriberId: z.string(),
    notificationId: z.string(),
    contextKeys: z.array(z.string()).optional(),
    idempotencyKey: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
    });
  });

export function subscribersControllerUnsnoozeNotificationRequestToJSON(
  subscribersControllerUnsnoozeNotificationRequest:
    SubscribersControllerUnsnoozeNotificationRequest,
): string {
  return JSON.stringify(
    SubscribersControllerUnsnoozeNotificationRequest$outboundSchema.parse(
      subscribersControllerUnsnoozeNotificationRequest,
    ),
  );
}

/** @internal */
export const SubscribersControllerUnsnoozeNotificationResponse$inboundSchema:
  z.ZodType<
    SubscribersControllerUnsnoozeNotificationResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())).default({}),
    Result: components.InboxNotificationDto$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

export function subscribersControllerUnsnoozeNotificationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  SubscribersControllerUnsnoozeNotificationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      SubscribersControllerUnsnoozeNotificationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'SubscribersControllerUnsnoozeNotificationResponse' from JSON`,
  );
}
