/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type TranslationControllerCreateTranslationEndpointRequest = {
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  createTranslationRequestDto: components.CreateTranslationRequestDto;
};

/** @internal */
export type TranslationControllerCreateTranslationEndpointRequest$Outbound = {
  "idempotency-key"?: string | undefined;
  CreateTranslationRequestDto: components.CreateTranslationRequestDto$Outbound;
};

/** @internal */
export const TranslationControllerCreateTranslationEndpointRequest$outboundSchema:
  z.ZodType<
    TranslationControllerCreateTranslationEndpointRequest$Outbound,
    z.ZodTypeDef,
    TranslationControllerCreateTranslationEndpointRequest
  > = z.object({
    idempotencyKey: z.string().optional(),
    createTranslationRequestDto:
      components.CreateTranslationRequestDto$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency-key",
      createTranslationRequestDto: "CreateTranslationRequestDto",
    });
  });

export function translationControllerCreateTranslationEndpointRequestToJSON(
  translationControllerCreateTranslationEndpointRequest:
    TranslationControllerCreateTranslationEndpointRequest,
): string {
  return JSON.stringify(
    TranslationControllerCreateTranslationEndpointRequest$outboundSchema.parse(
      translationControllerCreateTranslationEndpointRequest,
    ),
  );
}
