/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowControllerGeneratePreviewRequest = {
  workflowId: string;
  stepId: string;
  /**
   * A header for idempotency purposes
   */
  idempotencyKey?: string | undefined;
  /**
   * Preview generation details
   */
  generatePreviewRequestDto: components.GeneratePreviewRequestDto;
};

export type WorkflowControllerGeneratePreviewResponse = {
  headers: { [k: string]: Array<string> };
  result: components.GeneratePreviewResponseDto;
};

/** @internal */
export type WorkflowControllerGeneratePreviewRequest$Outbound = {
  workflowId: string;
  stepId: string;
  "idempotency-key"?: string | undefined;
  GeneratePreviewRequestDto: components.GeneratePreviewRequestDto$Outbound;
};

/** @internal */
export const WorkflowControllerGeneratePreviewRequest$outboundSchema: z.ZodType<
  WorkflowControllerGeneratePreviewRequest$Outbound,
  z.ZodTypeDef,
  WorkflowControllerGeneratePreviewRequest
> = z.object({
  workflowId: z.string(),
  stepId: z.string(),
  idempotencyKey: z.string().optional(),
  generatePreviewRequestDto:
    components.GeneratePreviewRequestDto$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    idempotencyKey: "idempotency-key",
    generatePreviewRequestDto: "GeneratePreviewRequestDto",
  });
});

export function workflowControllerGeneratePreviewRequestToJSON(
  workflowControllerGeneratePreviewRequest:
    WorkflowControllerGeneratePreviewRequest,
): string {
  return JSON.stringify(
    WorkflowControllerGeneratePreviewRequest$outboundSchema.parse(
      workflowControllerGeneratePreviewRequest,
    ),
  );
}

/** @internal */
export const WorkflowControllerGeneratePreviewResponse$inboundSchema: z.ZodType<
  WorkflowControllerGeneratePreviewResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: components.GeneratePreviewResponseDto$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function workflowControllerGeneratePreviewResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  WorkflowControllerGeneratePreviewResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      WorkflowControllerGeneratePreviewResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'WorkflowControllerGeneratePreviewResponse' from JSON`,
  );
}
