/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Source of the execution detail
 */
export const ExecutionDetailsSourceEnum = {
  Credentials: "Credentials",
  Internal: "Internal",
  Payload: "Payload",
  Webhook: "Webhook",
} as const;
/**
 * Source of the execution detail
 */
export type ExecutionDetailsSourceEnum = ClosedEnum<
  typeof ExecutionDetailsSourceEnum
>;

/** @internal */
export const ExecutionDetailsSourceEnum$inboundSchema: z.ZodNativeEnum<
  typeof ExecutionDetailsSourceEnum
> = z.nativeEnum(ExecutionDetailsSourceEnum);
