/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GroupPreferenceFilterDetailsDto = {
  /**
   * List of workflow identifiers
   */
  workflowIds?: Array<string> | undefined;
  /**
   * List of tags
   */
  tags?: Array<string> | undefined;
};

/** @internal */
export type GroupPreferenceFilterDetailsDto$Outbound = {
  workflowIds?: Array<string> | undefined;
  tags?: Array<string> | undefined;
};

/** @internal */
export const GroupPreferenceFilterDetailsDto$outboundSchema: z.ZodType<
  GroupPreferenceFilterDetailsDto$Outbound,
  z.ZodTypeDef,
  GroupPreferenceFilterDetailsDto
> = z.object({
  workflowIds: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
});

export function groupPreferenceFilterDetailsDtoToJSON(
  groupPreferenceFilterDetailsDto: GroupPreferenceFilterDetailsDto,
): string {
  return JSON.stringify(
    GroupPreferenceFilterDetailsDto$outboundSchema.parse(
      groupPreferenceFilterDetailsDto,
    ),
  );
}
