/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const TimedConfigWeekDays = {
  Monday: "monday",
  Tuesday: "tuesday",
  Wednesday: "wednesday",
  Thursday: "thursday",
  Friday: "friday",
  Saturday: "saturday",
  Sunday: "sunday",
} as const;
export type TimedConfigWeekDays = ClosedEnum<typeof TimedConfigWeekDays>;

export const Ordinal = {
  One: "1",
  Two: "2",
  Three: "3",
  Four: "4",
  Five: "5",
  Last: "last",
} as const;
export type Ordinal = ClosedEnum<typeof Ordinal>;

export const OrdinalValue = {
  Day: "day",
  Weekday: "weekday",
  Weekend: "weekend",
  Sunday: "sunday",
  Monday: "monday",
  Tuesday: "tuesday",
  Wednesday: "wednesday",
  Thursday: "thursday",
  Friday: "friday",
  Saturday: "saturday",
} as const;
export type OrdinalValue = ClosedEnum<typeof OrdinalValue>;

export const MonthlyType = {
  Each: "each",
  On: "on",
} as const;
export type MonthlyType = ClosedEnum<typeof MonthlyType>;

export type TimedConfig = {
  atTime?: string | undefined;
  weekDays?: Array<TimedConfigWeekDays> | undefined;
  monthDays?: Array<string> | undefined;
  ordinal?: Ordinal | undefined;
  ordinalValue?: OrdinalValue | undefined;
  monthlyType?: MonthlyType | undefined;
};

/** @internal */
export const TimedConfigWeekDays$inboundSchema: z.ZodNativeEnum<
  typeof TimedConfigWeekDays
> = z.nativeEnum(TimedConfigWeekDays);

/** @internal */
export const Ordinal$inboundSchema: z.ZodNativeEnum<typeof Ordinal> = z
  .nativeEnum(Ordinal);

/** @internal */
export const OrdinalValue$inboundSchema: z.ZodNativeEnum<typeof OrdinalValue> =
  z.nativeEnum(OrdinalValue);

/** @internal */
export const MonthlyType$inboundSchema: z.ZodNativeEnum<typeof MonthlyType> = z
  .nativeEnum(MonthlyType);

/** @internal */
export const TimedConfig$inboundSchema: z.ZodType<
  TimedConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  atTime: z.string().optional(),
  weekDays: z.array(TimedConfigWeekDays$inboundSchema).optional(),
  monthDays: z.array(z.string()).optional(),
  ordinal: Ordinal$inboundSchema.optional(),
  ordinalValue: OrdinalValue$inboundSchema.optional(),
  monthlyType: MonthlyType$inboundSchema.optional(),
});

export function timedConfigFromJSON(
  jsonString: string,
): SafeParseResult<TimedConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimedConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimedConfig' from JSON`,
  );
}
