/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type WorkflowInfoDto = {
  /**
   * The name of the workflow
   */
  name: string;
  /**
   * The unique identifier of the workflow
   */
  workflowId: string;
};

/** @internal */
export const WorkflowInfoDto$inboundSchema: z.ZodType<
  WorkflowInfoDto,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  workflowId: z.string(),
});

export function workflowInfoDtoFromJSON(
  jsonString: string,
): SafeParseResult<WorkflowInfoDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkflowInfoDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkflowInfoDto' from JSON`,
  );
}
