export type ClaudeMcpServerCategory =
  | 'productivity'
  | 'communication'
  | 'code'
  | 'data'
  | 'sales-and-marketing'
  | 'financial-services'
  | 'design'
  | 'health-and-wellness'
  | 'other';

export type ClaudeMcpServer = {
  /** Stable identifier used as a key in selections */
  id: string;
  name: string;
  description: string;
  /** Remote MCP server URL (used to configure the connection) */
  url: string;
  category: ClaudeMcpServerCategory;
  /** Whether this server appears in the "Popular" section of the picker */
  popular: boolean;
};

export const CLAUDE_MCP_SERVERS: ClaudeMcpServer[] = [
  // ── Popular ────────────────────────────────────────────────────────────────
  {
    id: 'slack',
    name: 'Slack',
    description: 'Read and send Slack messages, manage channels and workspaces.',
    url: 'https://mcp.slack.com/mcp',
    category: 'communication',
    popular: true,
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Access and manage Linear issues, projects, and cycles.',
    url: 'https://mcp.linear.app/sse',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'atlassian-rovo',
    name: 'Atlassian Rovo',
    description: 'Access Jira issues and Confluence pages in one integration.',
    url: 'https://mcp.atlassian.com/v1/mcp',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Interact with repositories, pull requests, issues, and code.',
    url: 'https://api.githubcopilot.com/mcp/sse',
    category: 'code',
    popular: true,
  },
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Access error events, issues, and performance data from Sentry.',
    url: 'https://mcp.sentry.io/sse',
    category: 'code',
    popular: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Read and write Notion pages, databases, and blocks.',
    url: 'https://api.notion.com/mcp/sse',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Coordinate tasks, projects, and goals in Asana.',
    url: 'https://app.asana.com/api/1.0/mcp/sse',
    category: 'productivity',
    popular: true,
  },
  {
    id: 'amplitude',
    name: 'Amplitude',
    description: 'Retrieve behavioral analytics and product insights from Amplitude.',
    url: 'https://mcp.amplitude.com/sse',
    category: 'data',
    popular: true,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Bring your Airtable structured data and databases to Claude.',
    url: 'https://mcp.airtable.com/mcp',
    category: 'data',
    popular: true,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Query payments, customers, subscriptions, and disputes.',
    url: 'https://mcp.stripe.com',
    category: 'financial-services',
    popular: true,
  },
  {
    id: 'intercom',
    name: 'Intercom',
    description: 'Access customer conversations, contacts, and support tickets.',
    url: 'https://mcp.intercom.io/sse',
    category: 'communication',
    popular: true,
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'Query metrics, logs, traces, and alerts from Datadog.',
    url: 'https://mcp.datadoghq.com/sse',
    category: 'code',
    popular: true,
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    description: 'Manage incidents, schedules, and on-call rotations in PagerDuty.',
    url: 'https://mcp.pagerduty.com/sse',
    category: 'code',
    popular: true,
  },

  // ── All others ─────────────────────────────────────────────────────────────
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    description: 'Autonomous marketing automation for campaigns and contacts.',
    url: 'https://mcp.activecampaign.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'adobe-experience-manager',
    name: 'Adobe Experience Manager',
    description: 'Manage your Adobe Experience Manager content.',
    url: 'https://mcp.adobe.com/aem/sse',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'ahrefs',
    name: 'Ahrefs',
    description: 'SEO analytics, backlinks, keywords, and AI search data.',
    url: 'https://mcp.ahrefs.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'airwallex',
    name: 'Airwallex',
    description: 'Integrate with the Airwallex global payments platform.',
    url: 'https://mcp.airwallex.com/sse',
    category: 'financial-services',
    popular: false,
  },
  {
    id: 'apollo',
    name: 'Apollo.io',
    description: 'Find buyers, book meetings, and manage your sales pipeline.',
    url: 'https://mcp.apollo.io/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'attio',
    name: 'Attio',
    description: 'Search, manage, and update your Attio CRM from Claude.',
    url: 'https://mcp.attio.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'aws-marketplace',
    name: 'AWS Marketplace',
    description: 'Discover, evaluate, and buy cloud solutions on AWS.',
    url: 'https://mcp.aws.amazon.com/marketplace/sse',
    category: 'code',
    popular: false,
  },
  {
    id: 'box',
    name: 'Box',
    description: 'Access and manage files, folders, and documents in Box.',
    url: 'https://mcp.box.com/sse',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'brex',
    name: 'Brex',
    description: 'Manage corporate cards, expenses, and budgets in Brex.',
    url: 'https://mcp.brex.com/sse',
    category: 'financial-services',
    popular: false,
  },
  {
    id: 'canva',
    name: 'Canva',
    description: 'Create and edit designs using Canva templates and assets.',
    url: 'https://www.canva.com/mcp/sse',
    category: 'design',
    popular: false,
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Manage Cloudflare DNS, Workers, and security settings.',
    url: 'https://mcp.cloudflare.com/sse',
    category: 'code',
    popular: false,
  },
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Read and write Confluence documentation pages.',
    url: 'https://mcp.atlassian.com/v1/mcp',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Access, share, and manage files stored in Dropbox.',
    url: 'https://mcp.dropbox.com/sse',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Inspect and work with Figma designs and components.',
    url: 'https://mcp.figma.com/mcp',
    category: 'design',
    popular: false,
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    description: 'Manage support tickets, agents, and contacts in Freshdesk.',
    url: 'https://mcp.freshworks.com/freshdesk/sse',
    category: 'communication',
    popular: false,
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    description: 'Query website traffic and user behavior data from GA4.',
    url: 'https://mcp.google.com/analytics/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Read and manage files and folders in Google Drive.',
    url: 'https://mcp.google.com/drive/sse',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Read, write, and analyze data in Google Sheets.',
    url: 'https://mcp.google.com/sheets/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'Access contacts, deals, companies, and marketing data from HubSpot.',
    url: 'https://mcp.hubspot.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Create, update, and query Jira issues and sprints.',
    url: 'https://mcp.atlassian.com/v1/mcp',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'looker',
    name: 'Looker',
    description: 'Run Looker queries and access business intelligence data.',
    url: 'https://mcp.looker.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    description: 'Query product analytics and user behavior insights from Mixpanel.',
    url: 'https://mcp.mixpanel.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'mongodb-atlas',
    name: 'MongoDB Atlas',
    description: 'Query and manage MongoDB Atlas databases and clusters.',
    url: 'https://mcp.mongodb.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Interact with Neon serverless Postgres databases.',
    url: 'https://mcp.neon.tech/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'okta',
    name: 'Okta',
    description: 'Manage users, groups, and applications in Okta.',
    url: 'https://mcp.okta.com/sse',
    category: 'productivity',
    popular: false,
  },
  {
    id: 'plaid',
    name: 'Plaid',
    description: 'Access financial accounts, transactions, and identity data via Plaid.',
    url: 'https://mcp.plaid.com/sse',
    category: 'financial-services',
    popular: false,
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Access Salesforce CRM records, leads, opportunities, and reports.',
    url: 'https://mcp.salesforce.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'segment',
    name: 'Segment',
    description: 'Manage customer data pipelines and events in Segment.',
    url: 'https://mcp.segment.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'Access orders, products, customers, and analytics in Shopify.',
    url: 'https://mcp.shopify.com/sse',
    category: 'sales-and-marketing',
    popular: false,
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Query Snowflake data warehouses and manage SQL pipelines.',
    url: 'https://mcp.snowflake.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'square',
    name: 'Square',
    description: 'Access payments, inventory, customers, and orders from Square.',
    url: 'https://mcp.squareup.com/sse',
    category: 'financial-services',
    popular: false,
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Interact with Supabase databases, auth, and storage.',
    url: 'https://mcp.supabase.com/sse',
    category: 'data',
    popular: false,
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'Send SMS, make calls, and manage Twilio resources.',
    url: 'https://mcp.twilio.com/sse',
    category: 'communication',
    popular: false,
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    description: 'Manage support tickets, users, and knowledge base articles.',
    url: 'https://mcp.zendesk.com/sse',
    category: 'communication',
    popular: false,
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Trigger and manage Zaps across thousands of connected apps.',
    url: 'https://mcp.zapier.com/sse',
    category: 'productivity',
    popular: false,
  },
];

export const CLAUDE_POPULAR_MCP_SERVERS = CLAUDE_MCP_SERVERS.filter((s) => s.popular);
