// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CreateUpdateTopicRequestDto struct {
	// The unique key identifier for the topic. The key must contain only alphanumeric characters (a-z, A-Z, 0-9), hyphens (-), underscores (_), colons (:), or be a valid email address.
	Key string `json:"key"`
	// The display name for the topic
	Name *string `json:"name,omitempty"`
}

func (o *CreateUpdateTopicRequestDto) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *CreateUpdateTopicRequestDto) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
