// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TLSOptions struct {
}

type CredentialsDto struct {
	APIKey                    *string     `json:"apiKey,omitempty"`
	User                      *string     `json:"user,omitempty"`
	SecretKey                 *string     `json:"secretKey,omitempty"`
	Domain                    *string     `json:"domain,omitempty"`
	Password                  *string     `json:"password,omitempty"`
	Host                      *string     `json:"host,omitempty"`
	Port                      *string     `json:"port,omitempty"`
	Secure                    *bool       `json:"secure,omitempty"`
	Region                    *string     `json:"region,omitempty"`
	AccountSid                *string     `json:"accountSid,omitempty"`
	MessageProfileID          *string     `json:"messageProfileId,omitempty"`
	Token                     *string     `json:"token,omitempty"`
	From                      *string     `json:"from,omitempty"`
	SenderName                *string     `json:"senderName,omitempty"`
	ProjectName               *string     `json:"projectName,omitempty"`
	ApplicationID             *string     `json:"applicationId,omitempty"`
	ClientID                  *string     `json:"clientId,omitempty"`
	RequireTLS                *bool       `json:"requireTls,omitempty"`
	IgnoreTLS                 *bool       `json:"ignoreTls,omitempty"`
	TLSOptions                *TLSOptions `json:"tlsOptions,omitempty"`
	BaseURL                   *string     `json:"baseUrl,omitempty"`
	WebhookURL                *string     `json:"webhookUrl,omitempty"`
	RedirectURL               *string     `json:"redirectUrl,omitempty"`
	Hmac                      *bool       `json:"hmac,omitempty"`
	ServiceAccount            *string     `json:"serviceAccount,omitempty"`
	IPPoolName                *string     `json:"ipPoolName,omitempty"`
	APIKeyRequestHeader       *string     `json:"apiKeyRequestHeader,omitempty"`
	SecretKeyRequestHeader    *string     `json:"secretKeyRequestHeader,omitempty"`
	IDPath                    *string     `json:"idPath,omitempty"`
	DatePath                  *string     `json:"datePath,omitempty"`
	APIToken                  *string     `json:"apiToken,omitempty"`
	AuthenticateByToken       *bool       `json:"authenticateByToken,omitempty"`
	AuthenticationTokenKey    *string     `json:"authenticationTokenKey,omitempty"`
	InstanceID                *string     `json:"instanceId,omitempty"`
	AlertUID                  *string     `json:"alertUid,omitempty"`
	Title                     *string     `json:"title,omitempty"`
	ImageURL                  *string     `json:"imageUrl,omitempty"`
	State                     *string     `json:"state,omitempty"`
	ExternalLink              *string     `json:"externalLink,omitempty"`
	ChannelID                 *string     `json:"channelId,omitempty"`
	PhoneNumberIdentification *string     `json:"phoneNumberIdentification,omitempty"`
	AccessKey                 *string     `json:"accessKey,omitempty"`
}

func (o *CredentialsDto) GetAPIKey() *string {
	if o == nil {
		return nil
	}
	return o.APIKey
}

func (o *CredentialsDto) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *CredentialsDto) GetSecretKey() *string {
	if o == nil {
		return nil
	}
	return o.SecretKey
}

func (o *CredentialsDto) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *CredentialsDto) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *CredentialsDto) GetHost() *string {
	if o == nil {
		return nil
	}
	return o.Host
}

func (o *CredentialsDto) GetPort() *string {
	if o == nil {
		return nil
	}
	return o.Port
}

func (o *CredentialsDto) GetSecure() *bool {
	if o == nil {
		return nil
	}
	return o.Secure
}

func (o *CredentialsDto) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *CredentialsDto) GetAccountSid() *string {
	if o == nil {
		return nil
	}
	return o.AccountSid
}

func (o *CredentialsDto) GetMessageProfileID() *string {
	if o == nil {
		return nil
	}
	return o.MessageProfileID
}

func (o *CredentialsDto) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *CredentialsDto) GetFrom() *string {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *CredentialsDto) GetSenderName() *string {
	if o == nil {
		return nil
	}
	return o.SenderName
}

func (o *CredentialsDto) GetProjectName() *string {
	if o == nil {
		return nil
	}
	return o.ProjectName
}

func (o *CredentialsDto) GetApplicationID() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationID
}

func (o *CredentialsDto) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *CredentialsDto) GetRequireTLS() *bool {
	if o == nil {
		return nil
	}
	return o.RequireTLS
}

func (o *CredentialsDto) GetIgnoreTLS() *bool {
	if o == nil {
		return nil
	}
	return o.IgnoreTLS
}

func (o *CredentialsDto) GetTLSOptions() *TLSOptions {
	if o == nil {
		return nil
	}
	return o.TLSOptions
}

func (o *CredentialsDto) GetBaseURL() *string {
	if o == nil {
		return nil
	}
	return o.BaseURL
}

func (o *CredentialsDto) GetWebhookURL() *string {
	if o == nil {
		return nil
	}
	return o.WebhookURL
}

func (o *CredentialsDto) GetRedirectURL() *string {
	if o == nil {
		return nil
	}
	return o.RedirectURL
}

func (o *CredentialsDto) GetHmac() *bool {
	if o == nil {
		return nil
	}
	return o.Hmac
}

func (o *CredentialsDto) GetServiceAccount() *string {
	if o == nil {
		return nil
	}
	return o.ServiceAccount
}

func (o *CredentialsDto) GetIPPoolName() *string {
	if o == nil {
		return nil
	}
	return o.IPPoolName
}

func (o *CredentialsDto) GetAPIKeyRequestHeader() *string {
	if o == nil {
		return nil
	}
	return o.APIKeyRequestHeader
}

func (o *CredentialsDto) GetSecretKeyRequestHeader() *string {
	if o == nil {
		return nil
	}
	return o.SecretKeyRequestHeader
}

func (o *CredentialsDto) GetIDPath() *string {
	if o == nil {
		return nil
	}
	return o.IDPath
}

func (o *CredentialsDto) GetDatePath() *string {
	if o == nil {
		return nil
	}
	return o.DatePath
}

func (o *CredentialsDto) GetAPIToken() *string {
	if o == nil {
		return nil
	}
	return o.APIToken
}

func (o *CredentialsDto) GetAuthenticateByToken() *bool {
	if o == nil {
		return nil
	}
	return o.AuthenticateByToken
}

func (o *CredentialsDto) GetAuthenticationTokenKey() *string {
	if o == nil {
		return nil
	}
	return o.AuthenticationTokenKey
}

func (o *CredentialsDto) GetInstanceID() *string {
	if o == nil {
		return nil
	}
	return o.InstanceID
}

func (o *CredentialsDto) GetAlertUID() *string {
	if o == nil {
		return nil
	}
	return o.AlertUID
}

func (o *CredentialsDto) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *CredentialsDto) GetImageURL() *string {
	if o == nil {
		return nil
	}
	return o.ImageURL
}

func (o *CredentialsDto) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

func (o *CredentialsDto) GetExternalLink() *string {
	if o == nil {
		return nil
	}
	return o.ExternalLink
}

func (o *CredentialsDto) GetChannelID() *string {
	if o == nil {
		return nil
	}
	return o.ChannelID
}

func (o *CredentialsDto) GetPhoneNumberIdentification() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumberIdentification
}

func (o *CredentialsDto) GetAccessKey() *string {
	if o == nil {
		return nil
	}
	return o.AccessKey
}
