// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MessageButton struct {
	// Type of button for the action result
	Type ButtonTypeEnum `json:"type"`
	// Content of the button
	Content string `json:"content"`
	// Content of the result when the button is clicked
	ResultContent *string `json:"resultContent,omitempty"`
}

func (o *MessageButton) GetType() ButtonTypeEnum {
	if o == nil {
		return ButtonTypeEnum("")
	}
	return o.Type
}

func (o *MessageButton) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *MessageButton) GetResultContent() *string {
	if o == nil {
		return nil
	}
	return o.ResultContent
}
