// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// MonthlyTypeEnum - Type of monthly schedule
type MonthlyTypeEnum string

const (
	MonthlyTypeEnumEach MonthlyTypeEnum = "each"
	MonthlyTypeEnumOn   MonthlyTypeEnum = "on"
)

func (e MonthlyTypeEnum) ToPointer() *MonthlyTypeEnum {
	return &e
}
func (e *MonthlyTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "each":
		fallthrough
	case "on":
		*e = MonthlyTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for MonthlyTypeEnum: %v", v)
	}
}
