// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type NotificationGroup struct {
	ID             *string `json:"_id,omitempty"`
	Name           string  `json:"name"`
	EnvironmentID  string  `json:"_environmentId"`
	OrganizationID string  `json:"_organizationId"`
	ParentID       *string `json:"_parentId,omitempty"`
}

func (o *NotificationGroup) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *NotificationGroup) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *NotificationGroup) GetEnvironmentID() string {
	if o == nil {
		return ""
	}
	return o.EnvironmentID
}

func (o *NotificationGroup) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *NotificationGroup) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}
