// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PushStepUpsertDtoControlValues - Control values for the Push step
type PushStepUpsertDtoControlValues struct {
	// JSONLogic filter conditions for conditionally skipping the step execution. Supports complex logical operations with AND, OR, and comparison operators. See https://jsonlogic.com/ for full typing reference.
	Skip map[string]any `json:"skip,omitempty"`
	// Subject/title of the push notification.
	Subject *string `json:"subject,omitempty"`
	// Body content of the push notification.
	Body *string `json:"body,omitempty"`
}

func (o *PushStepUpsertDtoControlValues) GetSkip() map[string]any {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *PushStepUpsertDtoControlValues) GetSubject() *string {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *PushStepUpsertDtoControlValues) GetBody() *string {
	if o == nil {
		return nil
	}
	return o.Body
}

type PushStepUpsertDto struct {
	// Unique identifier of the step
	ID *string `json:"_id,omitempty"`
	// Name of the step
	Name string `json:"name"`
	// Type of the step
	Type StepTypeEnum `json:"type"`
	// Control values for the Push step
	ControlValues *PushStepUpsertDtoControlValues `json:"controlValues,omitempty"`
}

func (o *PushStepUpsertDto) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PushStepUpsertDto) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *PushStepUpsertDto) GetType() StepTypeEnum {
	if o == nil {
		return StepTypeEnum("")
	}
	return o.Type
}

func (o *PushStepUpsertDto) GetControlValues() *PushStepUpsertDtoControlValues {
	if o == nil {
		return nil
	}
	return o.ControlValues
}
