// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ResourceOriginEnum - Origin of the workflow
type ResourceOriginEnum string

const (
	ResourceOriginEnumNovuCloud   ResourceOriginEnum = "novu-cloud"
	ResourceOriginEnumNovuCloudV1 ResourceOriginEnum = "novu-cloud-v1"
	ResourceOriginEnumExternal    ResourceOriginEnum = "external"
)

func (e ResourceOriginEnum) ToPointer() *ResourceOriginEnum {
	return &e
}
func (e *ResourceOriginEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "novu-cloud":
		fallthrough
	case "novu-cloud-v1":
		fallthrough
	case "external":
		*e = ResourceOriginEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ResourceOriginEnum: %v", v)
	}
}
