// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SmsRenderOutput struct {
	// Body of the SMS message
	Body string `json:"body"`
}

func (o *SmsRenderOutput) GetBody() string {
	if o == nil {
		return ""
	}
	return o.Body
}
