// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// StepIntegrationIssueEnum - Type of integration issue
type StepIntegrationIssueEnum string

const (
	StepIntegrationIssueEnumMissingIntegration StepIntegrationIssueEnum = "MISSING_INTEGRATION"
)

func (e StepIntegrationIssueEnum) ToPointer() *StepIntegrationIssueEnum {
	return &e
}
func (e *StepIntegrationIssueEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "MISSING_INTEGRATION":
		*e = StepIntegrationIssueEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StepIntegrationIssueEnum: %v", v)
	}
}
