// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Subscriber - The subscriber information
type Subscriber struct {
	// The identifier of the subscriber
	ID string `json:"_id"`
	// The external identifier of the subscriber
	SubscriberID string `json:"subscriberId"`
	// The avatar URL of the subscriber
	Avatar *string `json:"avatar,omitempty"`
	// The first name of the subscriber
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the subscriber
	LastName *string `json:"lastName,omitempty"`
	// The email of the subscriber
	Email *string `json:"email,omitempty"`
}

func (o *Subscriber) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Subscriber) GetSubscriberID() string {
	if o == nil {
		return ""
	}
	return o.SubscriberID
}

func (o *Subscriber) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *Subscriber) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *Subscriber) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *Subscriber) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

type SubscriptionDto struct {
	// The unique identifier of the subscription
	ID string `json:"_id"`
	// The topic information
	Topic TopicDto `json:"topic"`
	// The subscriber information
	Subscriber *Subscriber `json:"subscriber"`
	// The creation date of the subscription
	CreatedAt string `json:"createdAt"`
	// The last update date of the subscription
	UpdatedAt string `json:"updatedAt"`
}

func (o *SubscriptionDto) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SubscriptionDto) GetTopic() TopicDto {
	if o == nil {
		return TopicDto{}
	}
	return o.Topic
}

func (o *SubscriptionDto) GetSubscriber() *Subscriber {
	if o == nil {
		return nil
	}
	return o.Subscriber
}

func (o *SubscriptionDto) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *SubscriptionDto) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}
