// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// TimeUnitEnum - Time unit
type TimeUnitEnum string

const (
	TimeUnitEnumSeconds TimeUnitEnum = "seconds"
	TimeUnitEnumMinutes TimeUnitEnum = "minutes"
	TimeUnitEnumHours   TimeUnitEnum = "hours"
	TimeUnitEnumDays    TimeUnitEnum = "days"
	TimeUnitEnumWeeks   TimeUnitEnum = "weeks"
	TimeUnitEnumMonths  TimeUnitEnum = "months"
)

func (e TimeUnitEnum) ToPointer() *TimeUnitEnum {
	return &e
}
func (e *TimeUnitEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "seconds":
		fallthrough
	case "minutes":
		fallthrough
	case "hours":
		fallthrough
	case "days":
		fallthrough
	case "weeks":
		fallthrough
	case "months":
		*e = TimeUnitEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TimeUnitEnum: %v", v)
	}
}
