// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UpdateTopicRequestDto struct {
	// The display name for the topic
	Name string `json:"name"`
}

func (o *UpdateTopicRequestDto) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
