// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowListResponseDto struct {
	// Name of the workflow
	Name string `json:"name"`
	// Tags associated with the workflow
	Tags []string `json:"tags,omitempty"`
	// Last updated timestamp
	UpdatedAt string `json:"updatedAt"`
	// Creation timestamp
	CreatedAt string `json:"createdAt"`
	// Unique database identifier
	ID string `json:"_id"`
	// Workflow identifier
	WorkflowID string `json:"workflowId"`
	// Workflow slug
	Slug string `json:"slug"`
	// Status of the workflow
	Status WorkflowStatusEnum `json:"status"`
	// Origin of the workflow
	Origin ResourceOriginEnum `json:"origin"`
	// Timestamp of the last workflow trigger
	LastTriggeredAt *string `json:"lastTriggeredAt,omitempty"`
	// Overview of step types in the workflow
	StepTypeOverviews []StepTypeEnum `json:"stepTypeOverviews"`
}

func (o *WorkflowListResponseDto) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkflowListResponseDto) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *WorkflowListResponseDto) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *WorkflowListResponseDto) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *WorkflowListResponseDto) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *WorkflowListResponseDto) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *WorkflowListResponseDto) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *WorkflowListResponseDto) GetStatus() WorkflowStatusEnum {
	if o == nil {
		return WorkflowStatusEnum("")
	}
	return o.Status
}

func (o *WorkflowListResponseDto) GetOrigin() ResourceOriginEnum {
	if o == nil {
		return ResourceOriginEnum("")
	}
	return o.Origin
}

func (o *WorkflowListResponseDto) GetLastTriggeredAt() *string {
	if o == nil {
		return nil
	}
	return o.LastTriggeredAt
}

func (o *WorkflowListResponseDto) GetStepTypeOverviews() []StepTypeEnum {
	if o == nil {
		return []StepTypeEnum{}
	}
	return o.StepTypeOverviews
}
