import { MemberRoleEnum, PermissionsEnum } from '@novu/shared';

export const ROLE_PERMISSIONS: Record<MemberRoleEnum, PermissionsEnum[]> = {
  [MemberRoleEnum.OWNER]: [
    PermissionsEnum.WORKFLOW_READ,
    PermissionsEnum.WORKFLOW_WRITE,
    PermissionsEnum.WEBHOOK_READ,
    PermissionsEnum.WEBHOOK_WRITE,
    PermissionsEnum.ENVIRONMENT_WRITE,
    PermissionsEnum.API_KEY_READ,
    PermissionsEnum.API_KEY_WRITE,
    PermissionsEnum.EVENT_WRITE,
    PermissionsEnum.INTEGRATION_READ,
    PermissionsEnum.INTEGRATION_WRITE,
    PermissionsEnum.MESSAGE_READ,
    PermissionsEnum.MESSAGE_WRITE,
    PermissionsEnum.PARTNER_INTEGRATION_READ,
    PermissionsEnum.PARTNER_INTEGRATION_WRITE,
    PermissionsEnum.SUBSCRIBER_READ,
    PermissionsEnum.SUBSCRIBER_WRITE,
    PermissionsEnum.TOPIC_READ,
    PermissionsEnum.TOPIC_WRITE,
    PermissionsEnum.BILLING_WRITE,
    PermissionsEnum.ORG_METADATA_WRITE,
    PermissionsEnum.NOTIFICATION_READ,
    PermissionsEnum.BRIDGE_WRITE,
    PermissionsEnum.ORG_SETTINGS_WRITE,
    PermissionsEnum.ORG_SETTINGS_READ,
  ],
  [MemberRoleEnum.ADMIN]: [
    PermissionsEnum.WORKFLOW_READ,
    PermissionsEnum.WORKFLOW_WRITE,
    PermissionsEnum.WEBHOOK_READ,
    PermissionsEnum.WEBHOOK_WRITE,
    PermissionsEnum.ENVIRONMENT_WRITE,
    PermissionsEnum.API_KEY_READ,
    PermissionsEnum.API_KEY_WRITE,
    PermissionsEnum.EVENT_WRITE,
    PermissionsEnum.INTEGRATION_READ,
    PermissionsEnum.INTEGRATION_WRITE,
    PermissionsEnum.MESSAGE_READ,
    PermissionsEnum.MESSAGE_WRITE,
    PermissionsEnum.PARTNER_INTEGRATION_READ,
    PermissionsEnum.PARTNER_INTEGRATION_WRITE,
    PermissionsEnum.SUBSCRIBER_READ,
    PermissionsEnum.SUBSCRIBER_WRITE,
    PermissionsEnum.TOPIC_READ,
    PermissionsEnum.TOPIC_WRITE,
    PermissionsEnum.ORG_METADATA_WRITE,
    PermissionsEnum.NOTIFICATION_READ,
    PermissionsEnum.BRIDGE_WRITE,
    PermissionsEnum.ORG_SETTINGS_WRITE,
    PermissionsEnum.ORG_SETTINGS_READ,
  ],
  [MemberRoleEnum.AUTHOR]: [
    PermissionsEnum.WORKFLOW_READ,
    PermissionsEnum.WORKFLOW_WRITE,
    PermissionsEnum.EVENT_WRITE,
    PermissionsEnum.INTEGRATION_READ,
    PermissionsEnum.INTEGRATION_WRITE,
    PermissionsEnum.MESSAGE_READ,
    PermissionsEnum.SUBSCRIBER_READ,
    PermissionsEnum.SUBSCRIBER_WRITE,
    PermissionsEnum.TOPIC_READ,
    PermissionsEnum.TOPIC_WRITE,
    PermissionsEnum.NOTIFICATION_READ,
    PermissionsEnum.BRIDGE_WRITE,
  ],
  [MemberRoleEnum.VIEWER]: [
    PermissionsEnum.WORKFLOW_READ,
    PermissionsEnum.INTEGRATION_READ,
    PermissionsEnum.MESSAGE_READ,
    PermissionsEnum.SUBSCRIBER_READ,
    PermissionsEnum.TOPIC_READ,
    PermissionsEnum.NOTIFICATION_READ,
  ],
  [MemberRoleEnum.OSS_MEMBER]: [],
  [MemberRoleEnum.OSS_ADMIN]: [],
};

type UsedPermissions = (typeof ROLE_PERMISSIONS)[MemberRoleEnum][number];
type UnusedPermissions = Exclude<PermissionsEnum, UsedPermissions>;
type AssertAllPermissionsUsed = UnusedPermissions extends never ? true : `Missing permissions: ${UnusedPermissions}`;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _assertAllPermissionsUsed: AssertAllPermissionsUsed = true;
