name: Deploy Notification Center Web Component

on:
  workflow_call:
    inputs:
      env:
        description: 'Deployment environment - choose between dev and prod'
        required: true
        type: string

jobs:
  set_environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - id: set_env
        run: |
          if echo "${{ inputs.env }}" | grep -qwi 'prod'; then
            echo "environment=Production" >> "$GITHUB_OUTPUT"
          else
            echo "environment=Development" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: set_environment
    uses: ./.github/workflows/cloud-deploy-reusable-notification-center.yml

  deploy_web_component:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: ${{ needs.set_environment.outputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: notification-center-web-component
          path: packages/notification-center/dist/umd

      - name: Deploy Notification Center Web Component Dev
        if: ${{ contains(inputs.env, 'dev') }}
        uses: scopsy/actions-netlify@develop
        with:
          publish-dir: packages/notification-center/dist/umd
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: dev
          production-deploy: false
          alias: dev
          github-deployment-environment: development
          github-deployment-description: Notification Center Web Component Deployment
          netlify-config-path: packages/notification-center/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 69f27d21-6946-455f-8715-eae2c7931fe0
        timeout-minutes: 1

      - name: Deploy Notification Center Web Component Prod
        if: ${{ !contains(inputs.env, 'dev') }}
        uses: scopsy/actions-netlify@develop
        with:
          publish-dir: packages/notification-center/dist/umd
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: prod
          production-deploy: true
          alias: prod
          github-deployment-environment: Production
          github-deployment-description: Notification Center Web Component Deployment
          netlify-config-path: packages/notification-center/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 468165e2-bd64-4f33-9fd9-4b93ef8a0be0
        timeout-minutes: 1
