name: Add Triage Label

on:
  issues:
    types: [opened]

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.22.1
      - name: Install Octokit
        run: npm --prefix .github/workflows/scripts install @octokit/action@6

      - name: Check if user is a community contributor
        id: check
        run: node .github/workflows/scripts/add-triage-label.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
