name: Test @notifire/core
on:
  push:
    paths:
      - "packages/core/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: rm -rf build

      - name: restore lerna
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
      - run: yarn bootstrap
      - name: Test
        working-directory: "packages/core"
        run: yarn test
