name: Test @novu/node
on:
  push:
    paths:
      - "packages/node/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0
          run_install: true

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build
          projects: "@novu/node"
          nxCloud: true

      - name: Test
        working-directory: "packages/node"
        run: pnpm test
